### ISSUE TITLE
Interface function: play_sound(filepath)

### ISSUE THREAD

**Issue by z16** [Windower/Lua#10]
ChatMon can play sounds, so I figured there must be a library for that in use already. It would be nice if we could define our own sounds, and even better if filepath could be relative to the addon directory, so we can just put sounds in there and play them with no additional path considerations.

**Comment by Feary** [comment]
http://viremo.eludi.net/proteaAudio/index.html 

i found this and was working if this would work?

**Comment by Pr0c3ss0r** [comment]
windower.play_sound(filepath)

Not working.

**Comment by Byrth** [comment]
This function works fine for me. You need to make sure that the instance of windower you're playing the sound from is not muted.
