### ISSUE TITLE
Libs folder check.

### ISSUE THREAD

**Issue by Pheelix** [Windower/Lua#101]
Need to have windower check on startup if libs folder is in the addons folder.  Talked to Iryoku about it.  Had me post it as a issue for it.

**Comment by z16** [comment]
This is not a Lua bug but a Launcher problem, since that component is responsible for maintaining the folder structure and downloading relevant content.

Does it not install that on startup? Or do you mean, if people accidentally delete it?

**Comment by Zireael** [comment]
If I delete everything in  ..\Addons folder and then start Launcher and enable some random addons, their folders get downloaded properly, but Libs folder does not get downloaded ever. Also, I have a feeling that Libs folder does not get updated with new file changes after you start Launcher.

**Comment by z16** [comment]
It does, but not always. The behavior is pretty erratic. It works most of the time, but sometimes it doesn't. If you can find a pattern for that, please report it, it might give a better clue as to how to fix it. The truth is, the launcher has been somewhat unmaintained for a while, with various other issues coming up. It is still meant to be fixed.

**Comment by Byrth** [comment]
This has been "fixed" by forcing the launcher to download the entire libs every time that there's an update in the addon repository. Closing it for now.
