### ISSUE TITLE
Send addon issue

### ISSUE THREAD

**Issue by Laouz** [Windower/Lua#1024]
Hello, I am attempting to use the Send addon and it doesnt seem to recognize quotation marks on items.
For example i do //send (Name) /item "Soultrapper" and on my alternate accounts screen it comes up with an in-game error saying "/item Soultrapper a command error occurred.
Obviously you need quotation marks for items, it just seems send doesn't read them. Any help would be appreciated

**Comment by z16** [comment]
Windower commands use `"` to group tokens together, so it removes them. This is intended behavior and necessary for certain addon behavior, so it cannot be changed. You can bypass that by prepending a `\` character, then the double quote will be treated literally:
`//send <name> /item \"Soultrapper\"`
