### ISSUE TITLE
Menu Activation and windower.ffxi.get_mob_by_target('st')

### ISSUE THREAD

**Issue by Ivaar** [Windower/Lua#1025]
windower.ffxi.get_mob_by_target('st') doesn't return 'st' when activated from the menu, Is this intentional or a bug? Sorry I'm not very knowledgeable on this matter, is it stored in a different memory location when activated from the menu vs text macro?

**Comment by Ivaar** [comment]
Could the other variants of st be added? such as stnpc. Thanks.

**Comment by z16** [comment]
It doesn't make sense to have this for `stnpc` and similar variants (`stal`, `stpt`, etc.). `st` covers all of them, as it should just return the current sub-target selection. `windower.ffxi.get_mob_by_target` works with all strings `x` that can also be printed in the chatlog by typing in `<x>`. You can do `/echo <st>` to print your current sub-target, but you cannot do `/echo <stal>`, because `stal` is only used in a command context that limits the scope of the sub-target selector.

I'll examine why it doesn't work from within the menu later.

**Comment by z16** [comment]
I fixed this and will push a new LuaCore live after some more adjustments tomorrow.

**Comment by alphaONE2** [comment]
The following was posted by @Ivaar as Windower/Issues#600:

> Looks like this was updated today, st is still the only variant returning. Other variants appear to be returning instead as target, same with menu's, which should return as st . Here's an example.
> 
> ``` lua
> function target_change(new)
>   local target = windower.ffxi.get_mob_by_target('t')
>   local sub= windower.ffxi.get_mob_by_target('st')
>   if (sub ~= nil) then
>       log('This Is Sub-Target')
>   end
>   if (target ~= nil) and (sub == nil) then
>       log('This Is Target')
>   end
> end
> windower.register_event('target change', target_change)
> ```
> 
> It works as expected when using st , however all other variants and menu return nil, and instead the second statement executes. By Menu i refer to Switch Target(while engaged) and selecting spells/ja/ws.

@z16: It seems there may still be a problem here.

**Comment by z16** [comment]
Everything seems to be working fine for me, except that `windower.ffxi.get_mob_by_target('t')` returns the sub-target, if only the sub-target exists and no main target. I'm not sure if that should be adjusted, but possibly.

What do you mean that it doesn't work with "other variants", what other variants?

**Comment by Ivaar** [comment]
windower.ffxi.get_mob_by_target('st') only works as expected with st, not stnpc or stpc, instead they are being returned with windower.ffxi.get_mob_by_target('t'). regardless if main target exists. I know i was tired last night, but something isn't right. Did you accidentally add stnpc and stpc to 't' table, rather than st table?

**Comment by Ivaar** [comment]
@IryokuChevalier Sorry I didn't realize I could post once the issue closed. I should have checked this page rather than assuming. Thank You!

**Comment by Ivaar** [comment]
Sorry if i was confusing, I just tested it again, this is what's happening.
I target a mob then use /target st This logs "This is Sub-Target" when i switch mobs.
If i use /target stnpc, in the same manner, it reads "This Is Target".
And actually if i use /target st without selecting a main target first, it still logs, "This Is Sub-Target" as I expected it should. The problem i'm having is with stnpc specifically. Thanks for looking into this.

**Comment by Ivaar** [comment]
After more playing around, I came up with a clearer example.

```
function target_change(new)
  local target = windower.ffxi.get_mob_by_target('t')
  local sub= windower.ffxi.get_mob_by_target('st')
  if (sub ~= nil) then
      log('This Is Sub-Target: '.. (sub.id) ..' ID')
  end
  if (target ~= nil) then
      log('This Is Target: '.. (target.id) ..' ID')
  end
end
windower.register_event('target change', target_change)
```

I think this should provide all the details you need. Engage a mob and use `/target <st>` You will see both values are returned and printed to your log. Now try `/target <stnpc>` only the latter will be printed. `windower.ffxi.get_mob_by_target('st')` always returns nil for `<stnpc>`.
`windower.ffxi.get_mob_by_target('t')` returns your current target when using `<stnpc>` as you can see the mob id printed in the log with this above script does not change when switching targets. 
I hope this can be adjusted, as i would like to differentiate between current target and sub target, when using `<stnpc>` macros. Instead of being forced to use `<st>` while engaged and have to target players too.
I Absolutely agree with you `windower.ffxi.get_mob_by_target('t')` should return sub-target if no main target exists. However this isn't my issue, There's no way to return your sub-target using <stnpc> if you have a main target. sorry to be an annoyance, Thank you again, Sir.

**Comment by z16** [comment]
Your example works perfectly fine for me, as well as my own things I tried.

What version is your LuaCore? Are you on live or dev?

**Comment by z16** [comment]
Pushed a new LuaCore, added `stpt` and `stal` to the mix, although they will only work with actual `stpt` and `stal` targeting, not with other `st` targets.

 Adjusted it so that `t` will _not_ return the `st` if no `t` is available. However, now you can add multiple values to `windower.ffxi.get_mob_by_target` like this:

``` lua
windower.ffxi.get_mob_by_target('t', 'st')
```

This should be a good compromise. I still cannot replicate your other issues.

**Comment by Ivaar** [comment]
Okay I just checked out DEV version and it works. Not working on live, I think part of you adjustments missed the update the other day. Not sure, all is good. Sorry to consume your time.

**Comment by z16** [comment]
Np at all, now we know that live and dev are different, which I was not aware of :)
