### ISSUE TITLE
Gearswap not refreshing player.inventory in certain circumstances

### ISSUE THREAD

**Issue by Sechs** [Windower/Lua#1028]
I think I found what could be a small bug in Gearswap, which is not refreshing player.inventory under certain circumstances.

_step-by-step description of what happens_
1) Atoyac is already in inventory
2) I swap job to BRD from /NIN to /DNC 
3) The two functions get launched, and it swaps my variable correctly to "Atoyac", print_set displays Atoyac in the items list.
4) I try swapping job (launches the function automatically from within the other one) or using the self_command (launches the specific function only) and both seem to work.
5) I take off my Atoyac and put it in my Satchel, and do the opposite with my Izhiikoh
6) I try to swap job again between /NIN and /DNC
7) _The variable remains set to "Atoyac" and the print_set still displays Atoyac in my inventory, even if it's not there anymore. It doesn't display Izhiikoh instead._
8) I try to repeat step 6) multiple times, but nothing changes
9) _I try to launch the function directly from the self_command, it correctly swaps the variable to Izhiikoh, Print_set displays Izhiikoh in the inventory list and no more Atoyac._

**Comment by Sechs** [comment]
_Details on the functions and Lua used:_

http://pastebin.com/yZTYibt6

 To explain again correctly I have two custom functions:
 set_dagger() ==> sets the dagger to be used offhand in my TP sets while /NIN or /DNC
 set_idle_mode(sub_job) ==> sets a few things, among which my idle gear according to my subjob.

 set_dagger gets called from:
 1) set_idle_mode (if sj is /NIN or /DNC)
 2) from two different self commands

 set_idle_mode gets called from:
 1) only once at the end of function get_sets()
 2) within function sub_job_change

**Comment by Byrth** [comment]
This has been fixed on -dev.
