### ISSUE TITLE
[BUG] Distance (addon)

### ISSUE THREAD

**Issue by Sechs** [Windower/Lua#1032]
Found a small bug.
When you have a target selected, after you go out of range (around 53 yalms) your target disappears, but distances keeps displaying the last distance it displayed concerning your last selected target.

I think this is an unintended behaviour and Distance should reset to 0 when you lose a target?

**Comment by z16** [comment]
Indeed, that's a bug, I'll examine it in a bit.

**Comment by z16** [comment]
Hm, having trouble re-creating the issue. Does it always happen to you or only occasionally/situationally? If so, what do you need to do to make it happen?

**Comment by Sechs** [comment]
Happens always, on live version at least.
Only noticed this after last game patch, don't think it was present before as well.
Maybe it's not a bug in Distance itself but in the interaction between distance and some other addon? No clue, if you need further data I'll do my best to provide.

**Comment by z16** [comment]
Can you check if it happens with [this](http://update.windower.net/dev/plugins/LuaCore.dll) LuaCore?

**Comment by Sechs** [comment]
Yes and no, depends if it requires me to shut down the game.
Can I load the new luacore simply by manually loading it after overwriting it in the folder? Or is a full shutdown of Windower and the game required?

**Comment by joshk6656** [comment]
rename luacore.dll to luacoreold.dll

replace with dll arcon gave.

in game //reload luacore

**Comment by Sechs** [comment]
Not downloading the file. (link not working) If it's the latest version published on the Dev Windower I can just copy/paste from the Dev folder though.

**Comment by joshk6656** [comment]
Thats where the link points to so it should be fine. Re-run dev launcher tho in case he pushed it after your last run.

**Comment by Sechs** [comment]
With Luacore version 1.7.10 it still happens as far as I can see from the zone I'm in. It gets to ~54.0 and stays there after the target disappears.

**Comment by z16** [comment]
Sorry, the link above was broken (updated now).

Are you using the Distance plugin as well or just the addon?

**Comment by Sechs** [comment]
I was using the Plugin. Recently moved to to addon version (along with many other plugin which have addon version) because I was told that, sooner or later, plugin versions would disappear/stop being supported.

Atm Distance (plugin) is downloaded in the plugin folder but it's set to "off" into the Plugin tab of Windower 4.

Is the link you gave me 1.7.10 or another one? (if it's 1.7.10 I won't repeat the test).

**Comment by Sechs** [comment]
Someone forgot to close this.
I posted in the Windower4 thread on BG but forgot to do it here as well.
I think it was an issue with Hook/Luacore because it got itself fixed quite some updates ago.
Working perfectly now.

**Comment by z16** [comment]
Well that's great to hear!
