### ISSUE TITLE
[bug] gearswap function file_unload() 

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1038]
function file_unload() is not allowed to finish processing before the next job file loads
this happens when changing jobs with out unloading loading gearswap
more info below

**Comment by smd111** [comment]
more info
1.its not letting function file_unload() finish before loading the next job file
i can see this by using this code below

```
Stepmax = 4
Stopsteps = false
Conquest = {}
Conquest.neck = {}
Conquest.ring = {}
Conquest.neck.change = false
Conquest.neck.case_id = 1
Conquest.ring.change = false
Conquest.neck.case_id = 1
specialweaponwscount = 0
box = {}
box.pos = {}
box.pos.x = 892
box.pos.y = 294
Changestaff = false
Usestaff = "Atk"
function file_unload()
    file_write()
end
function file_write()
    local file = io.open(lua_base_path..'data/'..player.name..'/test/'..player.main_job..'var.lua',"w")
    file:write(
        'Stepmax = '..tostring(Stepmax)..
        '\nStopsteps = '..tostring(Stopsteps)..
        '\nConquest.neck.change = '..tostring(Conquest.neck.change)..
        '\nConquest.neck.case_id = '..tostring(Conquest.neck.case_id)..
        '\nConquest.ring.change = '..tostring(Conquest.ring.change)..
        '\nConquest.neck.case_id = '..tostring(Conquest.neck.case_id)..
        '\nspecialweaponwscount = '..tostring(specialweaponwscount)..
        '\nbox.pos.x = '..tostring(box.pos.x)..
        '\nbox.pos.y = '..tostring(box.pos.y)..
        '\nChangestaff = '..tostring(Changestaff)..
        '\nUsestaff = "'..tostring(Usestaff)..'"'..
        '')
    file:close()
end
```

how to reproduce(100%)
create a folder in the dir of your test char name (i.e. if name is Byrth "gearswap\data\Byrth\test")
put the above lua in Byrth folder labled testing.lua
use: gs l testing.lua change job
you will see that the file created is not the name of the job you started on but the job you changed to

**Comment by smd111** [comment]
after more testing i found what my issue is
no mater what i do i cant get my old main job name to go in to function file_unload()

**Comment by smd111** [comment]
i traced back how the file_unload() function works and found how to fix it(but if you decide to change how it does it thats ok)

what i did to fix my issue is add in a new function in flow lua 
here is a snipit for ware i added it the function

```
        end
    elseif id == 0x100 then
    -- Scrub the equipment array if a valid outgoing job change packet is sent.
        local newmain = modified:byte(5)
        if res.jobs[newmain] and newmain ~= 0 and newmain ~= player.main_job_id then
            windower.debug('job change')

            table.clear(not_sent_out_equip)

            for id,name in pairs(default_slot_map) do
                if items.equipment[name].slot ~= empty the
```

i just simply add in a function to trigger when you change jobs

```
        end
    elseif id == 0x100 then
    -- Scrub the equipment array if a valid outgoing job change packet is sent.
        local newmain = modified:byte(5)
        if res.jobs[newmain] and newmain ~= 0 and newmain ~= player.main_job_id then
            user_pcall('main_job_chang')
            windower.debug('job change')

            table.clear(not_sent_out_equip)

            for id,name in pairs(default_slot_map) do
                if items.equipment[name].slot ~= empty the
```

i know this is not the way you or i would like this done but it does work for my uses
on the live version it was added at line 426 same on the dev version

**Comment by smd111** [comment]
more info
i have even tried this in my gearswap file but it st does not get started before the vars change

```
function outgoing_chunk(id, data, modified, injected, blocked)
    if id == 0x100 then
    file_write()
    end
end
d_outgoing_chunk = windower.raw_register_event('outgoing chunk', outgoing_chunk)
```

**Comment by Byrth** [comment]
Okay, I understand the problem and know how I will fix it, I think.

**Comment by smd111** [comment]
i would be happy with it some how doing file_unload before changing any tables on job change
or something like that

**Comment by smd111** [comment]
i know my wording sucks (dyslexia is a pain in my butt)

**Comment by Byrth** [comment]
I opened a new issue on my tracker and so I'm going to close this one: https://github.com/Byrth/Lua/issues/307

**Comment by Byrth** [comment]
This is fixed now on -dev.

**Comment by smd111** [comment]
ill give it a test when i get home

**Comment by smd111** [comment]
i gave it a test and it clearing out half of my vars before thay can be saved
but its an easy fix i just added
coroutine.sleep(1)

right after line:67 user_pcall('file_unload') in refresh.lua
