### ISSUE TITLE
Gearswap [bug] fellow table == nil with fellow out

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1046]
on live(going to test dev)
the fellow table is nil when fellow is out

i can prove it with this code

```
function precast(spell)
    file_write(spell)
    add_to_chat(7,"fellow="..tostring(fellow))
end
function file_write(a)
    file = io.open(lua_base_path..'data/'..player.name..'/Data/test.lua',"w")
    local info = {}
    save('fellow', fellow)
    file:close()
    file = nil
end
function basicSerialize (o)
    if type(o) == "number" or type(o) == "boolean" or type(value) == "nil" then
        return tostring(o)
    else   -- assume it is a string
        return string.format("%q", o)
    end
end
function save (name, value, saved)
    saved = saved or {}       -- initial value
    file:write(name, " = ")
    if type(value) == "nil" then
        file:write('nil', "\n")
    elseif type(value) == "function" then
        file:write('FUNCTION', "\n")
    elseif type(value) == "userdata" then
        file:write('userdata', "\n")
    elseif type(value) == "number" or type(value) == "string" or type(value) == "boolean" then
        file:write(basicSerialize(value), "\n")
    elseif type(value) == "table" then
        if saved[value] then    -- value already saved?
            file:write(saved[value], "\n")  -- use its previous name
        else
            saved[value] = name   -- save name for next time
            file:write("{}\n")     -- create a new table
            for k,v in pairs(value) do      -- save its fields
                local fieldname = string.format("%s[%s]", name,
                basicSerialize(k))
                save(fieldname, v, saved)
            end
        end
    else
        error("cannot save a " .. type(value))
    end
end
```

it out put is always 
fellow = nil

**Comment by Byrth** [comment]
This is likely due to windower.ffxi.get_mob_by_target('ft') returning nil, probably because it broke in some update and no one noticed (lol fellows). Arcon got a Signal Pearl today, so he will probably be able to fix this.

**Comment by smd111** [comment]
well i guess it was good i found it then

**Comment by z16** [comment]
Was this after yesterday's update? If so, it broke then but has been fixed since.

Also, please try giving us a minimal working example in the future. Something like this:

``` lua
self_command = function()
    print('Fellow table is %s':format(fellow and 'not nil' or 'nil'))
end
```

Otherwise it may take a long time to work through your code and find out what you're doing in there and where the error happens.

**Comment by smd111** [comment]
it was before yesterdays update

sorry i wanted to post the code that i saw it in so if i did something wrong it would be known

and the code could be minimized to just this in gearswap

```
function precast(spell)
    add_to_chat(7,"fellow="..tostring(fellow))
end
```

this just showed in chat
fellow= nil

**Comment by z16** [comment]
It's not as pretty as mine though :D

But still, can you see if it works now? It may have broken in a previous update and was never adjusted.

**Comment by smd111** [comment]
i cant check it now because of server maint

**Comment by smd111** [comment]
i just tested with these two

```
    add_to_chat(7,"fellow = "..tostring(fellow))
    add_to_chat(7,"windower.ffxi.get_mob_by_target('ft') = "..tostring(windower.ffxi.get_mob_by_target('ft')))
```

 add_to_chat(7,"fellow = "..tostring(fellow)) gives fellow = nil
add_to_chat(7,"windower.ffxi.get_mob_by_target('ft') = "..tostring(windower.ffxi.get_mob_by_target('ft'))) gives windower.ffxi.get_mob_by_target('ft')= table:<number>

so the windower one is working and the gearswap one is not updating

**Comment by Byrth** [comment]
Did you perform an action after summoning your fellow? GearSwap only updates its variables when an event occurs.

The exact code used is:

```
table.reassign(fellow,target_complete(windower.ffxi.get_mob_by_target('<ft>')))
```

Does "ft" work but "<ft>" not work?

**Comment by Byrth** [comment]
Nevermind, I found the problem. Fellow was never exposed to the user environment. I must have done all my testing in gearswap itself pre-release.

**Comment by smd111** [comment]
thanks
