### ISSUE TITLE
Battlemod lua runtime error

### ISSUE THREAD

**Issue by hellbladex** [Windower/Lua#1065]
Been getting an error with battlemod for a few weeks now seems to happen randomly and often. Battlemod: lua error (runtime) - battlemod/parse_action_packet.lua:159: attempt to index field '?' (a nill value) doesn't crash me but it likes to fill up my console. Thanks!

**Comment by SnickySnacks** [comment]
I'll take a look tonight. 

Could you give some information on what you are doing when it happens? 

Or I could give you a modified version of battlemod that will tell me what message is causing the error. 

I generally only play monk and pup so there are still some actions on other jobs that aren't properly handled

**Comment by hellbladex** [comment]
I'm mostly on sam and lately doing incursion but i'm fairly certain it started before the sept update. i can just be standing there while someone else is fighting and the error will pop up. Same if its just me fighting something. wish i could be more helpful but i really have no idea whats causing it even though i am watching for it,  I have np running the modified version to help figure out what the cause is. Oh i am also not using the simplified option i mainly use battlemod so i can see skillchain dmg when i blink and i haven't messed with any filters or other settings except colors incase that makes a difference.

**Comment by SnickySnacks** [comment]
Can you check in addons\battlemod\parse_action_packet.lua
assuming that line 159 is
    local color = color_filt(res.action_messages[m.message].color,v.target[1].id==Self.id)
(if it's not, tell me)

Grab my copy of parse_action_packet.lua from
http://pastebin.com/HC57dWCK
then either start FFXI or if you're already in game do 'lua reload battlemod' in the windower console.

If you get either
"Received unknown message #"
or
"Received unknown target #"
Let me know which message and the number.

**Comment by hellbladex** [comment]
just tried to force the error to happen but it was a no go starting to think its the thf in my party causing the error not sure if its possible but i'll be doing more incursion with him tonight most likely so i'll try again. Also yes line 159 in the one i have been using is 
local color = color_filt(res.action_messages[m.message].color,v.target[1].id==Self.id)

**Comment by hellbladex** [comment]
Ok got it to error pretty sure it said unknown message 736 it was 736 for sure and only "pretty sure" about the message cause the log was flying as i was in a boss fight sorry but hopefully that helps a bit.

**Comment by SnickySnacks** [comment]
Yeah, we're missing a few action messages.
I'll push an battlemod update to fail a bit cleaner on these.
You'll likely start seeing something like:

X uses Y
123 HP drained from Z

which is one of the 4 messages that aren't being handled.

Still need to get the resources updated, but at least battlemod will handle these situations a bit better in the future.

**Comment by nesstea** [comment]
I'm getting these all the time as well.

**Comment by z16** [comment]
The exact same error message?
