### ISSUE TITLE
[?bug?] mouse event

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1073]
there seams to be a bug(or something wrong) in the mouse event
when ever i use something that uses the mouse event if i pass my mouse pointer over the ffxi window it causes the ffxi screen to freeze for about 0.5 seconds every second

**Comment by z16** [comment]
I've never experienced that myself or heard anyone complain, and the mouse event is used by many addons. Are you sure this is not just because of you running expensive code in the mouse event?

**Comment by smd111** [comment]
ok i found out what the issue was
in gearswap i am using 
texts = require('texts')
so i had to copy the text lua to my gearswap files and change this function
windower.register_event('mouse', function(type, x, y, delta, blocked)
to
windower.raw_register_event('mouse', function(type, x, y, delta, blocked)
and change 
texts = require('texts')
to
texts = require('includes/extra_more/gstexts')

i think this is because gearswap needs the mouse function to be a raw registered event

**Comment by z16** [comment]
Closing, as this does not seem to be a Lua issue.
