### ISSUE TITLE
Timers BLU Buff Duration change

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#1080]
The effect duration of the following spells has been increased.

Metallic Body / Memento Mori / Reactor Cool / Saline Coat / Plasma Charge / Diamondhide / Magic Barrier / Barrier Tusk / Orcish Counterstance / Nature's Meditation / Zephyr Mantle / Triumphant Roar

**Comment by z16** [comment]
Increased to how long?

**Comment by ghost** [comment]
Nature's Meditation i know is now 90 sec, the others I dont know.

If you need me to I can set them and get times for you once I get home today, about to head out the door for work.

**Comment by z16** [comment]
Can you verify that [this post](http://www.bluegartr.com/threads/123814-10-7-2014-Update!-Findings-Discussion?p=6231030&viewfull=1#post6231030) is correct? If so, I'll use that data.

**Comment by z16** [comment]
Also, would appreciate it if you could repost this in the [Windower issue tracker](https://github.com/Windower/Issues/issues), this one is only for Lua, so we cannot apply the right tags or assign the right team.
