### ISSUE TITLE
[bug] windower.ffxi.get_spell_recasts()

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1084]
Some spells do not work with windower.ffxi.get_spell_recasts()
Reprisal recast id is 75
Crusade recast id is 142

im using this code windower.ffxi.get_spell_recasts()[recast id] and for some spells it always shows 0

**Comment by smd111** [comment]
ok it seams that the recast it was changed to the spell id

**Comment by alphaONE2** [comment]
In that case I guess we'll just update the documentation and deprecate the recast_id field on spells. The new behavior is better anyway. We'll need to update ResourceExtractor to output the spell id in the recast_id field for compatibility.
