### ISSUE TITLE
scoreboard - fails to register new ninja trait "Daken" 

### ISSUE THREAD

**Issue by AlanWarren** [Windower/Lua#1098]
Just as the title says, scoreboard doesn't track the new Ninja job trait "Daken". This is the ability where you randomly throw shuriken, similar to a monk using kick attacks. 

I can verify this by engaging a mob with a shuriken equipped, without katanas and zero hand-to-hand skill.  The only damage done is through daken proc's, yet nothing is recorded. 

Thanks

**Comment by Byrth** [comment]
This should be fixed on -dev now. I've received at least one post that it is working:
http://www.ffxiah.com/forum/topic/44841/scoreboard-daken/1/#2770099
