### ISSUE TITLE
Itemizer Issue with Remedy

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#1105]
Noticed recently that Itemizer will pull Remedy one time and use it like it is suppose to.
After that I can hit the macro again and it does nothing, will then manually move item over and suddenly it will use it.

Had this issue happen a few times in the past, was always resolved after ticket was made

Sorry to bother with issue but hope it can be fixed soon.

Thank you.

**Comment by z16** [comment]
Just to make sure, you're talking about the add-on version of Itemizer?

**Comment by ghost** [comment]
Sorry was at work and couldnt reply,

yeah it is the addon.

**Comment by ghost** [comment]
Just wanted to touch base and see if you were able to look into it at all?

**Comment by z16** [comment]
Not yet, I was away all weekend. I will look into it today.

**Comment by z16** [comment]
This should be fixed now. Sorry for the delay.
