### ISSUE TITLE
Battlemod: Crafting results in both NQ and HQ messages

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1131]
Over the weekend I noticed when crafting Bison Steak (NQ) I got the NQ message from BM at the start of crafting and then an extra HQ message appeared at the end of crafting. This is on the DEV branch, haven't had time to check on live. I have not got an HQ when crafting, so I don't know what happens in that case.

**Comment by Byrth** [comment]
Yeah, this should be fixed now.
