### ISSUE TITLE
Timers - Embolden

### ISSUE THREAD

**Issue by MartelRagnarok** [Windower/Lua#1152]
Embolden doesn't appear to be applied to protect/shell durations in timers.

Also, The embolden augment on Evasionist's Cape isn't accounted for. Here's a post on the augment testing. http://www.bluegartr.com/threads/108199-Random-Facts-Thread-Other?p=6239278&viewfull=1#post6239278

**Comment by Byrth** [comment]
Timers is a plugin issue, so I'm going to move this to Windower/Issues.
