### ISSUE TITLE
Treasury

### ISSUE THREAD

**Issue by Waffless** [Windower/Lua#1154]
Having an issue where when I zone I have to keep adding things to the list to get it to auto drop. I"m using the command //tr d + item   or //tr p + item .  I also used the /tr save command (is this correct?) I also have autodrop enabled.

My file says everything I've added to the drop/pass list is there. I'm stumped, but I"m sure it's something simple that I'm doing wrong. Any ideas?

**Comment by Waffless** [comment]
I noticed I'm getting this error:

Treasury: Lua runtime error: table index is nil

**Comment by Waffless** [comment]
I found out what was wrong and it's working perfectly now, thanks.

**Comment by z16** [comment]
Can you let me now what it was? It's been driving me nuts lol

**Comment by Waffless** [comment]
If someone was to use easy farm from ffevo then they would have to input the items each time they zone when it's running, but if  they weren't using it then treasury works just fine.

**Comment by Byrth** [comment]
Wow, I can't even imagine how easyfarm would possibly be doing that.

**Comment by z16** [comment]
Yeah, I fail to really see the connection between the two... oh well, closing.
