### ISSUE TITLE
[bug]Gearswap --aftercast not trigering

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1165]
about 1/10 of the times i cast a spell aftercast does not trigger
im using my skillup.lua which relies on aftercast to get the correct timeing
https://github.com/smd111/Gearswap-Skillup

**Comment by Byrth** [comment]
Currently GearSwap waits for (casting_time_1.1) + 1 second before it clears entries out of the command_registry table. The symptoms you're describing indicate that that isn't long enough for your connection (meaning you have a server -> client -> server latency of over 1.5 seconds). I'm going to bump up the delay to (casting_time_1.1)+2 and open an issue for myself to make sure aftercast is called for completed action events even if they don't exist in the command registry.

**Comment by smd111** [comment]
thats vary possible as the closest trunk line access is 200 miles away from me
but the funny thing is it only started today
