### ISSUE TITLE
(bug)windower.text.get_extents

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1170]
windower.text.get_extents returns nil not what its supost to

this is what im using
mx, my = windower.text.get_extents(_G[check_windows[i][2]]._name)
i know that there is more that goes here to get the name

**Comment by z16** [comment]
This works fine for me (and for many other addons, or otherwise dragging and dropping would not be working). Can you show the full code? Here is a short snippet, can you see if this works for you:

``` lua
windower.text.create('foo');
windower.text.set_text('foo', 'Testing');
windower.text.set_font('foo', 'Arial');
windower.text.set_font_size('foo', 14);
print(windower.text.get_extents('foo')); -- > 64    23
```

**Comment by z16** [comment]
On a further note, nil is returned if the name is not found, so maybe the argument you're providing is invalid. Can you print it out and make sure it's correct?

Regardless, you would probably be better off using the `texts` library.

**Comment by smd111** [comment]
this prints correctly
check_windows[i][2]
but when i do this i get nil
_G[check_windows[i][2]]._name
and i do use the text.lua but it does not give extents anyways

**Comment by z16** [comment]
Why do you need the `_G` table then?

**Comment by smd111** [comment]
i use _G to get the table so i can pass the tables name to get_extents with
windower.text.get_extents(_G[check_windows[i][2]].name)

this is my display code
https://github.com/smd111/Gearswap/blob/master/includes/extra_more/Display.lua
this worked till sunday (i did not log in yesterday)

i just tried this and no goo still gives nil
texts.extents(check_windows[i][2])
here is the out put
17:27:51 > button
17:27:51 > GearSwap: Lua runtime error: libs/texts.lua:384:
17:27:51 >   attempt to index field '?' (a nil value)

**Comment by smd111** [comment]
ok i know what the issue is the texts.lua on the live version is bad i copied the dev version ovder and now it working correctly

**Comment by z16** [comment]
Strange, but ok, that will be fixed shortly then.

**Comment by smd111** [comment]
i can only surmise its because the live version have changed
t. to meta[t]. when building the table

**Comment by z16** [comment]
But that was an entirely self-contained change, it shouldn't have changed the behavior of anything outside of `texts.lua`… if it did, it was a mistake. Either way, we're gonna push the changes live shortly, thanks for letting us know.

**Comment by smd111** [comment]
i think it because the info get changed to a local table(or a meta table) here
texts.lua (live)line:171
`t = {}
    local m = {}
    meta[t] = m`
but the fact that none the the info is returned might also be the issue
thus this is nil eather way
button = texts.new(min_window)

**Comment by smd111** [comment]
@z16 
i have been doing some testing and the only way i can get the live version of texts.lua to work is with
starting at line 171 change this is ware the get extents error originates because t is empty but it wont send m to my file

```
    t = {}
    local m = {}
    meta[t] = m
    m.name = (_addon and _addon.name or 'text') .. '_gensym_' .. tostring(t):sub(8) .. '_%.8X':format(16^8 * math.random()):sub(3)
    m.settings = settings or {}
    m.status = m.status or {visible = false, text = {}}
    m.root_settings = root_settings
    m.base_str = str
    m.keys = {}

    m.events = {}

    m.texts = {}
    m.defaults = {}
    m.formats = {}
    m.textorder = {}
```

to

```
    t = {}
    t._name = (_addon and _addon.name or 'text') .. '_gensym_' .. tostring(t):sub(8) .. '_%.8X':format(16^8 * math.random()):sub(3)
    t._settings = settings or {}
    t._status = t._status or {visible = false, text = {}}
    t._root_settings = root_settings
    t._base_str = str

    t._events = {}

    t._texts = {}
    t._defaults = {}
    t._formats = {}
    t._textorder = {}
    local m = {}
    meta[t] = m
    m.name = t._name
    m.settings = t._settings
    m.status = t._status
    m.root_settings = t._root_settings
    m.base_str = t._base_str
    m.keys = {}

    m.events = t._events

    m.texts = t._texts
    m.defaults = t._defaults
    m.formats = t._formats
    m.textorder = t._textorder
```

i cant just change it to 

```
    t = {}
    t._name = (_addon and _addon.name or 'text') .. '_gensym_' .. tostring(t):sub(8) .. '_%.8X':format(16^8 * math.random()):sub(3)
    t._settings = settings or {}
    t._status = t._status or {visible = false, text = {}}
    t._root_settings = root_settings
    t._base_str = str

    t._events = {}

    t._texts = {}
    t._defaults = {}
    t._formats = {}
    t._textorder = {}
``
because it will cause and error else ware in the file
```

**Comment by z16** [comment]
Yeah, that makes sense, since the other functions all access the `meta` table. It doesn't matter, we'll merge the dev version live shortly, probably today.

**Comment by smd111** [comment]
ok i just wanted to let you know what i found
