### ISSUE TITLE
targets_target_ID in mob array/table

### ISSUE THREAD

**Issue by ratie** [Windower/Lua#119]
If it's possible (and feasible), I'd like to request exposure of the targets_target_ID in the get_mob_by_id() table, similar to how it exists in the get_player() table.

I have a feeling that this data is available in the client for it to allow /assist commands to work, and to also turn other players' heads to focus on their current target.

Thanks!

[Edit: accidentally clicked a random button. Ignore my closing and opening >_>]

**Comment by alphaONE2** [comment]
/assist is handled server-side. there is a target field in the mob struct but it's only valid for players. we can still expose it, but its usefulness is limited because of that fact.

**Comment by z16** [comment]
Don't see a reason to implement, as it's only possible for players and already exists for those. Closing for now, post if you object to that.
