### ISSUE TITLE
Lua runtime error

### ISSUE THREAD

**Issue by raliont** [Windower/Lua#1200]
Lua runtime error; GearSwap/refresh.lua:550: "id" is not defined for numbers 

I keep receiving this error and replaced the refresh.lua but to no avail. please help.

**Comment by smd111** [comment]
go here for help with gearswap http://www.bluegartr.com/threads/119461-Gearswap-Help-Thread!
unless you are told that its a gearswap error its probably an error in your file

**Comment by Byrth** [comment]
I replied to your post in the thread smd111 linked.
