### ISSUE TITLE
Request: Toggle display of timezone for Clock addon

### ISSUE THREAD

**Issue by geekgirl101** [Windower/Lua#1201]
As the subject heading states, would love to see a toggle option to show or display the timezone next to the time on the Clock addon.

**Comment by geekgirl101** [comment]
Sorry to be reopening this, I was looking at the readme on how to hide the timezone.  I'm guessing //lua clock remove GMT was supposed to work, but it's not happening.

**Comment by z16** [comment]
Go to the settings file `Windower/addons/Clock/data/settings.xml` and change `ShowTimeZones` from `true` to `false`.

**Comment by geekgirl101** [comment]
Tried that but on reloading it just hid everything including the time and background.
