### ISSUE TITLE
Runtime errors with updates (OhShi and Infobar)

### ISSUE THREAD

**Issue by geekgirl101** [Windower/Lua#1225]
So far got these two in my console window:

OhShi: Lua runtime error: libs/texts.lua:554: bad argument #2 to 'set_stroke_color' (number expected, got string)
infobar encountered a fatal error and must be terminated. Error: Access violation in PreRender method.

**Comment by z16** [comment]
InfoBar is fixed, OhShi is suffering from an error we're already aware of, so I'm gonna close this issue.
