### ISSUE TITLE
event_outgoing_text(original, modified)

### ISSUE THREAD

**Issue by Podginator** [Windower/Lua#125]
function event_outgoing_text(original, modified)
        write(a)
        modified = '/p hi'
        return modified
end

This only works 6 times, before seemingly stopping the lua script. The only way to get anything to work again is to reload the addon.

I may be doing something stupid, but I've tried it with only that function, and it works 6 times before stopping. If I do not return anything it will work indefinitely, but returning absolutely anything (Original, modified, or anything else) will break it after 6 times.

**Comment by z16** [comment]
I forgot about this issue, but I know why it's happening. `event_outgonig_text` erroneously takes too much off the stack. I'll try to submit a fix for it later today.

**Comment by z16** [comment]
This should be fixed. Report back if it still doesn't work.
