### ISSUE TITLE
[request] gearswap organizer-lib.lua add other items

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1261]
can you add a way to grab other items like nin tools

**Comment by Byrth** [comment]
If you want an immediate work around, this will probably happen if you make a dummy subset of sets and put them in it, like:

```
sets.items={main="Shihei",sub="Echo Drops"}
```

It might even work if you just list the items, idk.

I'll think about how to address this problem in the long run, though. If you're satsified with having them in your satchel, you could just set up a default file for your satchel that includes shihei, echo drops, etc.

**Comment by smd111** [comment]
```
sets.items={main="Shihei",sub="Echo Drops"}
```

---EDIT--
correction that works but it causes an error

12:21:04 > Organizer: Lua runtime error: organizer/items.lua:262:
12:21:04 >   attempt to index field '?' (a nil value)

**Comment by kelhor** [comment]
This should be addressed by the organizer_items functionality.

**Comment by Byrth** [comment]
Given that it has been addressed, I'm going to close this issue.
