### ISSUE TITLE
[gearswap] here is the code needed to get item used from menu

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1271]
@Byrth 

here is the code need to get item data when used from menu

```
require 'luau'
packets = require('packets')

windower.register_event('outgoing chunk', function (id, data, modified, injected, blocked)
    if id == 0x037 then
        local packet = packets.parse('outgoing', data)
        local rez = res.items
        print(packet['Bag'],packet['Slot'])
        local item = windower.ffxi.get_items(packet['Bag'],packet['Slot']).id
        print('item used = '..rez[item].en)
    end
end)
```

**Comment by Byrth** [comment]
You cannot precast item uses with that code, only midcast with a 0.5 second delay (equip commands go out in the next packet). In order to stay consistent I just avoided the whole thing.

**Comment by smd111** [comment]
but it would work for pretarget
and any item usage could then be eliminated from precast and midcast with an aftercast to reset gear

as i see most items that need gear change need it changed before any item is used so as to get the effect and all that would need to be done is to calculate the casting time of all Usable items which the resources already have

i bring this up as far as i know no gear can be changed after an item starts to be used any ways
and even if you could you should never need this because there are no items that have a needed midcast gear change just precast or pretarget

**Comment by Byrth** [comment]
It does not work for pretarget. If a chunk hits the outgoing chunk event then it is already being assembled into a UDP packet and is on its way to SE. If you inject packets then they go into the next UDP packet, mostly arriving after the first. So you can midcast them but not precast.

As you noted, there is little reason to midcast items. Thus, I will not be adding this.
