### ISSUE TITLE
[Request] Target by ID/Index

### ISSUE THREAD

**Issue by Wabafet** [Windower/Lua#1273]
I would like a feature to target an NPC by its ID or index and, if possible, the option to target it with a spell or ability without changing away from the current target, similar to `<st>`.  [Forum post.](http://forums.windower.net/index.php?/topic/817-target-by-id-or-index/)

Thank you

**Comment by Chiaia** [comment]
The closest thing to this for v4 will be the addon SetTarget a847aa3 that uses the incoming assist packet to target by ID. If you're in highly laggy instanced zones such as Ambu or the new Dyna Div it can take a few seconds to target or even fail.

v5 has better ways of targeting built in that don't rely on using packets but would not be easy to add to v4. Arcon looked into it a few years ago. Hence why Arcon made this addon as a work around instead.

As for the option to a ja, ws or cast spell without looking away if you use Gearswap you can do this by giving it the mob.id at the end.
Examples:

/ma "Fire V" mob.id
/ws "Tachi: Fudo" mob.id
/ra mob.id
