### ISSUE TITLE
Feature Request: Reive tracking

### ISSUE THREAD

**Issue by Stromgarde** [Windower/Lua#129]
I would like to see the following things tracked in reives:
a. Reive momentum scores
b. Reive bonuses
c. Bayld awarded

Here are some regex examples, although I'm not 100% certain they'll work outright:

a. Reive momentum score: ([%w%s])%p
b. Momentum bonus: ([%w%s])%p
c. (%w+) obtained (%d+) bayld%p

**Comment by giulianoriccio** [comment]
https://github.com/Windower/Lua/tree/master/addons/reive

Let me know how it works :)
