### ISSUE TITLE
Itemizer / LuaCore - bags.lua / get_bag_info() mismatch

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#1296]
Itemizer appears to rely on get_bag_info() being keyed to the 'english' value from the res.bags table on line 23.

Safe 2 is "Safe 2" in res.bags and "safe2" in get_bag_info(), so that appears to be causing the problems.

**Comment by smd111** [comment]
i saw that as well
"inventory","safe","storage","locker","satchel","sack","case","wardrobe","safe2" -- bags for get_bag_info()
"Inventory","Safe","Storage","Locker","Satchel","Sack","Case","Wardrobe","Safe 2" -- bag names in resources

**Comment by Byrth** [comment]
Fixed per Arcon's instructions.
