### ISSUE TITLE
[Bug](gearswap)

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1324]
GearSwap: Lua runtime error: gearswap/refresh.lua:229: attempt to index field '?' (a nil value)

line 229 is player.race = res.races[player.race][language]
the issue is player.race shows as 100 not 1 as it should
so something is wrong with on of these:
windower.ffxi.get_player()
windower.ffxi.get_mob_by_index(pl.index)

**Comment by kelhor** [comment]
There are problems deeper down; Arcon has said he will look at them when he gets home. If this is still a problem after the needed hook/luacore changes, please re-open it, but it's unlikely to be a problem in gearswap itself.

**Comment by smd111** [comment]
i posted this in case it was unknown but if it still persists(after fix) ill re open

**Comment by KenshiDRK** [comment]
this is probably due to SE adding 4 bytes before distance, so shifting the race offset by 4 bytes
