### ISSUE TITLE
"CRITICAL ERROR: FAILED TO FIND TargetArray" 

### ISSUE THREAD

**Issue by thecuriousorange** [Windower/Lua#1326]
"CRITICAL ERROR: FAILED TO FIND TargetArray" occurs when loading ffxidb, guildwork, blinkmenot, infobar, and timers.
I also had lua errors, but RE a discussion with Iryoku that's down to luacore.
hope this helps^^

**Comment by Byrth** [comment]
Arcon fixed the target struct and rebuilt the plugins, so this is fixed now.
