### ISSUE TITLE
[bug?](gearswap) bag data

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1330]
in gearswap.items this is what i get
all bag max,counts are 0
all bag enabled are false
no items are in the list eather

this is the out put i get when using my gs file
gs c show var gearswap.items
gearswap.items.wardrobe = table: 21AC6338
gearswap.items.max_wardrobe = 0
gearswap.items.enabled_wardrobe = false
gearswap.items.count_wardrobe = 0
---truncated for easy reading
gs c show var gearswap.items.wardrobe
gearswap.items.wardrobe.0 = table: 21AC8FA0
gearswap.items.wardrobe.max = 0
gearswap.items.wardrobe.count = 0
gearswap.items.wardrobe.enabled = false
---truncated for easy reading
gs c show var gearswap.items.wardrobe.0
gearswap.items.wardrobe.0 = nil

the command show var is built in to my gearswap file

how ever thay are all in 
player[bag][itemname]

**Comment by Byrth** [comment]
Yeah, that's the real item array, like from windower.ffxi.get_items()

gearswap.items.wardrobe.0 is indexing the wardrobe table by the string 0 instead of the number 0, so it returns nil. You need to use gearswap.items.wardrobe[0] would be the table for slot 0 of your wardrobe.
