### ISSUE TITLE
Gearswap: not equipping certain equipment

### ISSUE THREAD

**Issue by HadesDougg** [Windower/Lua#1331]
(Think i put this in the wrong place: github.com/Byrth/Lua-Byrth/issues/386)

Certain gear, specifically Falcon Eye and Sapience Orb, aren't getting equipped by Gearswap.

In case this helps, i noticed in windower4/res/items.lua that there's some pieces of data missing compared to other equipment.

**Comment by kelhor** [comment]
Sounds like your resources are out of date. I've got Sapience Orb on line 16766 of mine, and Falcon Eye on 16767.

**Comment by HadesDougg** [comment]
They're on the same lines for me too. My file even has the new items from this June  update so I don't think that's the case.

[edit]
This was also happening when Escha just came out too; all other escha equipment would swap fine the instant I obtained and updated my file, except these two.

[edit2]
By certain pieces of data, I mean within the item details. For example, Sapience orb:
[22252] = {id=22252,en="Sapience Orb",ja="サピエンスオーブ",enl="sapience orb",jal="サピエンスオーブ",flags=63568,stack=1,targets=0,type=4},

But Iron gobbet:
[19782] = {id=19782,en="Iron Gobbet",ja="アイアンゴベット",enl="iron gobbet",jal="アイアンゴベット",category="Weapon",damage=0,delay=999,flags=63572,jobs=8388606,level=99,races=510,skill=0,slots=8,stack=1,targets=0,type=4},

**Comment by HadesDougg** [comment]
Copying the missing pieces from iron gobbet fixed it for me.

Unrelated:
Having gearswap loaded doesn't let me use /item "Cave Cherax" <t> on Zaldon.

**Comment by Byrth** [comment]
Yeah, it looks like Sapience Orb is failing to export basic armor info despite being a type 4 item. I'll open an issue in the windower/pol-utils repository for this and link here.
