### ISSUE TITLE
Attachment  set not saving

### ISSUE THREAD

**Issue by megamanxx00** [Windower/Lua#1336]
Using Autocontrol add-on its not saving the attachment sets. it says it saves but when u log back in and try to pull up equipment set there r none listed

**Comment by nitrous24** [comment]
Do you still have this issue? I don't understand what could possibly be wrong with yours. Last night i logged in for the first time in over a year and autocontrol worked fine for me. I was able to save the set, unload the addon and reload it and the set was still there.

**Comment by nitrous24** [comment]
Going to close this, feel free to reopen and respond, but as i've said it worked fine for me and i can't really troubleshoot something that i can't reproduce.
