### ISSUE TITLE
[DressUp] Character blinks/changes to different model

### ISSUE THREAD

**Issue by mckenzielong** [Windower/Lua#1350]
When using DressUp certain interactions are causing my character to revert back to the original model.  For example, interacting with a homepoint or npc that triggers a cut scene will revert the character back to the original model after a second or two.

Zoning or causing a blink will return you to your desired change.

**Comment by Byrth** [comment]
We believe this has been fixed today (if you re-run launcher). Please reopen the issue or open a new issue if the problem persists.

**Comment by mckenzielong** [comment]
@Byrth I tried the newest update: 4.2.13.5. Still seems to be happening when interacting with blue chests.  Haven't had a chance to try out the mog or homepoints yet.

**Comment by mckenzielong** [comment]
@Byrth Confirmed still broken on homepoints and moogles.  Still blinking back (hook 4.2.13.5.)  DU's  blinking (or stop blinking) feature also doesn't work on those objects.

Can you reopen, or would you prefer a new issue?

**Comment by Byrth** [comment]
I reopened it and will investigate what is going on when I get home. IIRC the packet sent after interacting with homepoints and such is different from the normal packets. It's possible that it changed in some way and wasn't adjusted.

**Comment by mckenzielong** [comment]
@Byrth I see there was some changes pushed recently.  I will verify this is still an issue.

**Comment by mckenzielong** [comment]
Seems to be resolved.  Thanks folks.
