### ISSUE TITLE
[gearswap]player.jobs table cllapsed(in JP client only?)

### ISSUE THREAD

**Issue by amatsuno** [Windower/Lua#1352]
hours ago, I found gearswap failed equipping.
yesterday this is work well.

and i found player.jobs table collapsed
half of job's level are wrong, 
I don't have COR but players.jobs.COR is 1, is this reason?

**Comment by joshk6656** [comment]
Could you do..... and tell which are wrong?

//eval T(windower.ffxi.get_player().jobs):vprint()

**Comment by amatsuno** [comment]
i can't get from this command, //eval T(windower.ffxi.get_player().jobs):vprint()

I wrote in gearswap script

```
jobs = windower.ffxi.get_player().jobs
```

I got below left side. this is wrong and right is collect
jobs={
    BST="99"
    GEO="55"->99(55 is wrong, 99 is correct)
    WHM="99"
    DRG="76"->11(wrong)
    NIN="11"->99(wrong)
    COR="99"->nil?(wrongI don't have COR)
    BLU="1"->99(wrong)
    DRK="99"->21(wrong)
    DNC="99"
    MNK="99"
    RDM="99"
    RNG="99"->50(wrong)
    PUP="99"
    SMN="99"->76(wrong)
    RUN="1"->55(wrong)
    THF="90"->99(wrong)
    WAR="99"
    SCH="99"
    SAM="99"
    BRD="50"->99(wrong)
    PLD="21"->90(wrong)
    BLM="99"
}--end of jobs

**Comment by joshk6656** [comment]
This is fixed, if you close and reopen game it should be good to go.

Thank @z16 

https://github.com/Windower/Issues/commit/d57074fd6a9ca7d27428b65f51baa36a4859f9a7

**Comment by amatsuno** [comment]
restart game, gearswap work well.

THANK YOU!!
