### ISSUE TITLE
(Gearswap) Some abilitys are not being seen by gearswap

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1356]
i can tell you all that gearswap ignores but i do know that
Provoke
is not seen by gearswap in these functions

```
pretarget
precast
midcast --i know some JA's will not show here
aftercast
filtered_action --i know only things that you can not current use should be here
```

i found this by putting

```
print(_global.current_event,"--",spell.name)
```

it prints
function name --  spell name
at the vary top of all my functions

**Comment by Byrth** [comment]
This issue has been solved.
