### ISSUE TITLE
Pointwatch - Incorrect value for current sparks/accolades

### ISSUE THREAD

**Issue by aukon** [Windower/Lua#1373]
sparks.current and accolades.current are displaying 34463 when their actual value is 99999. The cause seems to be packet updates to account for the increased caps. Sparks can be fixed by changing line 113.

Original:
`sparks.current = org:unpack('H',5)`

Fix:
`sparks.current = org:unpack('I',5)`

**Comment by alphaONE2** [comment]
It would be very helpful if you could submit the fix as a pull request. It may be a while before someone else can get around to fixing it.

**Comment by aukon** [comment]
First time creating a pull request, hope I did everything properly!

I added a fix for accolades as well.

**Comment by KenshiDRK** [comment]
The statics.lua should have been changed for the maximum values as well from 50000 to 99999.

**Comment by nitrous24** [comment]
Fixed the statics.lua values as well. I am not sure if dev is able to be merged into live though so can't do that just yet. However, this is fixed so i'm closing this issue.
