### ISSUE TITLE
'gain buff' and 'lose buff' events occasionally fail to see changes in Scholar buffs.

### ISSUE THREAD

**Issue by trv6** [Windower/Lua#1384]
The gain/lose buff events seem to miss Scholar buffs (Light Arts, Dark Arts, Addendum: White, Addendum: Black). I've written the results of one cycle of Light Arts -> AW -> Dark Arts -> AB as reported by the gain/lose buff events. The results, however, were not consistent across cycles (except in that they were inaccurate).

The problem may only affect cases where the Scholar buff is the only buff present.

| Action taken | Previous buffs | Resultant buffs | Gain buff event | Lose buff event |
| --- | --- | --- | --- | --- |
| Light Arts | none | Light Arts | No event | No event |
| Addendum: White | Light Arts | Addendum: White | Light Arts | No event |
| Dark Arts | Addendum: White | Dark Arts | Dark Arts | Light Arts |
| Addendum: Black | Dark Arts | Addendum: Black | No event | No event |

**Comment by trv6** [comment]
Oops, wrong tracker. I can close/reopen this in the correct tracker if it's convenient.

**Comment by z16** [comment]
It's fine here. I'll take a look at it soon.

**Comment by trv6** [comment]
This appears to affect all buffs, not just scholar buffs as I'd originally thought.

**Comment by Nifim** [comment]
This works reliably now.
