### ISSUE TITLE
Scoreboard - Fails to handle "no argument" commands

### ISSUE THREAD

**Issue by chitterchitters** [Windower/Lua#1389]
When attempting to turn scoreboard on in game with //sb , this error is displayed in console:

Scoreboard: Lua runtime error: scoreboard/scoreboard.lua:79: attempt to index local 'command' (a nil value)

(If I've posted this in the wrong place, please let me know)

**Comment by Byrth** [comment]
Well, you did find an error (it should handle a blank command like that), but the actual command to turn scoreboard on is //sb visible

**Comment by chitterchitters** [comment]
haha, right you are, I suppose I'll leave it up for the existing error then. Thank you ~

**Comment by Byrth** [comment]
Okay, changed the title to reflect this. It'll probably be fixed shortly.

**Comment by jerryhebert** [comment]
oops

**Comment by MilkMansKid** [comment]
This should be closed. Fix was merged/pushed over 2 months ago.

**Comment by alphaONE2** [comment]
Indeed, we forgot to close the issue.

@MilkMansKid: In the future, if you include the text "Closes #1389" (obviously, replacing the issue number) in your pull request, GitHub will automatically close the referenced issue when the PR is merged.
