### ISSUE TITLE
GearSwap - Stops working when zoning

### ISSUE THREAD

**Issue by dwebbnet** [Windower/Lua#1396]
Gearswap will stop working when I zone and when fighting. Debugmode tells me nothing on why or where it stoped. Is there away I can see where its stoping?

**Comment by Byrth** [comment]
I'll try to replicate it on my end. Three questions, though:
1) Does it stop responding to //gs commands, like //gs validate?
2) Does it just stop swapping gear?
3) Can you please pastebin your file and link me to it?

**Comment by dwebbnet** [comment]
After it stops working  //gs validate  comes back with   "GearSwap: There is nothing to validate because there is no file loaded."  Its seems its unloading on zone. What file you need me to pastebin?

**Comment by Byrth** [comment]
Huh... So it unloads your player file on zone. I would need you to pastebin your user file. Also, do you play on Windows XP or something?

What job are you when this happens? Also, how long is your name? If your name is 16 characters long, I might know what's wrong.

**Comment by dacrybabysuck** [comment]
I seem to be experiencing the same problem.  With debug messaging on, after a zone a log message of Entering sub_job_change prints.  I'm also experiencing the "there is nothing to validate because there is no file loaded" when using //gs validate.  Anything I can do to help debug, please let me know.

I'm currently testing this on BRD
My character name is 13 characters long
Current running operating system is unfortunately windows 10

**Comment by Byrth** [comment]
Are you zoning out of Monstrosity?

**Comment by dacrybabysuck** [comment]
Negative, it seems like any zone change causes the file to be unloaded.  I've zoned out of the mog house into bastok mines as well as mines to gustaberg and the same thing happens.

**Comment by Byrth** [comment]
The method I'm using to detect job changes on zone appears to be broken for you somehow.

Could you please replace your gearswap.lua file with [this one](https://www.dropbox.com/s/12yu4ayhkaqpdth/gearswap.lua?dl=0), reload the addon, and tell me what it prints to log when you zone? I'll also need to know your current main/sub job

**Comment by dacrybabysuck** [comment]
Current job setup is BRD/WHM.

Output is 10 3 0 0.

**Comment by Byrth** [comment]
Well, we found the problem. Your 0x00A doesn't carry job information in the normal bytes. As for why this is, I'll have to think about it some more.

**Comment by Byrth** [comment]
Okay, are you on a private server?

**Comment by dacrybabysuck** [comment]
I am.

**Comment by Byrth** [comment]
Ta da! Fix the private server code to send job/subjob in those bytes of the 0x00A packet

0x0B4 of should be your main job ID and 0x0B7 should be your sub job ID.

**Comment by dacrybabysuck** [comment]
Thanks!

**Comment by Byrth** [comment]
I am actually going to close this issue now, because this was likely the same problem the original poster had.
