### ISSUE TITLE
Ohshi

### ISSUE THREAD

**Issue by maja6791** [Windower/Lua#1409]
Getting a lua runtime error: addon/libs/texts.lua:554: bad argument #2 to 'set_stroke_color' (number expected, got string).

Weird since it had been working with no errors for the last few weeks.

**Comment by z16** [comment]
For the record, this is a more complicated issue somewhere in the texts library that I cannot quite explain yet. I do have it on the radar, but for now you can fix it locally by manually removing stroke-related settings from the settings XML file.

**Comment by maja6791** [comment]
Thanks for the reply.  I ended up deleting the ohshi folder in the addons folder and re-downloading it.  This resolved the error.  If it happens again, I'll try your suggestion.
