### ISSUE TITLE
GearSwap: `//gs export` should escape single quotations in augment properties

### ISSUE THREAD

**Issue by nekonok** [Windower/Lua#1410]
If a gear has augment property that contains single quote, exported lua file is not valid because single quote is not escaped.
e.g.)

``` lua
sets.exported={
    feet={ name="Plun. Poulaines +1", augments={'Enhances "Assassin's Charge" effect',}},
}
```

this should be:

``` lua
sets.exported={
    feet={ name="Plun. Poulaines +1", augments={'Enhances "Assassin\'s Charge" effect',}},
}
```

**Comment by Byrth** [comment]
Thanks. I'll look into this this weekend. It's honestly kind of amazing this hasn't been reported before.

**Comment by Byrth** [comment]
Fixed it, I think.
