### ISSUE TITLE
Gearswap doesn't equip Apeile Ring or Apeile Ring +1

### ISSUE THREAD

**Issue by Icydeath** [Windower/Lua#1416]
Gearswap does not equip: 
- Apeile Ring
- Apeile Ring +1

_Following testing preformed while on PLD_

Example set (used //gs export equip to get the rings true names..)

sets.midcast.Enmity = {
    left_ring="Apeile Ring",
    right_ring="Apeile Ring +1",
}

Cmd to test it

//gs equip sets.midcast.Enmity

Confirmed they are in the res\items.lua

[27560] = {id=27560,en="Apeile Ring",ja="アペリエリング",enl="apeile ring",jal="アペリエリング",category="Armor",flags=63572,jobs=130,level=99,races=510,slots=24576,stack=1,targets=0,type=5},
[27561] = {id=27561,en="Apeile Ring +1",ja="アペリエリング+1",enl="apeile ring +1",jal="アペリエリング+1",category="Armor",flags=63568,jobs=130,level=99,races=510,slots=24576,stack=1,targets=0,type=5},

**Comment by smd111** [comment]
have you tried equipping them then running //gs export to verify that the name is correct??

**Comment by Icydeath** [comment]
Yes

**Comment by smd111** [comment]
using these commands in this order
//gs equip naked
//gs debug_mode
//gs show_swaps
//gs equip sets.midcast.Enmity

equip naked clears all gear from gearswap's currently equipped gear list
debug_mode might show you the reason
show_swaps shows you what gear its trying to equip
equip sets.midcast.Enmity equips your rings

**Comment by Icydeath** [comment]
Problem solved! '//gs equip naked' reveled the issue. 
Some how the ring slots were disabled >.<; I enabled both slots and it works fine now.

Thank you for your time and helping me figure out the issue.

**Comment by smd111** [comment]
it happens at lest you figured out what was going on
