### ISSUE TITLE
[Request] Add Mounts to Shortcuts

### ISSUE THREAD

**Issue by KenshiDRK** [Windower/Lua#1427]
Could the Mounts be added to the shortcuts addon? I think this will requiere a new resources file for the mounts but Im not sure.

Mounts are in the ability category and use his own command /mount /mo and you need to be a main job of lvl 20 or more.

**Comment by Byrth** [comment]
Could you possibly post the name of a mount and an example command?

For instance:
/mo "Raptor" <me>

**Comment by KenshiDRK** [comment]
yes
/mo "Raptor" <me>
/mo "Chocobo" <me>
/mo "Tiger" <me>

those are the avalaible ones at the moment.

**Comment by Byrth** [comment]
Bah, I wish the names were a little bit less generic. I don't know how the shit we're going to find the resource with such generic names.

**Comment by KenshiDRK** [comment]
ROM/351/83 contains the japanese strings for the help text descriptions of the mounts.
ROM/351/85 contains the english strings for the help text descriptions of the mounts.

ROM/351/84 contains the names of Chocobo, Raptor and Tiger but polutils can't open it to see if it really is the abilities, probably 82 for japanese.

**Comment by z16** [comment]
I added mounts to the resources (mounts.lua). Shortcuts can make use of that. Also added the "mounted" status to resources. This warrants further investigation, the mounts DAT had more than just names in there, possibly useful data. I won't be able to check it out before the weekend though.

**Comment by KenshiDRK** [comment]
It probably contains information similar at the one of other abilities, mounts have a recast of 1min which shares with all the mounts, duration of 30min (will have to test if chocobo duration extension apply to this). Also they have his own icon so, icon_id?

**Comment by z16** [comment]
Possibly, yes, any of those could be in there (or more of them). I'll check it out this weekend, won't have time to do any digging before then. Feel free to have a look yourself in the meantime.

**Comment by z16** [comment]
Actually, I forgot how easy it is to do the digging with RE :) Here's what it produced:

``` lua
    [0] = {id=0,en="Chocobo",ja="マイチョコボ",endesc="Calls forth your personal chocobo.",jadesc="マイチョコボを呼び出す。",moo=86},
    [1] = {id=1,en="Raptor",ja="ラプトル",endesc="Calls forth a raptor.",jadesc="ラプトルを呼び出す。",moo=87},
    [2] = {id=2,en="Tiger",ja="剣虎",endesc="Calls forth a tiger.",jadesc="剣虎を呼び出す。",moo=87},
```

I called the new property "moo". So it's 86 for Chocobo, 87 for the other two. Any idea what it could be? I don't know if it's a coincidence, but the mount status is 85. Ideas?

**Comment by KenshiDRK** [comment]
well the status is 85 for all the mount except chocobo, for chocobo the status is 5 even if you call the chocobo mount, though they could have done 5 and 85 for moo  if its what it mean, so looks weird.

**Comment by KenshiDRK** [comment]
Also it could be the icon id as the raptor and tiger use the same icon and the chocobo one is different, no job abilities use a icon id of 86 and 87

**Comment by z16** [comment]
Sounds like a good guess. Would you mind trying a modified DAT file to see if the icon changes?

**Comment by KenshiDRK** [comment]
sure, indeed I found the icons and its funny cause they added them in the trusts icons dat and also added icons for sp2 abilities which its nice for those ? in timers. And some rare icon called emot_32 which is a happy face lol. If you avoid that happy face the mounts icon are 86 and 87.

The dat is ROM/324/95.dat

**Comment by KenshiDRK** [comment]
Confirmed its the icon id, changing the icons on the dat changed them in the ui

**Comment by Byrth** [comment]
Could you also add prefix="/mount" to those via fixes.xml?

**Comment by z16** [comment]
Can do. Does it also need the `/mo` shortcut?

**Comment by Byrth** [comment]
I don't think we add shortcuts, do we? I'll be adding it to shortcuts, though.

**Comment by z16** [comment]
Guess not! Added it.
