### ISSUE TITLE
Gear Collector - Idea - Export inventories

### ISSUE THREAD

**Issue by Sekuroon** [Windower/Lua#144]
Similar to how spellcast has an /exportgear command, /gc export inventory would export a xml with all of your current inventory, including non-gear items such as nin tools, meds and food.  This would provide an easy and exceptionally fast way to make a gear collector profile for those who don't use spellcast or simply have too much gear in their spellcast to get all of it out at once.

It could group items by type or by how it's sorted.  Perhaps it could even include a export sack or export satchel so you can customize what gear you have in all of your inventories.

**Comment by Ihellmasker** [comment]
This is the lua issues tracker, you need the issues tracker that I linked to you on FFXIAH.
