### ISSUE TITLE
[request gearswap] add the ability to get extdata from player[bag]

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1446]
@Byrth 
can you please add extdata to player[bag]

all that needs to be done is
changing(line:640 of refresh.lua)

```
retarr[res.items[v.id][language]] = {id=v.id, count=v.count, shortname=res.items[v.id][language]:lower()}
```

to(this works)

```
retarr[res.items[v.id][language]] = {id=v.id, count=v.count, extdata=v.extdata, shortname=res.items[v.id][language]:lower()}
```

or(this works as well)

```
                retarr[res.items[v.id][language]] = v
                retarr[res.items[v.id][language]].shortname=res.items[v.id][language]:lower()
```

i cant post a pull request because i already have a pull somewhere else put in

i currently have to do it this way but it takes a lot of time

```
function get_item_next_use(name)--returns time that you can use the named item again
    for _,n in pairs({"inventory","wardrobe","wardrobe2"}) do
        for _,v in pairs(gearswap.items[n]) do
            if type(v) == "table" and v.id ~= 0 and gearswap.res.items[v.id].en == name then
                return gearswap.extdata.decode(v)
            end
        end
    end
end
```

if it was added i could just do this

```
function decode_extdata_of_item(name)
    for _,bag in pairs({"inventory","wardrobe","wardrobe2"}) do
        local item = player[bag][name]
        if item then
            return gearswap.extdata.decode(item)
        end
    end
end
```

i already tested it and it works with out flaws

**Comment by alphaONE2** [comment]
You're supposed to create a new branch for each change you plan to submit a pull request for. This keeps the changes separate and allows you to submit each PR independently.

**Comment by smd111** [comment]
i did but because i have a pull for pointwatch already it wont let me create another branch and if i try to modify gearswap it will go to that pull request

that is until eather that pull is accepted or rejected

**Comment by smd111** [comment]
updated first post with more info

**Comment by smd111** [comment]
created a pull request for this
https://github.com/Windower/Lua/pull/1452
