### ISSUE TITLE
[bug]windower.ffxi.get_key_items() missing mounts

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1457]
windower.ffxi.get_key_items() is missing the mounts key items

```

    local key_items = windower.ffxi.get_key_items()
    for k, v in ipairs(key_items) do
        if (v == 3055 or v == 3072) then
            print("Chocobo")
        elseif v == 3073 then
            print("Raptor")
        elseif v == 3074 then
            print("Tiger")
        elseif v == 3075 then
            print("Crab")
        elseif v == 3076 then
            print("Red crab")
        end
    end
```

the above code will tell you if you got them all

im not sure how windower builds its ki list but in packets/fields it says

```
-- Key Item Log
fields.incoming[0x055] = L{
    -- There are 6 of these packets sent on zone, which likely corresponds to the 6 categories of key items.
    -- FFing these packets between bytes 0x14 and 0x82 gives you access to all (or almost all) key items.
    {ctype='data[0x40]',        label='Key item available', fn=hex},            -- 04
    {ctype='data[0x40]',        label='Key item examined',  fn=hex},            -- 44   Bit field correlating to the previous, 1 if KI has been examined, 0 otherwise
    {ctype='unsigned int',      label='Type'},                                  -- 84   Goes from 0 to 5, determines which KI are being sent
}
```

when there are actually more then 6 (i counted 8 types in the res/ki.lua and 9 in game)

**Comment by alphaONE2** [comment]
The Type field has nothing to do with the categories you see in game. It's more like a bucket index. Each 0x055 packet holds 512 key items, each one stored in 2 bits (the first set if you have the key item, the second set if you've read the key item's description, which makes the dot small). The Type field just tells the client which bucket of 512 key items is in this packet. 6 buckets are enough for key item IDs up to 3,071. Unfortunately the new Mount KIs start at 3,072, which are just out of range. We'll need to add an extra key item bucket to Hook and update LuaCore.

**Comment by smd111** [comment]
ok
well at lest you know what needs to be done

**Comment by smd111** [comment]
im not sure how you coded this in lua core but something like this should make it ware you never have to make any adjustments(un tested)

```
Key_items = t{}
function toBitsTable(num, bits)
    -- returns a table of bits
    local t={} -- will contain the bits
    for b=bits,1,-1 do
        rest=math.fmod(num,2)
        t[b]=rest
        num=(num-rest)/2
    end
    return t
end
windower.register_event('incoming chunk', function(id, data) --builds ki list
    if id == 0x055 then
        local packet = packets.parse('incoming', data)
        local start = (packet['Type'] == 0 and 0 or ((packet['Type'] * 512) -1))
        local mask = toBitsTable(packet['Key item available'], 512)
        for i, v in ipairs(mask) do
            if v == 1 then
                Key_items:append(start+i)
            end
        end
    end
end)
```

**Comment by alphaONE2** [comment]
I looked into this, and I'm not actually sure why you aren't seeing the mounts. Hook currently allocates enough space to track up to 8,192 key items (essentially 16 "buckets"), well over double the number that exist in the game at this time.

**Comment by smd111** [comment]
no one i have talked to do thay show in the ki list
but thay do show up when watching the ki update packet

**Comment by z16** [comment]
We will always have to make adjustments for silly reasons. Anyway, the error is in _LuaCore_ and I fixed it. I'll push it later today or tomorrow, there's something else I might get into this push as well.
