### ISSUE TITLE
[Gearswap] Ambuscade capes augmented with new dye

### ISSUE THREAD

**Issue by Rikimarueye** [Windower/Lua#1468]
It doesn't swap in defined sets nor does it export.

The error line is as follows when attempting to export with said item equiped:

Gearswap: Lua runtime error: Gearswap/export.lua:122 attempt to index local 'item_tab' (a nil value)

**Comment by Byrth** [comment]
Thanks for the report. I will check whether it is still a problem when the servers go back online.

**Comment by Rikimarueye** [comment]
The exporting error was resolved!

In light of the update, those pieces still do not swap.

I hope this helps!

Edit: export functions properly now.

**Comment by Rikimarueye** [comment]
Mistake! All works well! Thanks for giving it your attention!
