### ISSUE TITLE
Gearswap updated for me, but now has trouble returning to idle sets

### ISSUE THREAD

**Issue by EphemeralArcs** [Windower/Lua#1472]
For me and others after the gearswap update last night, when you do actions (like use cdc or use bloodpact ward or rage) it doesn't return to your idle set fully or correctly now. I noticed this while doing NMs in reisen and I was starting to run out of mp, it didn't equip my feet after most pacts or some of my perp accessories and for the other person I asked it doesn't re-equip their idle set legs, and if I one shot an enemy it stays in my pet engaged set unless I do another action.

I found a "fix" but it bypasses some of your coding that you added to fix the rings swapping not working if they have the same name:
If I change line 136 of equip_processing.lua to:  
`if item_tab.status == 0 or item_tab.status ==5 then -- Make sure the item is not already equipped or otherwise in use.`
Then everything works.  My guess is that the item_status doesn't update in time to return to my idle set, as if I hit a bind to handle equipping player gear a second or so later it works.

**Comment by z16** [comment]
Just tagging @Byrth to make sure he gets notified.

**Comment by Byrth** [comment]
This has been changed on -dev, I think.
