### ISSUE TITLE
[BUG/Gearswap] spaming all items in inv when debug mode enabled

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#1474]
gearswap prints all items in the main inventory that do not have a job field in resources like its an error

im using another users post to show whats going on
http://imgur.com/r2Qs2xd

here is the forum post
http://forums.windower.net/index.php?/topic/1137-debugmode-spamming-too-much-text/

i did make sure it was not mine or the others user code first

**Comment by smd111** [comment]
it has to do with the check_wearable(item_id) function in equip_processing.lua

**Comment by Byrth** [comment]
This is actually intended behavior of debug mode, going to close.
