### ISSUE TITLE
Battlemod

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1477]
please update battlemod with the following to show skillchains for umbra and radiance. 

parse_action_packet.lua (line343) add:
(msg_ID > 766 and msg_ID < 771) or
parse_action_packet.lua (between lines 255 256) add:
elseif m.add_effect_message > 766 and m.add_effect_message < 771 then m.simp_add_name = skillchain_arr[m.add_effect_message-752]

and finally in statics.lua (line 27):
skillchain_arr = {'Light:','Darkness:','Gravitation:','Fragmentation:','Distortion:','Fusion:','Compression:','Liquefaction:','Induration:','Reverberation:','Transfixion:','Scission:','Detonation:','Impaction:','Radiance:','Umbra:',}

with these changes mine works perfectly, just wanted public to have it too ^^. thanks

**Comment by Byrth** [comment]
That code wouldn't work for the recovery messages, but I've added it as you meant it and will push it shortly.

**Comment by Byrth** [comment]
Done. It is on -dev.

**Comment by sebyg666** [comment]
exellent thanks. that was speedy.
