### ISSUE TITLE
Auto RA start

### ISSUE THREAD

**Issue by Bingbong77** [Windower/Lua#1478]
CTRL-D no longer binding to AutoRA start.

**Comment by ceresia** [comment]
Can confirm, stop works, but cannot start.

**Comment by Chiaia** [comment]
CRTL D starts and ALT D stops it. If it isn't then your gearswap or something else is binding these same key combo for bind.

**Comment by abbigailmarie** [comment]
Been watching for a fix, but your response is terrible, it doesn't work on my machine like the others reported.  It's a fresh install and nothing else is bound, all it does is move the character to the right and not start.  I can use the command line in console to start it so I've been doing that but something is wrong with the add-on.

**Comment by ceresia** [comment]
Agree, I have not tried the console command but this add-on just doesn't start for me using the binding.  I have tried a bunch of stuff and I gave up.

**Comment by z16** [comment]
I pushed an update to AutoRA, can you let me know if you're still having issues?
