### ISSUE TITLE
[Enhancement] A better way to get current job points

### ISSUE THREAD

**Issue by Isilrhofal** [Windower/Lua#1490]
EDIT: Adjusted code as per @smd111 comment.

Currently I use the incoming chunks to read the job points spent on any character.
Unfortunately this is only transmitted when zoning or chaning jobs, and returns nil if the addon was just loaded.

Could we add something for job points to the library, or is there already something like this?

```
windower.register_event('incoming chunk',function(id,org,modi,is_injected,is_blocked)
    if is_injected then return end
    if (id == 0x63 or id == 0x08D) and org:byte(5) == 5 then
        local offset = windower.ffxi.get_player().main_job_id*6+13
        totaljp = org:unpack('H',offset+4)
    end
end)

```

**Comment by smd111** [comment]
packet 0x08D,0x063 both have job point data

**Comment by Isilrhofal** [comment]
Thank's I wasn't aware. 
When I use packetviewer and run 'pv t i 0x08D 0x063 ' I also see the job points for 0x08D, but same as 0x63 it only shows when zoning or chaning jobs.

**Comment by smd111** [comment]
thay update when you gain merits/CP and use job points as well on 0x063 any ways

**Comment by z16** [comment]
``` lua
windower.ffxi.get_player().job_points
```

This table should contain the current job points for each category, job points spent and current capacity points. Is that what you were after, or is there an issue with this?

**Comment by Isilrhofal** [comment]
Please correct me if I am wrong, but windower.ffxi.get_player().job_points[main_job:lower()]  would return every single job points spent. So in this case I would have to count the job points and return the SUM of it as variable. But it would not return e.g. Total JP: 2100 similar to what the incoming chunk does.

In my example I am checking the total job points for SCH to calculate the correct timer for stratagems usage. So if it is below 550 jp the timer is 48 and above 550 jp it is 33 . (Not considering the merits)

Ideally I would have something which would return 2100 if master etc. (Hope this makes sense)
windower.ffxi.get_player().total_job_points['war']

> 2100

**Comment by smd111** [comment]
it should be
windower.ffxi.get_player().merits --for merits
windower.ffxi.get_player().merit_points --for merit points gained
windower.ffxi.get_player().job_points --for job points gained
windower.ffxi.get_player().spent_job_points --for job points spent
windower.ffxi.get_player().capacity_points --for gained capacity points

**Comment by trv6** [comment]
GearSwap iterates over the table and sums the individual categories as you described: https://github.com/Windower/Lua/blob/030e96f43540685ba12ef90944335a21cb2bdc18/addons/GearSwap/helper_functions.lua#L611-L625

**Comment by Chiaia** [comment]
windower.ffxi.get_player().job_points.**_job_**.jp_spent 
Does exactly what was asked. Just make sure to change "job" to a lowercase 3 letter job abbreviation.
Examples

windower.ffxi.get_player().job_points.mnk.jp_spent
windower.ffxi.get_player().job_points.whm.jp_spent
