### ISSUE TITLE
Synergy

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1491]
i think im missing something, im looking for a way to track the synergy parameters. ie elemental values fed, fewel left, pressure impurities ect. now is this information in memory or am i goin to have to descifer incoming packets for it? and if its all in memory, how can i pull the information? windower.get_mob_by_index() or something?

**Comment by z16** [comment]
If it's in memory there's nothing you can do about it. Packets are the way to go there. You should check out if the info you need is already in our [packet database](https://github.com/Windower/Lua/blob/dev/addons/libs/packets/fields.lua). If it's not, you'll have to gather that info yourself, or search the interwebs if anyone else already did that.

**Comment by sebyg666** [comment]
kk thanks
