### ISSUE TITLE
send_command()

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1493]
my sch uses a lot of send_command() in my gearswap lua + an extra addon to create and send skillchains. I constantly get crashes that boot me from the game and wondering if anyone knows of a way to stop that happening. The funny thing is my brd gearswap lua uses send_command() a lot aswell but doesnt crash, but these are all contained within my gearswap file.
The crashes dont occur all the time and i cant force it either, sometimes it happens in seconds of play on sch sometimes it happens after a couple of hours, but its allways a crash that kicks me from game fully. some of the send_commad() has waits in them and they are appended by a @ as i was told this helps aliviate crashes, heres an example of what crashes me on the extra addon:
```
windower.send_command('input /ja "Immanence" <me>')
windower.send_command('@wait 2;input /ma "'..sp1..'" <t>')
windower.send_command('input /p Opening Schillchain '..skillchain..' - [Magic Burst: '..burst..'] <call21>')
```
i tried putting all 3 into 1 send_command() and tried alot of different things but it always eventually crashes, even if its after a few days of no crashes. its driving me nuts especially when im doin endgame stuff and i back to back crash 3 to 4 times. any help would be appreciated. (i dont think its my geaswap lua because its basicly motentons and considering so many people use it, im sure there would be many people complaining of crashes)

**Comment by smd111** [comment]
```
windower.send_command('input /ja "Immanence";@wait 2;input /ma "'..sp1..'" <t> ;input /p Opening Skillchain '..skillchain..' - [Magic Burst: '..burst..'] ')
```

**Comment by z16** [comment]
I don't know if there's anything you can do about it. We've known about an issue in our ZMQ implementation for a while, but we haven't been able to figure it out. At this point I'd say it's very likely that that's what's crashing you, although I can't say more unless you provide a crash dump.

That said, this is the way to properly write the code (using *Shortcuts*, as you should):
```lua
windower.send_command('immanence')
windower.send_command:schedule(2, sp1)
windower.chat.input:schedule(2, '/p Opening Skillchain ' .. skillchain .. ' - [Magic Burst: ' .. burst.. ']')
```

Depending on where you write it you could use `coroutine.sleep` to simplify it, but you get the gist of it.

**Comment by sebyg666** [comment]
much apreciate the replies, will try the suggestions

**Comment by sebyg666** [comment]
uses that functionallity somehow feels more ... "smooth" i cnt explain it, im still expecting a crash at some point, im just so used to it, but if this even just removes 1 crash out of 10 ill be happy lol

**Comment by alphaONE2** [comment]
It's more smooth because you're not spawning a bunch of threads inside the Windower command handler. You're just using the Addon's scheduler to time things which uses fewer resources and goes through much simpler code paths (the command handler in Windower 4 is overly complicated).

**Comment by sebyg666** [comment]
i have yet to encounter the crash since utilising the code by z16, i consider this fixed and closing
