### ISSUE TITLE
CPU use increase over time

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1498]
can anyone think of a scenario where an addon could make CPU usage increase over time. I've created a couple of personal (very big) addons, I'm not sure if its one of those or some windower published ones like Gearswap how ever on numerous occasions after a few hours of play i find i start to lag like crazy (note i 2 box) and when i check task manager i find that pol is running crazy usage all the way to 40% + (per pol instance, so 80%+ ) instead of my usual 20% ish and when combined with other running proceeses my cpu can hit 100%. I am using a AMD processor and should have known better, its a quad core, but 2 are vertual. Anyway my processor isnt the issue. im racking my brain trying to figure out what could be causing this and the only thing i can think of is loops not being closed propally and everytime the addon containing the loop is reloaded it creates a new one.

Im not a fan of using regeister_event(prerender) as a loop mechanic as most addons only need to loop 2 or 3 times a second, IMHO there is ZERO addon that needs to loop more then that to perform all the calculations they need. But thats not the point. Any would be apreciated with this issue as i end having to completly reboot the game to overcome this issue. i even tried unloading ALL addons and cpu usage barely drops enough.

**Comment by joshk6656** [comment]
could you post or PM one of the addons??

**Comment by sebyg666** [comment]
i can post how i create my loop

windower.register_event('load', function()
	if player ~= nil then
		doloop = true
		loop()
	end
end)

windower.register_event('unload', function()
	doloop = false
end

function loop()
	while doloop do
"loop code inserted here"
		coroutine.sleep(0.35)
	end	
end

i also have libs to generate text boxes for gearswap files that require an external addon to send GS a command to update every 0.35 seconds (which works but i dont like either)

**Comment by smd111** [comment]
what are you trying to accomplish with this loop (what data do you need to grab)
this will determine the best way to do it

**Comment by sebyg666** [comment]
oh god lol where to start, my addon parses the gear u have currently equipped (including augemnts) to generate values for tp/hit return and how much DW you need to equip bassed on haste buffs / gear etc, and then sends a command to GS to equip the correct melee set bassed on these values, it also calculates ACC for main hand offhand RACC etc on the fly so has to grab the base stats packet regularly too (if u toggle this option on). The addon itself works flawlessly, it even checks for haste samba spikes ^^. It checks for job subjob, current merits and job points spent, what blue spells u have equipped etc etc etc. it literraly checks everything.

so in all it performs a hell of a lot of calculations and prerender just does it way too much.

**Comment by smd111** [comment]
why wouldn't you build it in to your gearswap file directly??

**Comment by sebyg666** [comment]
because i dont actually need gearswap to do all this, and i cont even know where i would add it inside gearswap, i tried it as a lib and ran into a lot of issues with it all, so i coded a seperate addon all together that just sends GS the DW value needed to be equipped. done

**Comment by smd111** [comment]
can you post a link to your code so i can check it out??

**Comment by sebyg666** [comment]
anyway what the addon does isnt the issue i was asking if anyone could think of a senario where CPU usage would spiral out of controle, and if its not my loop then the only thing i can think of is that the delay in the loop isnt long enough for it to finish all its calculations before strating again, eventually causing a backlog of functions fireing, is this possible?

**Comment by smd111** [comment]
ok
well either way for anyone to be sure we would need to see your code

**Comment by sebyg666** [comment]
i dont want my code to be public. The addon doesnt do anything naughty, that isnt the reason. its just private. i just wanted to know of possible senarios so i can try and rectify my problem. i cnt think of a way to test for it, as the issue doesnt arrise for hours

**Comment by smd111** [comment]
there are to many to list (about 500+)
with out the code its pointless to speculate
thats why you should always be willing to post your code when asking for help

**Comment by sebyg666** [comment]
how do i PM you, and can i be sure my code will stay private?

**Comment by smd111** [comment]
what is your email

**Comment by sebyg666** [comment]
sebyg666@hotmail.com

**Comment by smd111** [comment]
check your email for chatzy
