### ISSUE TITLE
expose time remainning on buffs

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#1502]
is it possible to pull the time remaining on active buffs from memory? This would help greatly for tracking bard buffs. heres an example

i know how long my buffs should last and what time i cast them, i have 3 ballads on, and one gets dispelled, by knowing how long each buff has left on them and knowing when i cast them i can figure out which one was dispelled.
Im hopping maybe it can be exposed and returned with the windower.get_player().buffs table or something similar.
thanks in advance.

**Comment by smd111** [comment]
the last i checked with ffxi's memory(over 5+ months ago) it was there but it uses a 4 byte time code and im not sure if its the drop or the gain time {except for indi/geo buffs which constantly changes} 

you would have to do alot of calculations to get the correct time

i am however almost certain you could try to find this data in the packets
0x037 -- Player update
0x063(0x09) -- Set Update(buff) {this is probably the one you want to look at as it has bufftime}

how ever you would need to figure it out on your own as i have no clue where to start

**Comment by sebyg666** [comment]
via packet is fine if i can request it when i need it

**Comment by smd111** [comment]
no you would have to keep updating it every time the packet comes in because if you miss it you could lose track of whats going on

**Comment by sebyg666** [comment]
ill check out the oxo63 packet but id still like to have a dev tell me if its possible to have buff duration pulled from memory if its in there, which id imagine it to be. which would be way more helpful then a packet update that will prob only update if u lose / gain a buff.

**Comment by Byrth** [comment]
The packet tells you the timestamp when the buff is going to wear off.

Look at gearswap to see how to extract the time information from it.

**Comment by sebyg666** [comment]
thanks byrth
