### ISSUE TITLE
Battlemod: Error when using job abilities (-dev)

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1506]
When I used Flee in Port San d'Oria, I received an error: "Battlemod: Lua runtime error: battlemod/parse_action_packet.lua:235: attempt to index global 'bit' (a nil value)"

Also happened with Sneak Attack, Trick Attack, and Berserk. 

Error occurs on -dev, haven't had time to test live yet.

**Comment by Byrth** [comment]
Sorry, somehow ended up with a version mismatch between my addon folder and the repository. Fixed.
