### ISSUE TITLE
Gearswap: On login, player.equipment.sub returns nil erroneously until GS is reloaded

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1514]
When I first log in, the line: add_to_chat(154,'EqSub: '..player.equipment.sub) in my PLD.lua produces the error "attempt to concatenate field 'sub' (a nil value)" until //gs reload, after which no error occurs and the line executes successfully. This happens even when my Ochain is equipped at login. Happens on dev or live.

**Comment by Subadai** [comment]
@Byrth tried again without loading a PLD.lua and gs eval print(player.equipment.sub) returned nil until gs reload was done. Rules out Mote-libs or anything in the lua.

**Comment by Selindrile** [comment]
I've noticed something like this, it seems player.equipment.whatever doesn't seem to actively refresh with globals on player gear, only whenever gearswap sends an equip packet does it update, and it's not even always right about that, if the equip fails to say lack of dual wield, or if you change the equipment without using gearswap, it still thinks you have whatever the last gearswap-created equip packet sent was supposed to equip, at least that's my best from what I've observed.

**Comment by smd111** [comment]
its because on your firs login it takes time for ffxi to update all of your info but gearsswap is quiker
which is why i had to delay my gearswap start

**Comment by smd111** [comment]
i have built in to my gearswap code a fix for this
all it does is stop the loading of my include untill it finishes loading ffxi
```
--sence this packet is the one that gives gearswap you current equipment
--this is used to reload your gearswap file
gearswap.parse.i[0x01D] = function (data)
    local cur_equip = table.reassign({},gearswap.items.equipment)
    gearswap.player.equipment = gearswap.make_user_table()
    table.reassign(gearswap.player.equipment,gearswap.to_names_set(cur_equip))
    for i,bag in pairs(gearswap.res.bags) do
        local bag_name = gearswap.to_windower_bag_api(bag.en)
        if gearswap.items[bag_name] then gearswap.player[bag_name] = gearswap.refresh_item_list(gearswap.items[bag_name]) end
    end
    --if gearswap has not been loaded before it reloads your include
    if not loaded then
        loaded = true
        include("this is the path to your file")
    end
end
--stops gearswap from loading of gearsswap files on the first load of ffxi
if not loaded then
    mf = {}
    local lastpacket = windower.packets.last_incoming(0x01D)
    if lastpacket then
        gearswap.parse.i[0x01D](lastpacket)
    end
    return
end
```

**Comment by Nifim** [comment]
This is not a supported usecase for gearswap.
