### ISSUE TITLE
Windows Key prioritizing windows key combinations first even when XI in focus.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Lua#1521]
With the new Windower Dev version, windows key combinations like windows+M for minimize will minimize another screen even when FFXI is in focus, rather than the key combination being intercepted by windower.

If I press the windows key and release it alone, it pops up the windows taskbar if windower is in focus, however if I press say windows+o which is a keybind I have set, then release, it works properly and doesn't ever pop up the windows taskbar.

**Comment by Selindrile** [comment]
Had some issues but after restarting FFXI again, it seems that the windows key is working like it was before the hook change, but the chrome video lag issue is back.

**Comment by Selindrile** [comment]
I'm not sure if these two are related somehow, but the chrome issue is gone again, but the windows key issues are back for me and many of the people who use my gearswaps with a slight difference, basically using the windows key as a ffxi keybind isn't possible for us currently as it just doesn't seem to recognize the key.

**Comment by cairthenn** [comment]
I probably fixed this. Check out hook 4.3.1.0.

**Comment by Selindrile** [comment]
!!!!!! Windows key working on everything, even the normal windows combinations and XI taking precedence again, and no chrome video issues, ty! No issues to report at this time!
