### ISSUE TITLE
Keyboard controlling character movement and control/alt when not in focus.

### ISSUE THREAD

**Issue by Selindrile** [Windower/Lua#1532]
If the chat box is open in game, typing out of focus doesn't do anything.

But if the chatbox is closed wsad move my character, and escape will close the chatbox even if it's out of focus, as well as alt/control pulling up my macros when window is out of focus.

Windows 7, Dev version of Windower, newest update.

And the windows key issues, which were just fixed are back again.

**Comment by Byrth** [comment]
Going to close this because it's on the wrong tracker, but I'll link it.
