### ISSUE TITLE
Gearswap: /item command fails when any lua is loaded

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1542]
Any /item command, e.g. /item "Hatchet" \<t\> on a targeted logging point, fails with no error message when Gearswap is loaded and a job lua is also loaded. If Gearswap is loaded but no corresponding job lua is found, the problem does not occur. Any lua causes the problem, no matter how simple, for example luas like the following will cause the failure:

```
function get_sets()
    sets.precast = {hands="Gendewitha Gages"}
    sets.midcast = {main="Tamaxchi", hands="Bokwus Gloves"}
    sets.aftercast = {main="Bolelabunga", sub="Genbu's Shield", hands="Serpentes Cuffs"}
end
 
function precast(spell)
    equip(sets.precast)
end
 
function midcast(spell)
    equip(sets.midcast)
end
 
function aftercast(spell)
    equip(sets.aftercast)
end
```

The only exception to the problem is using the command to trade crystals to the Ephemeral Moogle in the Mog Garden, which works fine. The problem still occurs with Ephemeral Moogles in guilds. Tested against logging points, harvesting points, and waypoints.

Win10 Creators Update, hook 4.3.1.1

**Comment by Schliematt** [comment]
This has been happening for a while. You cant use the /item "Hatchet" <t> (but with a fish instead of hatchet) to Zaldon to gut them either. There were a few others but the Zaldon one is the only one i can think of off the top of my head.

**Comment by Byrth** [comment]
This is because the game uses two different packets for /item and I can't for the life of me figure out how it decides which to use.

This is where I've been aggregating such reports:
https://github.com/Byrth/Lua-Byrth/issues/352

Going to close this because it's effectively a duplicate.
