### ISSUE TITLE
setkey (via SEND addon) not working when window is NOT in focus.

### ISSUE THREAD

**Issue by Schliematt** [Windower/Lua#1548]
I talked to Radec on bg forums and this doesnt happen to him, but it happens to me. I am updated and on live version (doesnt work on dev either for me so) on Win10 Creators Update.

I am a dual boxer. Setkey works on the window that is in focus. But it does not work if the window is in the background and not in focus. I use setkey home when I zone on both characters so the camera is behind me and i will less likely zone back where i just came from accidently. But more importantly I use numpad7 to stop my mule from following. If i put the mule on follow and then use the SEND addon to setkey numpad7 down and then up, mule keeps following. If i switch afterward over to mule's window though, you suddenly see "follow cancelled." in the chat log. Same with the home key after zoning. ill zone on both characters. The next time i switch to the mule in background (within a short period of time) it will then center the camera behind the character (only after i switch to the mule's window).

To further test this I go to an open area and put mule in first person camera. I put his back to a wall. I switch to my main character and do "//send @others setkey numpad8 down" (this normally moves you forward).
The mule does not move. I switch to the mule's window and he starts running forward. I switch back to the main's window and the mule stops moving. I switch to the mule and he starts running again.

So the setkey from send does work, but only triggers when the background window comes to focus. and stops when not in focus (despite the setkey is still set to down). and reactivates when that window becomes in focus again.

I have tried Always Enable Gamepad on and off and that doesnt change it. So I dunno what the issue is.

**Comment by Byrth** [comment]
Closing this because you already posted again in the right place.
