### ISSUE TITLE
Suggestion: Find/Findall:  Please provide a way to remove one or more character's data

### ISSUE THREAD

**Issue by IBHalliwell** [Windower/Lua#1549]
Hello,

A friend of mine logged into his characters using my workstation (which is what I use as my primary computer for FFXI). Tonight when I went to look for the various crafting kits on my characters, I ended up seeing his 16 characters, too.

It would be wonderful if there was a method to remove those 16 characters, without touching my own.

At a minimum, though, a method (or instructions) to do a complete removal / reset of all character data, too.

Thank you.

P.S.  Someone might want to look at the web page on Windower for Findall (http://wiki.windower.net/doku.php?id=addons:findall) because the URL for support takes you to a GitHub page no longer supported by the author (except to send people here).

**Comment by Byrth** [comment]
If you go to windower/addons/findAll/data, you will see a list of files that are character names. Delete the ones that you don't want.
