### ISSUE TITLE
Gearswap: Swaps don't work when using <focust>

### ISSUE THREAD

**Issue by mazzaccaro** [Windower/Lua#1552]
Gearswap is not swapping sets when using <focust>.

**Comment by Byrth** [comment]
What is \<focust\>?

**Comment by Byrth** [comment]
OK, did some investigation. \<focust\> uses an action on the focus target, which is a a party member designated by the (/focustarget) command. Using the command does not generate packets, but I would guess that it changes the party structure.

GearSwap does not handle actions if it cannot make an action packet for them, which means it needs to determine the action being taken and the target of the action. LuaCore's `windower.ffxi.get_mob_by_target()` function does not currently support \<focust\>. Until it does, GearSwap will not. When it does, the addition to GearSwap will be pretty trivial.

@z16 any thoughts on this? I would guess this target type is just a flag somewhere in the party structure.

**Comment by Byrth** [comment]
It does not change the party structure, but it changes the targets structure. Arcon committed LuaCore changes yesterday that should add it, and I added it to Shortcuts yesterday. When the LuaCore changes go live, it should fix GearSwap. Going to close this now.
