### ISSUE TITLE
New Addons not showing?

### ISSUE THREAD

**Issue by SammehFFXI** [Windower/Lua#1554]
Sorry been a lil while since being here.  Took a side project that has taken my attention for the last month.   I submitted two addons/approved etc.  "DistancePlus" and "JobChange" but I do not see them in the addon list in the windower Main menu.  Was there something else I was supposed to change other than the Addons.xml?  

Thanks,
Sam

**Comment by z16** [comment]
They're currently only on the dev branch, it hasn't been merged to live yet. We're looking to do that soon. Can you confirm that you see them on the dev launcher?

**Comment by SammehFFXI** [comment]
Probably sounds silly - I didn't realize there was a dev launcher :\    Where do I get?

**Comment by z16** [comment]
https://windower.net/ Then under the main download button is a link for the development build:
http://update.windower.net/dev/Windower.exe

That said we just fixed a big issue on the dev branch, so we may merge it live soon.

**Comment by SammehFFXI** [comment]
thanks.  Yes it's there in dev =)
