### ISSUE TITLE
Pet_Midcast v Automaton Ws

### ISSUE THREAD

**Issue by Caradog** [Windower/Lua#1559]
Its looking like it doesn't catch the weaponskill soon enough to effect it

Swaps are taking place but the damage remains baseline upon testing

**Comment by cairthenn** [comment]
This is not possible/reliable. Handle instant pet abilities with your precast or midcast.

**Comment by Caradog** [comment]
Automaton ws aren't triggered by any means that could be detected by player precast or midcast.

Key binding a set and triggering it manually when the automaton reaches near 1000 tp would be the only means then, thanks for your response.
