### ISSUE TITLE
Song timers with Mousai equipment

### ISSUE THREAD

**Issue by funkworkz** [Windower/Lua#1561]
More timers need updated with the latest Mousai equipment. Body is Threnody so doesn't need messed with.

Mousai Turban/+1: ID 25561/25562 - Paeon +1/Paeon +2

Mousai Crackows/+1: ID 25968/25969 - Mambo +1/Mambo +2

Mousai Gages/+1: ID 25988/25989 - Carol +1/Carol +2

Mousai Seraweels/+1: ID 25901/25902 - Minne+1/Minne+2

**Comment by Chiaia** [comment]
Mousai Turban/+1 is for Etudes! You almost got me to add the wrong thing to timers. :P

**Comment by Chiaia** [comment]
Closing this now, I've already added it to my local copy. Will be released in a few hours. Going through open timer issues one by one tonight.
