### ISSUE TITLE
[Gearswap] Certain actions ignore disabling the user file

### ISSUE THREAD

**Issue by Caradog** [Windower/Lua#1574]
As title - certain actions seem to ignore //gs disable

For example, disabling and then summoning an avatar seems to still cause a swap, so pet_change still seems to process

**Comment by Nekseus** [comment]
@z16 this issue is also within triggers.lua

I believe it is missing gearswap_disable calls that would be expected. I

[edit] I must of typo'd gearswap_disable when I searched for it because now I've found it. Not sure of the source of this now.

**Comment by Nekseus** [comment]
@Caradog if you know of any other actions still processing gear during //gs disable please mention them

**Comment by Caradog** [comment]
The only time I've noticed it seems to be on Summoner, would assume it's pet_change causing it - only time I've noticed it

**Comment by Nekseus** [comment]
I found the pet_change issue and sent a pull request

**Comment by Caradog** [comment]
Thanks Nek, gonna close this
