### ISSUE TITLE
Boxdestroyer: Lua runtime errors when opening chests

### ISSUE THREAD

**Issue by Subadai** [Windower/Lua#1575]
Attempting to open a brown chest often results in erroneous suggestions or error messages such as "boxdestroyer: Lua runtime error: boxdestroyer/boxdestroyer.lua:114: bad argument #1 to 'format' (number expected, got nil).

**Comment by KenshiDRK** [comment]
The ID of the messages changed on last update, I'll try to send a pull request later. You can fix it by yourself editing the lua and adding a +1 to every message ID, for example [100] = 8053, to [100] = 8054, and so on for every message.

**Comment by Subadai** [comment]
Thanks!

**Comment by zetaepyon** [comment]
Merged to live in PR #1576
