### ISSUE TITLE
boxdestroyer not working

### ISSUE THREAD

**Issue by cantreadcode** [Windower/Lua#1598]

**Comment by z16** [comment]
Please provide a description of the error.

**Comment by cantreadcode** [comment]
`boxdestroyer: Lua runtime error: ...Windower4/addons/boxdestroyer/boxdestroyer.lua:115: bad argument #1 to 'format' (number expected, got nil)`

**Comment by cairthenn** [comment]
This was related to messages AFAIK and should be resolved.
