### ISSUE TITLE
Dressup Doesn't Change Face

### ISSUE THREAD

**Issue by FunkamusPrime** [Windower/Lua#1600]
I've seen a few other people saying they have this problem too, but have never found a solution.  I have 3 characters on my account.  Two of them can use Dressup without a problem.  However, the third character (my main, unfortunately) cannot change his face.  I can change race and gender without a problem, but //du self face #   does nothing.

When I go into settings.xml, everything looks fine.  For example, under the character's name it does show <face>#</face>, but this has no affect on the character's appearance in game.

I have tried //du self clear, as well as completely uninstalling and reinstalling FFXI, PlayOnline, Windower and Dressup with no success either.

Any assistance is appreciated.  Thanks!

**Comment by cairthenn** [comment]
Can you type  `//list`, `//lua list`, and `//du bmn` and screenshot the results?

**Comment by cairthenn** [comment]
Also, if you create an addon with just this in it and change gear, it will print out the face number it's trying to change you to so I know if that's working. Or if you have eval you can type `eval` in console and copy/paste the following code after that:

```lua
windower.register_event('incoming chunk', function(id,original,modified)
    if id == 0x51 then
       print('Orginal: %d Modified: %d':format(original:byte(5), modified:byte(5)))
    end
end)
```

I believe the addon has to be loaded _after_ DressUp. With `eval`, this should always be the case unless you reload.

**Comment by FunkamusPrime** [comment]
//list and //lua list:  https://imgur.com/a/kNGkv

//du bmn didn't seem to do anything other than display the usual red text in the upper left: https://imgur.com/a/oeECr

Not sure how to create an addon, but I'll work on loading eval and using that now.  Thanks for your help!!

**Comment by FunkamusPrime** [comment]
When I try to paste in the above code with //eval, it truncates it.  Is there a way to get it to accept more characters?  I've tried removing the line breaks and making it as brief as possible, but it's still too long for what the chat window will allow.

Thanks again for your help with this.

**Comment by alphaONE2** [comment]
Create a new folder in your Windower install folder `addons\MyAddon`, create a file in that folder called `MyAddon.lua` paste the code above into it, save, then run `//lua l myaddon`.

**Comment by FunkamusPrime** [comment]
Thanks, AlphaOne2!

I was able to create the addon and when I do //lua l myaddon it reports  Original: 0   Modified:0

So I try //du self face 7  and it still says Original: 0   Modified:0 (including after a reload)

When I go to one of my other characters and try, I get Original: 2  Modified: 7 (after a reload).

**Comment by cairthenn** [comment]
Give it a try. I'm nearly positive it should work now

**Comment by FunkamusPrime** [comment]
I closed, reopened and tried to change the face.  It says: "DressUp: Lua runtime error: DressUp/DressUp.lua:135: attempt to index global 'p' (a nil value)

**Comment by cairthenn** [comment]
My bad :disappointed: Should be good to go~

**Comment by FunkamusPrime** [comment]
Success!  Thanks for your help!
