### ISSUE TITLE
feature request: WS damage filters separate from melee damage 

### ISSUE THREAD

**Issue by temenos7** [Windower/Lua#161]
essentially, being able to filter out others (and your own) melee damage, but not WS damage.

For when you give zero fucks about your party's melee, but want to know the WS damage for SC potential, etc

**Comment by z16** [comment]
I believe this can already be done with Battlemod. It has custom filters for many things.

**Comment by temenos7** [comment]
when I made this request I was actually thinking I was opening a ticket on battlemod's github, only to find out later that it's connected to the main Windower tree here.

Regardless, this is a bad post since it's not on topic to battlemod. I'll ask directly.
