### ISSUE TITLE
[Treasury] Feature Request

### ISSUE THREAD

**Issue by Feary** [Windower/Lua#1612]
Could a Move command and move list (sorted by bag) be added.

example when silk thread are in the inventory i want to be able to move it every time straight to my case.

//tr m a silk thread case
and
//tr move list
item name  ,  bag

thanks.

**Comment by cairthenn** [comment]
You'd probably have to end up disabling it every time you wanted to move the item out of the bag it was moved to, which is very clunky. `Itemizer` provides this functionality by command line, though.

**Comment by Feary** [comment]
wanted it for mog garden and random drops, i just have to use an exec with long list of itemizer commands.

 thank cair
