### ISSUE TITLE
[findAll] Feature Request

### ISSUE THREAD

**Issue by Kanaarei** [Windower/Lua#1618]
Key items in the tracker window possible? 

I've spent a few days playing with this with no success (my LUA skills are horrendous) but would be extremely useful for things like Abyssea popset farming.  The ability to see items in the bags on the tracker is helpful for items which need to be traded, but seeing the key items would make it a bit faster to see whether you have a full popset or not.  This is especially true when multi-boxing.

Thanks for looking!

**Comment by z16** [comment]
It's possible, personally I think though that it would make more sense as a separate addon, as both its functionality and purpose is a quite different to find/findAll. If you're interested in writing something like that you can pop by our [Discord](https://discord.gg/v6pk6uy) and get some help there.

**Comment by Kanaarei** [comment]
Unfortunately I don't have the skill for a full add-on like that which is why I was looking here.  Part of the purpose of the built-in tracker in findAll though is precisely what I'm asking, at least in my opinion.  The tracker is meant to track the quantity of items you have in a bag.  The original readme even calls out items like shihei etc.

It doesn't seem far off to me that tracking a key item might be used for the same purpose, and although I called out Abyssea specifically there's a number of places where that information could be useful.

If I had the talent to write it I would, but sadly my brain is wrapped around Powershell/VB, not LUA.  :(

**Comment by Nifim** [comment]
Third Party addon serving this feature: https://github.com/xurion/ffxi-empy-pop-tracker
