### ISSUE TITLE
Help with Azure Sets

### ISSUE THREAD

**Issue by Mercurian** [Windower/Lua#1621]
So, I want to use RUN/BLU with Azure sets.

Is this possible? If so, how?

**Comment by Selindrile** [comment]
If you want to change spells on the fly, not possible at the moment, you can still use it to gear up with a workaround though, get on Blu/Whatever, and load up your set, then change to Run/Blu.

**Comment by Mercurian** [comment]
Yeah, we modified azuresets to make it work now, so, nevermind, closing the thread.

**Comment by z16** [comment]
Feel free to submit a pull request for the changes you made to AzureSets :)
