### ISSUE TITLE
[Craft] [Bug Report] Client Input lockup w/ "support" subcommand

### ISSUE THREAD

**Issue by deadman80** [Windower/Lua#1622]
1. Turn on the auto-support feature by typing: //craft support
2. Attempt a synthesis using any method.  (I verified w/ main Synthesis Menu, Synthesis History, small sub menu using the crystal, /lastsynth, //craft repeat.. all had same result.
3. Get the "synth failed. crystal lost" msg.  Checking inventory shows crystal not lost.
4. Find that all NPCs now ignore input, client ignores typed commands (like /logout, /shutdown), menu ignores commands (like log out / shutdown).

Using a warp ring at this point made character go invis/transparent, then visual effect ended and nothing else happened.

Was standing almost on top of the clothcraft adv support NPC: Terude-Harude, Windurst Woods, (G-12).

**Comment by z16** [comment]
@Snapsmojo Highlighting you so you're aware of this.

**Comment by Snapster-amb** [comment]
I'll try and carve out some time this weekend to look at this

**Comment by Jinko1** [comment]
This is still an issue, I guess the addon is no longer being worked on ?

**Comment by joshk6656** [comment]
This issue is resolved in the dev branch, will be fixed when someone does dev>live merge.
