### ISSUE TITLE
Freezing when viewing the Chatlog (LS says it's either Highlight or Battlemod?)

### ISSUE THREAD

**Issue by Mortlock-Asura** [Windower/Lua#1632]
I've been having an issue as of late where I will randomly freeze upon opening the Chatlog window.  My LS says that its apparently an issue with Battlemod//Highlighter because of how they alter and change the names of people in Party/Alliance.   This is a problem for me because I actually like Battlemod quite a bit so is there something else that might be causing this?  Or is there a bug somewhere in there that's been surfaced from one of SE's updates?

**Comment by Mercurian** [comment]
This is a common issue with multiboxing, do you do that? There's no fix for that.

Also, highlite can cause it yeah, but never hear of it being an issue with battlemod.

**Comment by cairthenn** [comment]
Sandbox fixes the multiboxing issue with opening of the chat log. It can still happen, but it's very rare, I have seen it fewer than five times in the past 8 years (multiboxing extensively).

**Comment by Mortlock-Asura** [comment]
You say Sandbox? Kk I’ll get ahold of that then

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Mortlock-Asura** [comment]
Do you guys have a link for that?

**Comment by cairthenn** [comment]
It's a plugin in the plugins tab in the windower launcher

**Comment by Mercurian** [comment]
I still crash basically 50% of the time with sandbox, probably due to the number of instances I run though.

Would be safe to assume number of instances increases failure rate?

**Comment by cairthenn** [comment]
You are probably crashing for a different reason than the original multiboxing chatlog crash.

**Comment by Mortlock-Asura** [comment]
Got it, thank you for the help. Ill report if there's any more problems

**Comment by cairthenn** [comment]
Closing since the author's issue seems resolved.
