### ISSUE TITLE
Issue with Gearswap extract and new Ambuscade augments

### ISSUE THREAD

**Issue by Sechs** [Windower/Lua#1637]
Not working with "Parrying" augment in the new 5th slot.
This is the result I'm getting in a cape I have.

```
sets.exported={
    back={ name="Ogma's cape", augments={'HP+60','Eva.+20 /Mag. Eva.+20','Mag. Evasion+10','Enmity+10','System: 1 ID: 1472 Val: 4',}},
}
```

**Comment by cairthenn** [comment]
How does it appear on the cape?

Parrying +5?
Parrying +5%?
Parring rate + 5?

**Comment by Sechs** [comment]
"Parrying rate +5%"
Exactely like I wrote it minus the quotation marks.

**Comment by Sechs** [comment]
Any update on this? Just tried again today but it's still not working, on that specific cape at least.
