### ISSUE TITLE
[Gearswap] Improperly handles /item commands.

### ISSUE THREAD

**Issue by Ivaar** [Windower/Lua#1654]
Gearswap intercepts /item commands and injects the wrong packets under certain situations.

If the item is usable gearswap generates outgoing 0x037, otherwise 0x036 is injected.

The client uses 0x036 exclusively for NPC/objects, trusts and non-charmed pets (any npc you can open a trade window with). While 0x037 is used for players and mobs regardless if the item is actually usable. The only thing the client seems to check was distance, if its equipped and if the item is enchanted equipment.

https://www.ffxiah.com/forum/topic/52302/hatchet-mining-and-logging-cant-use-macro-with-wd/

**Comment by Byrth** [comment]
Are you sure that this is defined by NPC type? I always had a hard time figuring out exactly how to define the difference between the two.

Going to close this issue and consolidate the discussion to here:
https://github.com/Byrth/Lua-Byrth/issues/352
