### ISSUE TITLE
GearSwap issues

### ISSUE THREAD

**Issue by Iminiillusions** [Windower/Lua#1668]
Hello, I've had an issue since about 2 or 3 Windower updates ago where GearSwap equips my WS set when I use certain abilities like Reverse Flourish, Fan Dance, Saber Dance, Unbridled Learning, Warcry, Provoke, Cutting Cards, Flee, and Batatuta. I have spent countless hours beating my head thinking its something with the rules, but seeing how its Motenten's lua's which is what most people use, without issue, and it was working just fine before, I am at a complete loss as to what it could be.
 

Thanks for looking at this.

-Iminiillusions of Asura

**Comment by Iminiillusions** [comment]
here's an example of one of my LUAs that's this happens with. 
[DNC.zip](https://github.com/Windower/Lua/files/2082126/DNC.zip)

**Comment by Byrth** [comment]
I think you might just need to capitalize "engaged" to "Engaged" in your set definitions.

Lua is case sensitive.

**Comment by Iminiillusions** [comment]
My engaged sets aren't  the issue, its ability sets. Would something like
precast need to be capitalized?

**Comment by Byrth** [comment]
Unfortunately I really don't know. This is an issue related to the Motenten lib. He quit years ago and I don't support his files.

**Comment by smd111** [comment]
just doing a quick look over the file you posted
1. you have no sets in init_gear_sets for the JA's you posted about or they are commented out
2. you have no rules in job_precast to do anything or they are commented out

in lua -- or --[[...]] is how you do comments
--comments out a single line
--[[comments out till you use]]

(mind you i know vary little about motes include but) this is what i see

**Comment by zetaepyon** [comment]
Have your lib files been modified in some way? I would try grabbing a clean copy of Mote's libs from:
https://github.com/Windower/Lua/tree/live/addons/GearSwap/libs

I don't see anything particularly wrong in that user file.

@smd111 With the default processing from Mote's libs you usually don't need to include specific rules for every ability, etc., so it's not that strange to see nothing in job_precast(). That function is simply called prior to the default precast() logic built into the library.

**Comment by Iminiillusions** [comment]
@zetaepyon I don't believe they have, but I will go grab a fresh set.
Thanks.


@smd111 from what I understand, Motes has all the rules and stuff in his
predefined includes, as zeta said. I just put stuff in my sets and they
usually work. As I said they haven't worked the past 2 or 3 updates to
windower ago.

**Comment by smd111** [comment]
@zetaepyon 
still of the ja's listed by Iminiillusions only Reverse Flourish and Saber Dance are in his sets and:
Reverse Flourish uses sets.precast.Flourish2['Reverse Flourish']--this might be correct i do not know

`    sets.precast.Flourish2 = {}

    sets.precast.Flourish2['Reverse Flourish'] = {hands="Charis Bangles +1"}`
Saber Dance is commented out so it will not equip any of the gear but it would only work during buff change
`    --sets.buff['Saber Dance'] = {legs="Horos Tights"}`
so all the other ja's posted have no gear to equip

**Comment by Iminiillusions** [comment]
Totally didn't realize that saber dance was commented. Thats my stupidity
showing itself. However that doesn't solve the issue of reverse flourish.
The sets.precast.Flourish2 = {} always throws an error when I put gear in
so I though that wasn't really needed and just there.
I'll try both solutions here in a few

**Comment by smd111** [comment]
@Iminiillusions 
why dont you just use
sets.precast.JA['Reverse Flourish'] = {hands="Charis Bangles +1"}
skip the spell.type info

**Comment by Iminiillusions** [comment]
Was just going on what was already defined as sets. I should just buck up
and do the research to be able to make my own

**Comment by zetaepyon** [comment]
You're not really meant to put gear directly into `sets.precast.Flourish2`, that's a holding table for the specific Flourish II types. It may be a relic from when some timers needed to be created manually, but I'm not sure.

That said, I use this same base Lua for my own DNC, and don't have issues with it.

**Comment by Iminiillusions** [comment]
I will try these possible fixes tonight and send an update if they worked.
Thanks for the suggestions!

**Comment by Skyrant** [comment]
`sets.precast.Flourish2` and `sets.precast.Flourish1` are not standard Motens tables. They are defined in your lua only using `sets.precast.Flourish2 = {}`.

You would need to write some code in job_precast() to equip them.

To assign a set to a specific spell or ability you should always use the basic Motens sets like: `sets.precast['Waltz']` or `sets.midcast['Waltz']`

**Comment by smd111** [comment]
actualy it does but it looks like something is wrong
Mote-Include.lua line 654: cat = (sets.precast[spell.type] and spell.type) or 'JA'
i think it should be: cat = (sets.precast[spell.type] and spell.type or 'JA')
im not sure who made this change but it weird that Mote would make this kind of mistake

**Comment by Chiaia** [comment]
GS user file issue more so then GS having an issue, which is fine.
