### ISSUE TITLE
Craft not loading!

### ISSUE THREAD

**Issue by Autimstar** [Windower/Lua#1670]
Getting this Error Message...
craft: Lua syntax error:  craft/craft.lua:103: '=' expected near ':'

I have tried uninstalling the craft. rebooting, reinstalling! Re down loading it.  Even uninstalled windower and reinstalled! same error message appears!  Craft was working beautifully before the update on the 7th. Very nice little program! Appreciate any help/info. to fix. Thank you!

**Comment by z16** [comment]
I just pushed a fix, try updating and then reload it.

**Comment by Autimstar** [comment]
It worked! Very nice and Thank you for the quick response!  /Smile!
