### ISSUE TITLE
Getting an Invalid number of method arguments when using Tab addon

### ISSUE THREAD

**Issue by Spliffmonkey187** [Windower/Lua#1676]
Hello, i was trying out your Tab addon. It loads fine with no error, but then the windower console will start spitting out the following error once you start pressing Tab:-

`Invalid number of method arguments. Expected 1, got 0.`

Am i doing something wrong and is the Tab working as intended?

I am on an English Client of the game and retail.

**Comment by z16** [comment]
Are you on dev or live?

**Comment by z16** [comment]
Alternatively, if you hover the `Windower.exe` file it will show a version, which version is it? It should be either `4.3.6631.2080` (which would indicate the dev version) or `4.3.6632.29121` (which means you're on our live version).

**Comment by Spliffmonkey187** [comment]
I am on Live , sorry forgot to mention that.

**Comment by Spliffmonkey187** [comment]
And yes i am on 4.3.6632.29121

**Comment by z16** [comment]
I just pushed an update to the live version, the dev version did support Tab, but the live version didn't yet. Now it should.

Out of curiosity, the live version wasn't even supposed to have the addon yet. Did you get it from the launcher, or did you download it manually?

**Comment by Spliffmonkey187** [comment]
Ty for the work Z, I downloaded it manually, sorry i should have added that in my issue report.

**Comment by Spliffmonkey187** [comment]
I will restart my clients and let you know if its working. Give me a minute.

**Comment by Spliffmonkey187** [comment]
OK Z, that update you just pushed out has got it fixed, everything seems to be working as intended. Thanks for the help mate.
