### ISSUE TITLE
BluGuide Not showing categories,

### ISSUE THREAD

**Issue by Autimstar** [Windower/Lua#1691]
Error Msg. 
bluGuide: Lua runtime error: bluguide/masterlist.lua:85: attempt to index field '?' (a nil value)

When Loading Window Console says it loaded successfully, then provides the run error as you  see above this statement.  

Appreciate a way to fix. Very Nice program! Extremely helpful!
Thankyou for your time!

**Comment by Chiaia** [comment]
Whats on live definitely doesn't have this anymore if it ever did and not just a user issue.
