### ISSUE TITLE
Use Item packet (outgoing, 0x037) fields have a duplicate label.

### ISSUE THREAD

**Issue by Tny5989** [Windower/Lua#1693]
There is a duplicate label for the fields of outgoing packet 0x037.

The duplicate label '_unknown2' prevents this packet from being used in some situations.  I was able to change the last occurrence to '_unkown3' and had success.

**Comment by alphaONE2** [comment]
Could you please open a [Pull Request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) for this change, instead?

**Comment by joshk6656** [comment]
I fixed this for you in dev, it should go out in the next live merge, whenever that may be.

https://github.com/Windower/Lua/commit/682c149ab71f98d802c498d6250d5f0e85b62771

**Comment by joshk6656** [comment]
Also merged to live.
