### ISSUE TITLE
GearSwap - SMN Disable Slot Ignored

### ISSUE THREAD

**Issue by Tsezear** [Windower/Lua#1695]
As a SMN with an Avatar summoned, disabled slots in GearSwap are still being utilized by swap commands. "//gs disable" still works as intended and prevents all swaps.

Additional details: The intended slots ARE disabled when I attempt to rest with an avatar out but not when performing other actions such as spell-casting and blood pacts.

**Comment by Chiaia** [comment]
This is 100% a problem with your gearswap file and not a problem with gearswap itself. If you'd like to reopen this please include your gearswap files(s) next time.
