### ISSUE TITLE
requesting addition of player.wardrobe2, player.wardrobe3 and player.wardrobe4

### ISSUE THREAD

**Issue by thecuriousorange** [Windower/Lua#1697]
please add player.wardrobe2, player.wardrobe3, and player.wardrobe4.
player.wardrobe is great, but having the other 3 accessable would be really helpful for me.
thanks^^

**Comment by RubenatorX** [comment]
In the meantime...
```
windower.ffxi.get_items(8) --Wardrobe
windower.ffxi.get_items(10) --Wardrobe2
windower.ffxi.get_items(11) --Wardrobe3
windower.ffxi.get_items(12) --Wardrobe4
```

**Comment by Chiaia** [comment]
I believe this is a gearswap request which was added forever ago. If not please reopen with more details.
