### ISSUE TITLE
Mount muzzle causing ff11 not to shut down

### ISSUE THREAD

**Issue by lewyo** [Windower/Lua#1727]
I have just tracked down this addon (Mount Muzzle) for causing me to have to end task in windows every time i shut ff11 down.

**Comment by Sjshovan** [comment]
Thank you for reporting this. This issue is known and is currently being worked on!

**Comment by z16** [comment]
Does unloading it work? Out of curiosity. If not, you can still `//terminate` inside the game, it's the best way to quit anyway :)

**Comment by lewyo** [comment]
Unloading it does work but i have just turned it off in windower until it gets a fix.

**Comment by Sjshovan** [comment]
It could take quite a while for this fix to make it into Windower. Here is where you can download the latest version without having to wait: https://github.com/Ap0gee/Windower-MountMuzzle

**Comment by dhufford81** [comment]
thank you for tracking this down @lewyo, i was just gettting ready to hunt for the culprit myself when i saw this. thank you for posting the update @Ap0gee  Cheers all!

**Comment by Sjshovan** [comment]
This issue has been solved with the latest version (v0.9.5).
