### ISSUE TITLE
Treasurepool error when lottery passes

### ISSUE THREAD

**Issue by ShoppyCodes** [Windower/Lua#1729]
Getting the following error when a character passes due to Lottery addon.

Treasurepool: Lua runtime error: TreasurePool/TreasurePool.lua:142 attempt to index field '?' (a nil value)

It spams this continuously and very fast until unloaded manually.

Edit for clarity: this is on retail with standard windower updates.

**Comment by KenshiDRK** [comment]
@z16 though a dummy item was added to resources, but checking them there is not. Anyway it shouldn't be a nil value unless resources are outdated (which shouldn't be the case at this time) or a private server with custom items?. why is windower.ffxi.get_items().treasure giving and id that is not in resources?

**Comment by z16** [comment]
I did add it, but removed it again, because it caused a bunch of other issues in multiple addons. ^ What @KenshiDRK said is a good question though, that really shouldn't be the case. Unless it tries to look up item `0`?

**Comment by ShoppyCodes** [comment]
Editing OP as well for clarity; this is on retail and with windower updater doing it normal thing in regards to updating resources. 

I believe the same issue happens during dynamis D, even with one character and without lottery doing anything at all, but I’ve not found a cause for that to be repeatable easily. I’d also have to check the exact error message next time I’m in there.

**Comment by ShoppyCodes** [comment]
Having trouble reproducing this now...

**Comment by ShoppyCodes** [comment]
Reproduced in Dynamis Sandy (standard, not D). Lotting on a Clerics cap.

Character A lots cap.
Character B passes due to lottery.
Character B treasurepool spams the same error as reported until unloaded manually.

Not sure if this info helps but I figure it might.

**Comment by KenshiDRK** [comment]
I have refactored TreasurePool so it uses packets instead of windower.ffxi.get_items().treasure. Could you try it and see if the error is fixed?
https://gist.github.com/KenshiDRK/60b4e8ce7de0527145a3f422f0c196c0

This version is a little different tho, it will keep the same order the normal treasure pool of the game has, except when you load the addon with items on treasure, for this I have to use windower.ffxi.get_items().treasure and I have no way of know what the items order is.

**Comment by ShoppyCodes** [comment]
Using that version now to test. I will post again with an update when I've used it a bit. 

Worth noting that in this version when the treasurepool goes back to empty there is a little background square left on screen.

**Comment by ShoppyCodes** [comment]
After using the version you posted since my last post, I've had no errors at all. Even in this short time-frame I would have expected to have an error with the previous version.

**Comment by KenshiDRK** [comment]
I added a new version, the background square shouldn't show anymore, and this version should fix items position being incorrect sometimes. Also I didn't know windower.ffxi.get_items().treasure had the timestamp of when items drops, so it now should be able to track time and position when the addon is loaded with items on treasure.

What Im worried about using packets is about packet lost, so need to test it in heavy dropping situations, like cp parties.

Link is the same.

**Comment by ShoppyCodes** [comment]
![treasure](https://user-images.githubusercontent.com/26325324/51088962-ffa65900-175d-11e9-914e-d96a03156aa8.PNG)

Not sure how this happened, lots of people were lotting at the same time. Hasn't happened when not many people lot. Not sure if that's the reason or not though. Using the linked version from KenshiDRK.

Edit: Somehow I only just saw your last comment, the above is from the older version you posted. Updating to the new version now to continue testing.

**Comment by ShoppyCodes** [comment]
New version gives error as follows, spams it fast as before and under the same lotting circumstances.

Lua runtime error: treasurepool/treasurepool.lua:134 attempt to compare number with nil

**Comment by KenshiDRK** [comment]
ok, I noticed some errors, updated the link with a new one.

**Comment by ShoppyCodes** [comment]
After some time using this, it seems pretty solid except for a couple things. As you suspected, when a lot of loot enters/exits the pool quickly it loses track and ends up showing more than 10 items (pictured). 

There's also something hard to show in a picture. I can't seem to reproduce on command, it seems a bit random. Two slots will randomly swap back and fourth with each other incredibly quick, so far it's only between two items next to each other. 

![treasurepool bug1](https://user-images.githubusercontent.com/26325324/51710825-34e65d00-2022-11e9-96b8-fc07a62534d9.PNG)

**Comment by KenshiDRK** [comment]
Yep, I did encounter both issues, I have a new version that should have all this fixed. I'll update the link in a min.

**Comment by ShoppyCodes** [comment]
Downloaded from the link just now, I assume it's the new version. Will continue to test.

**Comment by Nifim** [comment]
84ab8e6579bd6e5615cd4e96d7b4981a12970ba0
