### ISSUE TITLE
Equip_processing error

### ISSUE THREAD

**Issue by Kheldar109** [Windower/Lua#1740]
So I as all excited to get my Kaja Katana and try it out, but as soon as I equip it my Whole LUA system breaks to this error. It is only the Kaja Katana and in either weapon slot. I have tried updating the GS files several times. 
"Gearswap: LUA runtime error: Gearswap/equip_processing.lua: 246: attempt to index failed '?' (a nil value)"

The command in reference is

function to_names_set(equipment)
local equip_package = {}

for ind,cur_item in pairs(equipment) do
local name = 'empty'
if type(cur_item) == 'table' and cur_item.slot ~= empty then
if items[to_bag_api(res.bags[cur_item.bag_id].english)][cur_item.slot].id == 0 then return {} end
-- refresh_player() can run after equip packets arrive but before the item array is fully loaded,
-- which results in the id still being the initialization value.
**name = res.items[items[to_bag_api(res.bags[cur_item.bag_id].english)][cur_item.slot].id][language]**
end

if tonumber(ind) and ind >= 0 and ind <= 15 and math.floor(ind) == ind then
equip_package[toslotname(ind)] = name
else
equip_package[tostring(ind)] = name
end
end

return equip_package
end

**Bold is the line in mention**

**Comment by Chiaia** [comment]
It sounds like your resources didn't update for the Feb 8th, 2019 patch. Go to you windower install folder then /res/ delete the files inside of it and extract the contents of this [file](https://www.dropbox.com/s/w1ydi1t85wvlyw6/res%20feb%208th%202019.7z?dl=0) into it. Then restart FFXI if it was running.

**Comment by Kheldar109** [comment]
That fixed it, Thanks a bunch. I tried re installing Gearswap many times to no avail.
