### ISSUE TITLE
Khonsu Grip crashes gearswap/game

### ISSUE THREAD

**Issue by smoothjazz07** [Windower/Lua#1745]
When equipped the game reads a gearswap runtime error then shortly after crashes.

**Comment by Chiaia** [comment]
It sounds like your resources didn't update for the March, 2019 patch. Go to you windower install folder then /res/ delete the files inside of it and extract the contents of this file into it. Then restart FFXI if it was running.
https://www.dropbox.com/s/05hwqec11wwqt3x/march%202019%20resources%20.7z?dl=0

**Comment by smoothjazz07** [comment]
Thank you so much it worked!
