### ISSUE TITLE
Pet bar in xivbar

### ISSUE THREAD

**Issue by Azzaare** [Windower/Lua#1748]
All is in the title, but will it be possible to add an optional pet bar with the same options than for the master in xivbar ?

I can code, but I'm not a lua programmer so I assume someone can do it much faster than I can.

**Comment by Azzaare** [comment]
@SirEdeonX Sorry to refer to you, but you're the last that work on the addon.
 
Bump!

**Comment by Icydeath** [comment]
I borrowed XIVBar and PetTP's code to create a separate addon. It shows/hides just like PetTP does.
[https://github.com/Icydeath/ffxi-xivpetbar-addon](url)
