### ISSUE TITLE
Rhombus spell_aliases.lua format

### ISSUE THREAD

**Issue by SrSenour** [Windower/Lua#1758]
I have been messing around a bit with Rhombus and I am now looking to remap some spell names but I haven't been able to crack the format needed for the spell_aliases.lua.  Can anyone provide any help?

**Comment by trv6** [comment]
It's a map of spell ID to alias, and is only valid for magic.
E.g.
```
return {
    [399] = "Madrigal",
    [400] = "Madrigal II",
}
```

**Comment by SrSenour** [comment]
Perfect!  Thank you very much!
