### ISSUE TITLE
Question: Escaping characters in XML

### ISSUE THREAD

**Issue by tehkrizz** [Windower/Lua#177]
Is there a way to use apostrophes in element tags?

Ex: Vanguard's Crow

**Comment by z16** [comment]
This should be possible natively. Did you close it because you found that it works? If you need such functions, you can load the XML module then do `str:xml_escape()` or `str:xml_unescape()` to return an escaped or unescaped string respectively.

**Comment by tehkrizz** [comment]
I believe I got it to work, but I mainly decided to place the data within the .lua file instead of a xml file. There is practically no reason for a user to edit the data. It also makes things clearer for me since I'm still learning what I'm doing.
