### ISSUE TITLE
LuaSocket support

### ISSUE THREAD

**Issue by giulianoriccio** [Windower/Lua#178]
I was wondering if it would be possible to add the LuaSocket extension to make HTTP requests from Lua addon/scripts

http://w3.impa.br/~diego/software/luasocket/
https://github.com/fire/luasocket

**Comment by jerryhebert** [comment]
LuaSocket currently only works on 5.1 but LuaCore uses 5.2. I read that a few people tried to make it compatible with 5.2 but it ended up buggy. LuaCore may be switching to 5.1 soon though, which would probably pave the way to adding this module.

**Comment by giulianoriccio** [comment]
i don't know if it can help somehow, but i've found this "new" page and the source code under the unstable branch updated with a recent fix for 5.2 compatibility

http://www.luatex.org/svn/tags/beta-0.76.0/source/texk/web2c/luatexdir/luasocket/doc/
https://github.com/diegonehab/luasocket/tree/unstable

**Comment by z16** [comment]
Added.

**Comment by giulianoriccio** [comment]
about time :p

Closed #178 https://github.com/Windower/Lua/issues/178.

—
Reply to this email directly or view it on
GitHubhttps://github.com/Windower/Lua/issues/178#event-125037938
.
