### ISSUE TITLE
Add queue based/flow controlled chat channel message injection

### ISSUE THREAD

**Issue by Brytor** [Windower/Lua#179]
Was asked to repost this as an LUA issue by  IryokuChevalier and adding a little more detail.

Currently if using a windower script or LUA add-on to add something to a chat channel using the console input command if there is not a delay between messages the next messages generate an error.

For example a windower script (no LUA) of:

[code]
input /l P1: ---(PLD) ---(NIN) ---(MNK) ---(COR|MISC) ---(RDM) ---(WHM)
input /l P2: ---(WAR) ---(SAM) ---(DRG) ---(DRK) ---(COR) ---(WHM)
input /l P3: ---(BLM) ---(BLM) ---(BLU) ---(SCH|BLU) ---(RNG) ---(BRD)
[/code]

Will  result in:
![chat-error](https://f.cloud.github.com/assets/4118024/397975/f5f34016-a84c-11e2-9c04-bbe638bcc4ef.PNG)

With only the first line being actually accepted

In scripts this can be worked around by adding a wait between each line. However, as more LUA add-ons are being added I am seeing issues where one or more add-ons may try to feed chat at the same time (or at the same time as a script) resulting in multiple errors.

For another example using the following LUA code:

```
function event_incoming_text(original, modified, color)
    local stagger, sPos, sUser    = string.find(original,'(.+)\'s attack devastates the fiend!')
    local low,     lPos, lTrigger = string.find(original,'The fiend appears vulnerable to (.+)!')
    local high,    hPos, hTrigger = string.find(original,'The fiend appears highly vulnerable to (.+)!')
    local extriem, ePos, eTrigger = string.find(original,'The fiend appears extremely vulnerable to (.+)!')
    if stagger == 1 then
        send_command('input /p ' ..sUser.. ' -> Stagger !!')
    elseif low == 1 then
        send_command('input /p ' ..lTrigger.. ' 1 !')
    elseif high == 1 then
        send_command('input /p ' ..hTrigger.. ' 3 !!! ')
    elseif extriem == 1 then
        send_command('input /p ' ..eTrigger.. ' 5 !!!!!')
     end
end
```

Will result in errors if multiple events occur close together. (2x staggers, stagger & hint, etc.) and messages being lost.

Adding a way to inject chat into chat channels (party, tell, linkshell) that has flow control and was a shared queue between all LUA add-ons, Windower script, and manually entered console commands could solve this issue.

The delay between messages may need to be configurable since it appears based on computer and lag that the delay needed may vary from 0.5 to 3 seconds.

For example if there is a single queue for chat the different add-ons, windower scripts and the existing (or new script input command) would inject their messages onto a queue while a monitor thread could poll the queue and pull off in order placed on and sleep for the configured delay between polls of the queue. Since you would need to synchronize and lock on the queue when modifying there may be slight contention issues but this would be thread and multi input source safe .

One side effect is messages can be delayed if multiples are queued at same time ao developers using this feature would need to be aware of it if time sensitive.

Optional this feature could be used generically for all input commands in case multiple add-ons may be trying to send both chat input and other input (spells, etc.) at same time.

**Comment by giulianoriccio** [comment]
if 3 addons tried to input text at the same time into my party chat preventing me from inputting my own text because they are in queue, that would be an issue.
i think such a function should be user controlled.
from what i understand, in your example you are trying to send the vulnerability into the party chat every time you get the message. wouldn't that get spammy if you get the same messages 3 times after using 3 ws sequentially? at the same time you "risk" to send a vulnerability that maybe someone else has already notified.

**Comment by z16** [comment]
This is currently not possible to do in Lua, as there is no sleep function. If it gets added to the Lua API, I will add a function that does that, but as Giuliano said, that is not always desirable. Imo no addon should be automatically outputting global chat, but that's just my opinion. Like I said, if this gets added to the API, I will implement a function that does that, but I'd still suggested restricted usage (and preferably avoid it completely).

**Comment by Brytor** [comment]
Yes, it can get spammy and you can build in checks for repeated messages.   The purpose of the two examples (windower script and lua) was to show how the problem of losing items you want to go to the log can be shown and why/how such a feature could solve it.   I wound fully expect it to be user controlled by calling the specific function as just automatically spamming to chat is a red flag to people you are using something not native to FFXI.
