### ISSUE TITLE
AutoRA Error upon load

### ISSUE THREAD

**Issue by Clairefox** [Windower/Lua#180]
I have the addon set to "on" in the windower startup, but when I log in fully, it's not loaded. This happens when I try to manually load it. Not sure what to do >_<;

![luaerror](https://f.cloud.github.com/assets/4085925/399799/584ee7ce-a87f-11e2-9114-61a92c8f0182.png)

**Comment by z16** [comment]
Looks like you have an outdated version of the code. Try to update by restarting the launcher. If that doesn't work, download [this file](https://raw.github.com/Windower/Lua/master/addons/AutoRA/AutoRA.lua) and save it in your Windower/addons/AutoRA folder.
