### ISSUE TITLE
Gearswap: midcast equipping before precast triggers?

### ISSUE THREAD

**Issue by tehfailsafe** [Windower/Lua#1807]
Setting up a FC set, noticed I wasn't seeing a reduction in the recast times of spells. Removed mote includes and made a super simple basic example that will not work. Is there anything wrong here?

```
function get_sets()
    sets.idle =  {
        legs = "Carmine Cuisses +1",
        body = "Jhakri Robe +2",
        right_ring = "Warp Ring",
    }
    
    sets.precast = {
        legs = "Carmine Cuisses +1",
        left_ear = "Enchntr. Earring +1",
        right_ear = "Loquac. Earring",
        hands = "Leyline gloves",
        body = "Hashishin Mintan",
        right_ring = "Jhakri Ring",
        left_ring = "Prolix Ring",
        waist = "Witful belt",
        back = {name = "Rosmerta's Cape", augments = {'"Fast Cast"+10', 'Phys. dmg. taken-10%', }},
    }
    
    sets.midcast = {
        head = "Jhakri Coronal +1",
        body = "Jhakri Robe +2",
        hands = "Jhakri Cuffs +1",
        waist = "Eschan Stone",
        legs = "Jhakri slops +1",
        feet = "Jhakri Pigaches +1",
        left_ear = "Sortiarius Earring",
        right_ear = "Friomisi Earring",
        neck = "Atzintli Necklace",
        left_ring = "Shiva Ring",
        right_ring = "Jhakri Ring",
        back = {name = "Rosmerta's Cape", augments = {'INT+16', 'Magic Damage +6', '"Mag.Atk.Bns."+10', }},
    }
end



function precast(spell)
    equip(sets.precast)
end

function midcast(spell)
    equip(sets.midcast)
end

function aftercast(spell)
    equip(sets.idle)
end

```

If I comment out `equip(sets.midcast)` I do see the correct recast reduction (and cast speed, of course).  I turned on debugging and I do see the correct gear being swapped in the `------ precast -----` and `----------- midcast ------------` blocks. 

Does there need to be a longer delay before midcast equip?

**Comment by Nifim** [comment]
Recast is calculated as the spell goes off. 

Precast will define your casting time, Midcast will define your recast time.

**Comment by RubenatorX** [comment]
Precast sets by design do not affect recast. Only fastcast(+ etc) in your midcast does.

**Comment by tehfailsafe** [comment]
whoa. So I wasted hours. Hah! 
What is the best way then of testing the FC gear is actually affecting spell cast time? I don't have enough FC at the moment it seems to see a noticeable difference in longer casts.

**Comment by Nifim** [comment]
I use a spell that take a long time to cast, like stoneskin or reraise. Then you can either observer the time based on the time stamp ingame(second resolution) or print the time when you equip your precast and then print the time when you equip your aftercast

**Comment by RubenatorX** [comment]
Well, this is not off topic from your issue. I'd recommend you come chat with us in the windower discord #general https://discord.gg/v6pk6uy
But to answer your question, if you test with a spell that has a longer cast time (i dunno, like stoneskin) you'll see the effect more prominently because its percentage based
