### ISSUE TITLE
Battlemod Feature Request

### ISSUE THREAD

**Issue by Headtatt** [Windower/Lua#1825]
Currently there is no way to differentiate MY avatar damage from OTHER avatar damage.

In a party with several Ramuh (for example) being able to set "other's pets" to an easier to ignore color and "my pet" to a easier to see color I could see in the chat box how I was performing.

Right now all Ramuh's appear the same and so I cannot tell my (epic) voltstrike from some other guy's (less epic) voltstrike as it moves by in chat.

I hope you can help, and that it is as easy a change as I think (and hope) it is.

**Comment by Nifim** [comment]
This has been implemented already, you can use the setting `showownernames` to get the owner of a pet's name attached to the action performed by the pet. The setting is false by default. #1696
![showownernames](https://user-images.githubusercontent.com/4059879/73225458-9784a400-4121-11ea-9944-9ca6f6031770.png)

**Comment by Headtatt** [comment]
Thank you so much!  Didn't even realize that was an option, even looking at the code. Worth adding a note in the readme?

**Comment by Nifim** [comment]
Indeed, I will update readme
