### ISSUE TITLE
[Autocontrol] settings.xml Gets Wiped On Syntax Error

### ISSUE THREAD

**Issue by Gojito** [Windower/Lua#1857]
If you attempt to reload autocontrol after editing the settings.xml file, the XML will be wiped and replaced with what looks to be a template settings file.

I think we can just allow the addon to fail loading gracefully for that error.

**Comment by RubenatorX** [comment]
FYI this is the default behavior of all settings files that use the config library.
For this reason, when possible it is best to use the settings commands for the addon:
https://docs.windower.net/addons/autocontrol

**Comment by Gojito** [comment]
Found a workaround if you have the file open when you reload the addon. You can undo the changes by hitting Undo on your text editor. Just pointing out I was using Sublime since I'm not sure if this depends on the text editor being used.
