### ISSUE TITLE
[Shortcuts] Curing Waltz Breaks Under Level-Cap

### ISSUE THREAD

**Issue by Gojito** [Windower/Lua#1874]
Did an Assault mission with COR/DNC and was not able to use /curingwaltz nor was I able to use it via the Ability menu in-game.

/curingwaltz would attempt Curing Waltz III which wouldnt be available at COR70/DNC35
Using the menu option would also cause the same thing to happen even when explicitly choosing CW2.

**Comment by RubenatorX** [comment]
I can't replicate your issue.
`/curingwaltz` for me does curing waltz 1
Make sure you don't have a custom shortcut in your settings file for
`<curingwaltz>Curing Waltz III</curingwaltz>`
Also make sure its not your gearswap (or another addon) causing this behavior or something.
(you can use `//lua unload all` and `//lua load shortcuts` and `/curingwaltz` and see what happens)

**Comment by Gojito** [comment]
It turned out to be my gearswap logic. >.<
