### ISSUE TITLE
Dimmer doesn't use ring unless it's already equipped

### ISSUE THREAD

**Issue by ticktickMOF** [Windower/Lua#1884]
as the title says, dimmer just equips the ring the first time you input the command.  the code looks like it's supposed to wait until it's ready and then use it.

**Comment by RubenatorX** [comment]
Dimmer does the following:
1) checks for all 3 dimensional rings in equippable inventory
2) one by one in a preset order it checks for any of them being off cooldown
3) equips the ring
4) waits for the ring's potential "post-equip 8 second wait timer" (waiting a maximum of 10 seconds)
5) uses the item

It is possible for other addons or gearswap libraries or scripts to interfere with the process. For example using Selindrile's library it is possible for it to unequip the ring before the wait timer to expire.
(Selindrile has its own special command to get around this situation)

Would need more details about your specific setup and what's happening.

**Comment by ticktickMOF** [comment]
![img_20200607_152457](https://user-images.githubusercontent.com/15878714/83978131-638d6c80-a8d3-11ea-8158-119d9c7f1bf4.png)

the ring wasn't un-equipped

**Comment by RubenatorX** [comment]
the "21" appears to indicate that the ring is not off cooldown or something
Are you on retail server? Its acting like the equip cooldown is longer than 8 seconds

**Comment by lili-ffxi** [comment]
This happens when the system clock is off from ffxi server clock by too much.

Both MyHome and Dimmer give up using the ring if the cooldown is higher than 10 seconds (normally, the cooldown of the ring is 8s). @ticktickMOF looks like your system clock is off from ffxi's clock by at least 13s! Try synchronizing your system clock with internet clock in windows' settings, it should fix the issue.

**Comment by ticktickMOF** [comment]
that worked! thanks

**Comment by z16** [comment]
If you restarted Windower, it may have also been fixed by the code changes @lili-ffxi made to tolerate higher time discrepancies :D But still good to hear that it is fixed.
