### ISSUE TITLE
DressUp off by one

### ISSUE THREAD

**Issue by n1n384ll** [Windower/Lua#1888]
faces map is off by one; typical index issue. should start at 0. 

update static_variables.lua with this:

_faces = {}
_faces["1a"] = 0
_faces["1b"] = 1
_faces["2a"] = 2
_faces["2b"] = 3
_faces["3a"] = 4
_faces["3b"] = 5
_faces["4a"] = 6
_faces["4b"] = 7
_faces["5a"] = 8
_faces["5b"] = 9
_faces["6a"] = 10
_faces["6b"] = 11
_faces["7a"] = 12
_faces["7b"] = 13
_faces["8a"] = 14
_faces["8b"] = 15
_faces["Fomor"] = 29
_faces["Mannequin"] = 30

**Comment by Chiaia** [comment]
Verified and just pushed a fix to Dev.
