### ISSUE TITLE
findall no longer working

### ISSUE THREAD

**Issue by fationt** [Windower/Lua#1898]
I was using findall just fine until one day FFXI crashed and Windower was completely gone from my computer. unsure what caused this. any ideas on fixing it?

**Comment by z16** [comment]
This sounds very unrelated to anything Windower. The best way I can explain it is if an anti-virus program deleted it, although it wouldn't delete it "completely", but not quite sure what you mean by that. How is Findall related to this?

**Comment by Chiaia** [comment]
Closing it's 1.5 years old with no follow up and sounds like it was AV related.
