### ISSUE TITLE
Lua - Basic Calculator using 3 operator

### ISSUE THREAD

**Issue by ashishsme14** [Windower/Lua#1920]
We had given below task

Create three function using Lua which can perform addition, subtraction and multiplication/

The program should be

Accept any number.
Check the operator + - *. If not the print "Invalid operand" and exit.
Accept two operands. if any operand not number print "Invalid operand" and exit. use - tonumber()
Perform the operation and print result.

We had written code as below which not working as expected , not sure where we went wrong, please guide us
```

local operators = {
    ["+"] = function(x,y) return x+y end,
    ["-"] = function(x,y) return x-y end,
    ["*"] = function(x,y) return x*y end
}

local function default()
    print "Invalid operand"
end

local num1 = io.read()
local num2 = io.read()
local operator = io.read()

local func (
 if operator == "+" then
   local add = tonumber(num1) + tonumber(num2)   
 end 
 if operator == "-" then
   local subtract = tonumber(num1) - tonumber(num2)
 end
 if operator == "*" then
   local multiply = tonumber(num1) * tonumber(num2)
 end
)
or default
print(func(num1,num2))

io.read()
```

**Comment by Nifim** [comment]
This repository is for windower Lua addons used to enhance the game play of final fantasy XI. 

Your question appears to be a general Lua question, you might want to seek help on a Q&A site like StackOverflow.
