### ISSUE TITLE
[Craft] - missing Lightning Emblem Card & ID in main file

### ISSUE THREAD

**Issue by Vamperica** [Windower/Lua#1925]
In the section with all the Emblem cards and IDs defined, you are missing Lightning Card.  I added it to mine, but seems to revert due to update push?

**Comment by joshk6656** [comment]
There is a pending pull request to update the recipes.lua file to include all new recipes since this was released. I have also added the missing lightning card to that pull request.

You can view it here.
https://github.com/Windower/Lua/pull/1924
