### ISSUE TITLE
GearSwap incorrectly reporting double weather when -storm buffs are active.

### ISSUE THREAD

**Issue by lili-ffxi** [Windower/Lua#1926]
Gearswap will report double weather intensity if a tier 1 -storm buff is active while the same natural weather is occurring.
This is incorrect, as -storm buffs overwrite natural weather in all cases, and do not stack.

Cfr: https://www.bg-wiki.com/bg/Category:Storm
> Storm spells override environmental weather effects on the buffed individual. For example, personal Aurorastorm will override a Dynamis double dark weather. As such, these enhancements are not additive to environmental effects.

and

> If it is Ice weather, you can cast Hailstorm on yourself and wear Hachirin-no-Obi, you will only benefit from single weather effect for a constant +10% damage.

The error is in [lines 470-472 of gearswap\refresh.lua](https://github.com/Windower/Lua/blob/dev/addons/GearSwap/refresh.lua#L470).

As that code is from 2015, I might be missing some other uses for it, so I'll only submit a PR if it's confirmed there's no other logic behind it, and it is indeed a bug.

**Comment by alphaONE2** [comment]
After a quick search, I can see that that function is only called in two places, and it's an internal function that isn't exposed anywhere else. It should be safe to fix.

**Comment by lili-ffxi** [comment]
Sent a PR, so I'm closing this issue. Thanks for checking!
