### ISSUE TITLE
launcher

### ISSUE THREAD

**Issue by gilles007-** [Windower/Lua#194]
with so many updates for the past 3-4 days, my ffxi, which was running fine, now experiments freezing, BSOD, controller problem
only using 8 plugins, no addons
back in normal days, i could have rollback some dll
now i can't
please add an option to accept or refuse updates
or better, make an archive folder somewhere (windower\archives)
is it possible to make a ninja edit to host file, so i can block this for the moment ?
(update.windower.net     127.0.0.1          ????)
thanks

**Comment by Ihellmasker** [comment]
This is the lua issues tracker, not the windower issues tracker.

What plugins are you using? The updates recently have only been to timers and not a single update there would cause you to BSOD, or touch the controller. None of the updates have caused this. It must be something else on your system.

You can not disable auto-updating and no, it will not be made an option.

The point of the updating system is so everyone is always on the latest version so we don't have trouble like we did with the old windower with people never updating and causing a world of problems.

Please repost this in the correct place answering the question above.
