### ISSUE TITLE
blist not working

### ISSUE THREAD

**Issue by Latravant** [Windower/Lua#1948]
i came back after a 6 month break, updated everything, and started to use //blist to add bots, and it doesnt block them. i checked the list and it shows their names but i still see theyre shouts filling up my window

**Comment by Latravant** [comment]
[blist.txt](https://github.com/Windower/Lua/files/5361531/blist.txt)

**Comment by RubenatorX** [comment]
What does `//bl status` say for you?

**Comment by Latravant** [comment]
sorry couldnt find this page XD
all options say on and muted color 57

**Comment by RubenatorX** [comment]
ok and when you do `//bl list` it shows the bots names that you are seeing messages from?

**Comment by Latravant** [comment]
yes

**Comment by Latravant** [comment]
also i tried both blist add (filled out all of the parameters) and blist qa and neither worked
