### ISSUE TITLE
Battlemod - Sirens damage is not displaying as my damage

### ISSUE THREAD

**Issue by Meezeri** [Windower/Lua#1961]
Hello,

I just noticed that Siren is my only Avatar that seems to not recognize as my damage when it comes to colors and filters. 

I have my damage set as Purple and all the other avatars show as purple except Siren.

**Comment by KenshiDRK** [comment]
Are you speaking about normal hits or bp? it does works for me. Are you on private server or retail?

**Comment by Meezeri** [comment]
I'm on retail, I can send some screenshots later. It's the BP and attacks
from Siren.

**Comment by Meezeri** [comment]
[
![Ifrit Damage](https://user-images.githubusercontent.com/74452355/99315599-bc184c80-2817-11eb-82d4-4421f306cd4d.PNG)
![Siren Damage](https://user-images.githubusercontent.com/74452355/99315609-bfabd380-2817-11eb-97c6-37b35d3f89eb.PNG)
![Colors Settings](https://user-images.githubusercontent.com/74452355/99315615-c20e2d80-2817-11eb-97dd-5b6c13d0d87c.PNG)


](url)

**Comment by KenshiDRK** [comment]
Hysteric assault is a drain effect so thats why it doesn't show the same, others dmg bps and normal hits should work

**Comment by Meezeri** [comment]
Is there a way I can make it look the same?

**Comment by KenshiDRK** [comment]
not in an easy way

**Comment by Byrth** [comment]
Looks like this was addressed, so I'm going to close it.
