### ISSUE TITLE
Battlemod - Pet Magic Bursts Not Showing

### ISSUE THREAD

**Issue by PBeJune** [Windower/Lua#1962]
Hi - I've noticed when I Magic Burst with my BST jug pets that the damage is not captured in the log no matter what my filters are set to. I attempted to go default and customize the filters, nothing seems to work. When I unload Battlemod, the normal FFXI chat window is able to pick it up. 

Thank you,

**Comment by KenshiDRK** [comment]
Found the issue I'll fix soon.
