### ISSUE TITLE
FINDALL

### ISSUE THREAD

**Issue by Solen18** [Windower/Lua#1988]
Find all does not work, when you click on support it takes you to his purchase history from 2013. I think its time to take it down, unless someone can tell me how to use this thing.

**Comment by RubenatorX** [comment]
It does work. `//find warp ring`
What commands are you doing and what makes you think its not working? When you do the command how does it behave? Does nothing happen? Does it print an error?
Also feel free to come chat with us in #support in discord (link at the top of http://windower.net)

**Comment by Nifim** [comment]
Closing due to no response
