### ISSUE TITLE
MobCompass conflict with MacroChanger

### ISSUE THREAD

**Issue by banggugyangu** [Windower/Lua#199]
Addon MobCompass was written to use same command structure as MacroChanger.  This could potentially cause issues for anyone using both addons simultaneously.

**Comment by z16** [comment]
I wouldn't really call it an issue, there's always the longer version of the commands. If someone actually uses both, they can make a different alias for one of the two. We won't be able to prevent this, everyone can commit addons, and after a while it will get rather huge, and FFXI having so many commands, chances are that some will overwrite others. That's up to people to set up how they want imo. Closing for now, I'll let the author know though, maybe he'll feel differently about it.
