### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by Latravant** [Windower/Lua#2017]
I'm using the clock addon and i dont know what happened but the clock is offscreen somehow. is there anyway to edit the lua to move it back on screen?

**Comment by RubenatorX** [comment]
Edit the settings file `windower\addons\Clock\data\settings.xml` and change the position fields to 0 and then save the file and `//lua reload clock`
![image](https://user-images.githubusercontent.com/5944121/113602864-6bf02a00-9600-11eb-96aa-a6763b9e9fc0.png)

**Comment by Latravant** [comment]
tyvm
