### ISSUE TITLE
equipviewer game data command

### ISSUE THREAD

**Issue by shastaxc** [Windower/Lua#2023]
I love the new features you've added to equipviewer (ammo count, encumbrance, etc). However, one small complaint is that it took me a bit to get it running due to my FFXI install directory. It is not inside the PlayOnline folder, but instead my "SquareEnix/FINAL FANTASY XI" folder is a peer to it. I saw that there was a command `ev game_date path` to redefine this. However, typing that in game stripped out all the forward slashes so I had to go into the settings.xml to edit it and add them back in.

I tried going straight to the settings in the first place to update settings like the game path and position but it looks like the default values aren't stored in settings.xml like most addons do, so I didn't know what syntax to use until after running the command in game. It's a minor thing, but just unnecessary complication.

**Comment by lili-ffxi** [comment]
> It's a minor thing, but just unnecessary complication.

Agreed. The next iteration of equipviewer will be able to detect FFXI's folder on its own, but in order to do that, a modification to windower itself was necessary. This modification has been written, it's currently being tested, and will soon be deployed.

**Comment by shastaxc** [comment]
One other sorta related issue: I set everything up in the settings for equipviewer on one character (mainly game_path and position) then when I loaded the addon on my 2nd character, it moved my character specific settings for the first character to <global> and completely erased the game_path setting so I had to run the command again, and then go back into the settings.xml again and re-add the forward slashes.

**Comment by RubenatorX** [comment]
The settings lib is buggy when multiboxing. The best way I've found to get around the bugs is, when first setting up really any addon for multiple characters, first unload the addon for all characters. Then load it on one character. Change settings. Then unload it, and load it on a different character. Once all the settings are the way you like, then you can load it on all characters.

**Comment by RubenatorX** [comment]
Also, afaik it shouldn't be stripping any forward slashes.
![image](https://user-images.githubusercontent.com/5944121/115117396-94aae480-9f5b-11eb-87dc-9fe1ec5a4d95.png)
But if you used backslashes `\` then the command parser uses those as an escape character so you'd have to double them up like this in a command
`this\\is\\a\\test` and there's nothing the addon can do about fixing that.

**Comment by RubenatorX** [comment]
But yes, we have a fix in the works to make it more reliably find the game path in the first place. Will go out in the next week because it modifies windower core so additional testing required to make sure the change doesn't break other stuff.

**Comment by Chiaia** [comment]
This feature was added. #a6f4394d940f0c171bf03da8d77d651981a26c9f
