### ISSUE TITLE
Rolltracker gearswap integration

### ISSUE THREAD

**Issue by shastaxc** [Windower/Lua#2028]
Can we get some integration between rolltracker and gearswap like what gearinfo does, so we can collect info about current rolls and their potencies?

**Comment by RubenatorX** [comment]
No don't think so. If for no other reason than its not possible to accurately know the potency of rolls done by corsairs other than yourself because you can't know what gear they were or weren't wearing for each roll.

**Comment by shastaxc** [comment]
I think it's reasonable to simply pass the result of the roll (1 thru 11) and let the user decide what to do about phantom roll gear assumptions.

**Comment by RubenatorX** [comment]
You can already do this in gearswap by including code in your lua that watches for the packets/events that report roll values, and recording those values in a table/variable.

**Comment by RubenatorX** [comment]
Something like:
```lua
local rollNumbers = T{}
windower.raw_register_event('action', function(act)
    if act.category == 6 and table.any(act.targets, function(targ) return targ.id == player.id end) then
        local rollName = gearswap.res.job_abilities[act.param].english
        if rollName:endswith('Roll') then
            local rollID = act.param
            local rollNumber = act.targets[1].actions[1].param
            rollNumbers[rollID] = rollNumber
            rollNumbers[rollName] = rollNumber
        end
    end
end)
```
