### ISSUE TITLE
numbers and debug_EAM showing in console

### ISSUE THREAD

**Issue by drunkenstyle** [Windower/Lua#203]
Not sure where this is coming from, but when I check a monster I get this in console : 
13 3 1

When dead I receive this in console : 
debug_EAM#97: ${target} was defeated by ${actor}.

Is there anyway to shut off those messages from appearing?

**Comment by z16** [comment]
There have been a few changes in libraries. Can you update and confirm that the error is still occurring?

**Comment by drunkenstyle** [comment]
Let me restart windower and see if I get the same error.

**Comment by z16** [comment]
Unfortunately, that does not guarantee an update of your files. The launcher is currently buggy, so if you could instead download [this](https://github.com/Windower/Lua/archive/master.zip) and extract the `libs` files to the `Windower/addons/libs` folder, then you'd have all the most recent files. You can do the same for other addons in there, but make sure not to overwrite your various `settings.xml`s.

**Comment by drunkenstyle** [comment]
The numbers 9 1 1 are showing up when pressing alt + c to check the mob.
Going to die real quick and see if the debug message shows up.
The debug message also shows up.
debug_EAM#97: ${target} was defeated by ${actor}.
Will download file and try again.

**Comment by z16** [comment]
Nevermind, this is a Battlemod debug message. Open Windower/addons/battlemod/battlemod.lua and at the very beginning, change the following line:

``` lua
        debugging = true
```

to

``` lua
        debugging = false
```
