### ISSUE TITLE
Autocontrol doesn't equip head, frame or attachments

### ISSUE THREAD

**Issue by jasonc-87** [Windower/Lua#2067]
It seems like most of the functionality works for autocontrol except actually equipping pup gear.  There are a ton of people on my private server I play on interested in the ability to be able to swap pup automation sets out with commands instead of manually equipping every piece.  I have tried to add longer waits inside of the coroutine.schedule(set_attachments_from_autoset:prepare function thinking maybe the packets aren't working but haven't had any luck. In theory you would be able to at least equip some of the automations gear but none of it works.  You can save your sets and all the other stuff works fine but I just want to be able to change my automation set without manually doing it each time, don't really care about burden tracker or anything.  I've debugged this and it gets the attachment names , ids, etc fine.  It's almost like windower.ffxi.set_attachment(att.id) just doesn't work to set attachments.  Is there another command I can try?  Lastly I have tried just using the default settings.xml on the most current version in the repo and that doesn't work either so please don't ask for my xml file, everything is exactly like the 2.0.4 version(most current and my version) in the repo.  Thanks!

**Comment by jasonc-87** [comment]
@Nifim Nothing, just closed? =[

**Comment by z16** [comment]
It has been fixed. We sometimes forget that people here are not part of our Discord server, where we discuss these things. It may take a while for the fix to go live.

**Comment by jasonc-87** [comment]
Oh awesome news! That will make our whole server happy I'm sure.  I was looking for a pull request for it. What was the issue if you don't mind me asking?  Thanks all!

**Comment by z16** [comment]
We were sending a packet of the wrong length. The retail servers tolerated it, but private servers did not.

**Comment by jasonc-87** [comment]
I gotcha, thanks guys 😄
