### ISSUE TITLE
plugin_manager: Crashes game logging in and out

### ISSUE THREAD

**Issue by Shylo-Musgrove** [Windower/Lua#2075]
This addon caused me to crash multiple times going from one mule to another.

I logged out of main and logged into mule1.  Logged out of mule1 and logged into mule2. Immediately crashed once the load bar was complete. I relogged Playonline and at character selection screen I selected mule2. I couldn't login as it said same character was already logged in. I logged in and out of mule1. Mule2 was still busy. I logged into mule3. Immediately crashed once the load bar was complete. This entire process happened 2 more times.

I asked myself why was this happening as it has never happened since 2005. The only change I made was I started using this addon. I turned the addon off, relogged Playonline, and the issue went away. I still had a mule that was "already logged in" so I was able to replicate exactly what had happened to me 4 previous times.

**Side Note:** The "Report a bug" link in Windower directs us to an archived repository (Byrth). These need to be updated with links to actual working repositories.

**Comment by Nifim** [comment]
Thanks for the report, a few questions:
1. What other addons do you have loaded?
2. What addons do you have plugin_manager loading?
3. Are you retail or private server? 
    I assume retail based on some of your comments but just need to make sure.
4. Does it only happen when going from `mule1` to another mule? 
    You mentioned login and out of `mule1` both times before crashing on the next login attempt.
5. What are the names of your mules?

**Comment by RubenatorX** [comment]
Hi :)

First, want to feel free and to invite you to discuss this with us live on discord #support (link found at top of windower.net)
We would probably like to see your settings.xml for the addon.

The addon itself does not actually do very much so, I suspect either there's something up in the settings file and/or one of the things its trying to load is causing a crash, but we may have to have a look. You can upload it here and/or we can chat about it in discord.

Also note that the "already logged in" error really does not have anything to do with windower directly, (unless you have loaded some sort of addon/mod that is directly interfering with the login process). But we can discuss that further in discord if you like. Repeated attempts at logging in on an "already logged in" character can delay the process of the game letting the character log out as well so, sometimes you need to be patient.

There is also a situation that happens sometimes in which your character login can get stuck for a while (in our experience, up to 24 hours) but we have discovered that logging in from a different ip address tends to resolve that problem, (or waiting a day if that's not possible). Again though, to our knowledge that is a vanilla game problem unrelated to windower.

**Comment by Shylo-Musgrove** [comment]
I am more than willing to jump in discord to help work the issue. I will tag both of you referencing issue 2075.

**Comment by Shylo-Musgrove** [comment]
Issue resolved. Removed addons being automatically loaded via Windower and the crashing stopped.

My suggestion to the Devs would be to update the Readme file to be more clear. The plugin_manager addon should be used for addons and/or plugins that are **_NOT_** being automatically loaded via Windower or the init.txt file. Hind sight this seems obvious to me but that is not how I initially understood it to work.
