### ISSUE TITLE
invtracker broken with latest (10/10/2021) update

### ISSUE THREAD

**Issue by xianthe** [Windower/Lua#2086]
The invtracker addon is no longer tracking bags (just gear) after the latest release.
![image](https://user-images.githubusercontent.com/279276/136900024-ff4886a4-27c9-45f7-9421-3b4aa9ea8fb1.png)

**Comment by RubenatorX** [comment]
Cause of this issue is the same as this one
https://github.com/Windower/Issues/issues/1080

**Comment by xianthe** [comment]
Thanks for the update.

**Comment by Nifim** [comment]
Resolved, See Windower/Issues#1080 for more details
