### ISSUE TITLE
Using findAll in Japanese does not work after October 10th update

### ISSUE THREAD

**Issue by kens002** [Windower/Lua#2089]
From the October 10th update, some key items can no longer be searched using findAll in Japanese.

Ex) 
   I have 歪んだトンベリの王冠 and don't have 潤んだアーリマンの目.
   And "//findall 潤んだアーリマンの目" returns "XXXX/key tems: 潤んだアーリマンの目" (I don't have it).

  Windower/res/key_items.lua shoud have like:
    [1466] = {id=1466,en="mucid Ahriman eyeball",ja="潤んだアーリマンの目",category="Abyssea"},
    [1467] = {id=1467,en="twisted Tonberry crown",ja="歪んだトンベリの王冠",category="Abyssea"},
  But now;
    [1466] = {id=1466,en="mucid Ahriman eyeball",ja="砕けたウィヴルの角",category="Abyssea"},
    [1467] = {id=1467,en="twisted Tonberry crown",ja="潤んだアーリマンの目",category="Abyssea"},
    [1468] = {id=1468,en="veinous hecteyes eyelid",ja="歪んだトンベリの王冠",category="Abyssea"},

Due to FFXI's own update, the order of English and Japanese strings is out of sync and Resource Extractor is unable to generate the correct lua and xml files.

I've made a proposed fix for Program.cs, Please see the comment I left at [Oct 10th 2021 Update](https://github.com/Windower/Resources/commit/2b37f5876196e02d24307fbc1e7f7b3756c90d1d)

**Comment by RubenatorX** [comment]
Hi. Are you saying that the dat file in the Japanese version update doesn't contain those problems?
Because otherwise, all the items would simply display wrong in game otherwise. Or are you saying that there has been an update to the dats since we did a pull and we should pull again?
Or are you saying that they are offset now in the dats (for whatever reason) and the japanese client is handling the offset properly?
We definitely noticed that all the japanese strings were off but, we were waiting on SE to fix it.

**Comment by kens002** [comment]
Sorry, I am not English native and I must misunderstand the problem. I don't know the item in the EN version and/or JA version has the problem to display wrong item. I also didn't realized SE means the company :-)
I got it. I also wait for the fix by SE.

I just realized that If I got "潤んだアーリマンの目" in Abesea aria, I can see the key item in key item list in the game.
I was not sure if this is bug or specification change. I just realized that both EN list and JA list has its own id , and synced by the id, generated list (key_items.lua) is like the one checked in previous the update.

**Comment by RubenatorX** [comment]
Sorry, not sure I understand:
Did your key item menu show the proper/correct key item name for the key item you got? Or did it show the incorrect one?

**Comment by kens002** [comment]
I was making Verethragna. I'm not sure right now, but I think triggers for Chloris, Ulhuadshi, Dragua and some of the key items in Abyssea - Tahrongi was displayed correctly.

**Comment by RubenatorX** [comment]
Those aren't in the messed up KIs though
(you can see the changes here in the key_items section: <https://github.com/Windower/Resources/commit/2b37f5876196e02d24307fbc1e7f7b3756c90d1d#diff-44bb611238f70e73ddb4752b20cd3e8d702454b830623eecedbb41cba4375c3e>)
Anyway, If you have finished voidwatch, you can check if it says you have `六芒星の紅色のジェイドIII` instead of `六芒星の紅色のジェイドIV`

**Comment by kens002** [comment]
Thank you for your time.
I found Crimson Stratum Abyssite IV in the list:
![image](https://user-images.githubusercontent.com/92364243/140393571-95d2f704-a863-4c81-b27b-77e4e9960c5d.png)

**Comment by RubenatorX** [comment]
Turns out you were right!
We should have a fix in the coming days. (soonish)

**Comment by kens002** [comment]
If I'm not misunderstanding, I hope my source (Program.cs) attached to [Oct 10th 2021 Update](https://github.com/Windower/Resources/commit/2b37f5876196e02d24307fbc1e7f7b3756c90d1d#commitcomment-58791155) helps.

**Comment by kens002** [comment]
Most of the strings in key_items have been fixed at [November 10th, 2021 Update](https://github.com/Windower/Resources/commit/5221659af20011195ae4491ff563b8f20b840ab0), but the following strings do not match in the English and Japanese versions.

    [2300] = {id=2300,en="craggy fin",ja="頑強な幹",category="Temporary Key Items"},
    [2301] = {id=2301,en="flame-scarred skull",ja="凍てついた鋭牙",category="Temporary Key Items"},

    [2532] = {id=2532,en="sparking tail feather",ja="瑞々しい尖角",category="Temporary Key Items"},
    [2533] = {id=2533,en="piece of inviolable bark",ja="灼熱の頭骨",category="Temporary Key Items"},
    [2534] = {id=2534,en="frosted incisor",ja="雷光の尾羽根",category="Temporary Key Items"},

These shoud be following

    [2300] = {id=2300,en="craggy fin",ja="瑞々しい尖角",category="Temporary Key Items"},
    [2301] = {id=2301,en="flame-scarred skull",ja="灼熱の頭骨",category="Temporary Key Items"},

    [2532] = {id=2532,en="sparking tail feather",ja="雷光の尾羽根",category="Temporary Key Items"},
    [2533] = {id=2533,en="piece of inviolable bark",ja="頑強な幹",category="Temporary Key Items"},
    [2534] = {id=2534,en="frosted incisor",ja="凍てついた鋭牙",category="Temporary Key Items"},

These strings have been wrong since before the [Oct 10th 2021 Update](https://github.com/Windower/Resources/commit/2b37f5876196e02d24307fbc1e7f7b3756c90d1d), and it seems that the order of strings in the English version and the Japanese version in FFXI itself have been partially different for some time.
Using the code attached to the Oct 10th 2021 Update, I have confirmed that the output lua file is correct when we match the id of the English and Japanese strings.
These are only 5 items and should probably be fixed by SE in the first place. So I will leave it up to you to decide if you want to fix them in Windower or not.

**Comment by Chiaia** [comment]
Thank you for letting us know I was just going to check. We'll fix it manually since SE missed them.

**Comment by kens002** [comment]
Thank you for supporting the Japanese version as well as the English version.
I took a look at the oldest key_items.lua that I could find, [Update for v5 and clean up](https://github.com/Windower/Resources/commit/1219a21c15f1013d6338c368aac0639ca5501cca#diff-44bb611238f70e73ddb4752b20cd3e8d702454b830623eecedbb41cba4375c3e), and these 5 strings are already wrong.
I don't know if it's a SE error or a specification that the order of the id's is different in some places between English and Japanese, but it seems unlikely that SE will fix this. It would be a pain to fix it manually every time (sorry if I'm wrong).

**Comment by Chiaia** [comment]
Mind sending me the new .cpp file or pastebin, or gist? SO I don't need to
type up your images?

**Comment by kens002** [comment]
This is my first time using pastebin. How about this?
[source1](https://paste.centos.org/view/raw/8fbaf4e3)
[source2](https://paste.centos.org/view/raw/c84730f4)
[Program.cs](https://paste.centos.org/view/raw/a1646835)

**Comment by Chiaia** [comment]
Could you re-post those, I guess they expired. Sorry I had forgot about this till just now.

Oh dang that site only allows up to 24 hours could you use like https://www.pastebin.com and set it to 1 week, it jumps from 24 hours to 1 week.

**Comment by kens002** [comment]
Please see the link below.

[source1](https://pastebin.com/FUEqmCVx)
[source2](https://pastebin.com/5FFZ1UWL)
[Program.cs](https://pastebin.com/QGpyBHqM)

**Comment by Chiaia** [comment]
Thank you very much and I've updated the resources.
