### ISSUE TITLE
findall: Lua runtime error

### ISSUE THREAD

**Issue by Knumskull83** [Windower/Lua#2124]
after they added the new wardrobes Findall gives up a lua runtime error![bild](https://user-images.githubusercontent.com/3845922/153361484-7b847cd2-baab-4ac7-a3b1-35bab3de0142.png)

**Comment by Darkway1** [comment]
same problem

**Comment by Byrth** [comment]
These are all actually caused by problems in the plugin API, so I'm going to let this ticket stand in as the one true ticket for all these errors:
https://github.com/Windower/Issues/issues/1085
