### ISSUE TITLE
Gearswap Runtime error : Gearswap/packet-parsing.lua

### ISSUE THREAD

**Issue by Darkway1** [Windower/Lua#2125]
![Screenshot-4](https://user-images.githubusercontent.com/1635608/153369012-2814362e-9b06-42be-a50b-f951837303ca.png)

there is error with gearswap after the update

**Comment by z16** [comment]
Just upload the image directly, do not use third party hosters, especially not such shady ones. I fixed it for you. Closing this issue as there are a lot of things that broke and we are working on them, this is very likely just a related break.
