### ISSUE TITLE
Gearswap error

### ISSUE THREAD

**Issue by Darkway1** [Windower/Lua#2126]
Runtime error: Gearswap/packet_parsing.lua:165 attempt to index field 

getting this error when moving gear to new inventory

![Screenshot_5](https://user-images.githubusercontent.com/99390895/153370490-20445adb-0c8f-47ab-85ca-b8aa017855be.png)

**Comment by z16** [comment]
Please don't open new issues for GearSwap and item processing. These all have the same cause and they're being worked on.
