### ISSUE TITLE
Bad argument #1 to 'ipairs' (table expected, got nil)

### ISSUE THREAD

**Issue by ahenry30** [Windower/Lua#2131]
<img width="1025" alt="findall error" src="https://user-images.githubusercontent.com/54108454/153406006-d59e5b11-adfd-44e7-8644-f364f8b6af37.png">

Started getting this error message, not sure if there was a recent update in windower that is causing it.  I tried deleting the folder and redownloading the plugin through windower to no avail.

The image has a small snippet of the source code where the error occured

Also I play on the private server Eden

**Comment by RubenatorX** [comment]
The retail game updated to add additional wardrobes so inventory stuff is moved around. We are working on it.
Same cause as #2124

**Comment by Byrth** [comment]
Closed as duplicate
