### ISSUE TITLE
windower.ffxi.get_mob_by_target() or  by_name or by_id returning incorrect values in table

### ISSUE THREAD

**Issue by PeachBlossomWine** [Windower/Lua#2136]
Various fields in these functions returning incorrect info.  Found at least these fields:

in_alliance, in_party, target_index,

might be more.

**Comment by Byrth** [comment]
They changed the monster structure. When we release a new Hook/LuaCore this will be fixed.

**Comment by RandomCanadian12** [comment]
After new hook/luacore update, I have an issue pulling up shield size from ID. Any ideas?

res.items[item_name_to_id(player.equipment.sub)].shield_size

**nvm, I see KateFFXI has a fork where this issue was fixed/futureproofed. Thanks Kate! I dont know this stuff well enough to fix myself.

**Comment by z16** [comment]
The original issue should be fixed. Reopen this issue if you're still experiencing problems.
