### ISSUE TITLE
FindAll

### ISSUE THREAD

**Issue by tommycostello** [Windower/Lua#2137]
findall: Lua runtime error: findall/findall.lua: 418: bad argument #1 to 'ipairs' (table expected, got nil)

Assuming this is related to the mog wardrobe changes.

**Comment by Jerukhalri** [comment]
It appears that @tommycostello might be right. Lua will load FindAll without any problems when making the transition from PlayOnline Viewer into the game, but that's where the normalcy ends. GearSwap is also having issues now, so I would venture to say that any addon that pulls data regarding FFXI storage may not work.

**Comment by Byrth** [comment]
These should be resolved on the dev branch now. Probably by end of night it will make it to live.

**Comment by Byrth** [comment]
Also, going to close this because it was a plugin issue and this is the Lua repository.
