### ISSUE TITLE
Skillchains - Battlemod

### ISSUE THREAD

**Issue by drunkenstyle** [Windower/Lua#214]
When using battlemod and doing a skillchain, this error continues to pop up : 
\addons\battlemod\event_action.lua:302: attempt to call global "t" {a nill value)

**Comment by giulianoriccio** [comment]
try opening the file and replacing on line 302 `if t{152,161,162,163,167,229,603,652}` with `if T{152,161,162,163,167,229,603,652}` until it gets fixed

**Comment by drunkenstyle** [comment]
thank you
