### ISSUE TITLE
item_name_to_id not working with weapons in wardrobes 5-8

### ISSUE THREAD

**Issue by jrhoward81** [Windower/Lua#2144]
A lot of GearSwap functions (mostly precast.WS and lockstyle) are returning errors when weapons are in Wardrobes 5 through 8. The common thread for the errors seems to be this line of code:

res.items[item_name_to_id(player.equipment.main)].skill

Works fine when weapons are in inventory or Wardrobes 1 through 4.

Thanks for all your work after the update!

**Comment by zetaepyon** [comment]
item_name_to_id is not a gearswap function, it is part of Selindrile's library.
For assistance, see the associated Discord: https://discord.gg/ug6xtvQ

**Comment by jrhoward81** [comment]
> item_name_to_id is not a gearswap function, it is part of Selindrile's library. For assistance, see the associated Discord: https://discord.gg/ug6xtvQ

I see it now, thanks
