### ISSUE TITLE
Infobar

### ISSUE THREAD

**Issue by tspawn35** [Windower/Lua#2147]
infobar addon stopped working with the update. It just shows the monster name and nothing else.

**Comment by RubenatorX** [comment]
Either your Windower is not up to date, or you're playing on a private server.
If you're on a private server then you must either complain at your hosts to get the server updated for the new retail packets, or you must revert your `windower\addons\libs\packets\fields.lua` to an older version for use with older packet formats.

**Comment by tspawn35** [comment]
I uninstalled and than downloaded the installer from the website for windower and am def not playing on a private server. Still not working. Oh well it's not that important.

**Comment by KenshiDRK** [comment]
by default it only shows the name, you have to edit the settings file to add variables, the readme has all the variables you can use.

**Comment by tspawn35** [comment]
Thanks, That fixed it.
