### ISSUE TITLE
Gearswap's //gs validate no longer finds items in wardrobes 3+

### ISSUE THREAD

**Issue by johnarnfield** [Windower/Lua#2159]
This line, recently merged looks particularly suspicious, and when I reverted it, and reinstated the `find_in_equippable_inventories` function, it fixed the issue for me.

https://github.com/Windower/Lua/commit/c636840c9d80a6118c812697eb3ad8cc248be653#diff-5c03235efc85228818c55f7de3f9c33a6061395792459799284fa95e3acf5245R238

~~@Sechs Are you able to confirm if this is just my possibly modified version of GS causing issues?~~ Affecting multiple users

**Comment by RubenatorX** [comment]
Fix is on development (unstable) build for testing now, and will go live soon
#2160

**Comment by johnarnfield** [comment]
Thanks @RubenatorX. Working perfectly now.
