### ISSUE TITLE
temps only works part time

### ISSUE THREAD

**Issue by Latravant** [Windower/Lua#2171]
when i use temps in escha on my 6 characters, it usually only works on 2-3 characters and the others it just gets stuck. like it shows the command, than nothing. or sometimes it opens the menu, then nothing.

**Comment by RubenatorX** [comment]
This is due to the way packets are handled. You have to wait between doing the command between characters. You can come to discord and try out the `delayedall` addon to have it delay the commands for you. But doing it on all characters at the same time is the problem
