### ISSUE TITLE
disable slot no longer works

### ISSUE THREAD

**Issue by kylouie1616** [Windower/Lua#2181]
when I do //gs disable neck or //gs disable back it says that this slot is disabled but it still swaps gear in that slot

**Comment by RubenatorX** [comment]
Well need repro steps (probably a script) and/or to have you come chat with us in discord.
But keep in mind that sometimes there's code in your script that messes with the enable/disable states of stuff without informing you

**Comment by Byrth** [comment]
Closing this because it's a user file problem.
