### ISSUE TITLE
Findall Remove Chars?

### ISSUE THREAD

**Issue by Baylion** [Windower/Lua#2206]
Hi  - 
Have used for a while but had name changes - so now it searches old names as well?
Can i turn off findall for a specific character going forward? 
Unistall / re install?
Please help  too many Dup results

**Comment by RubenatorX** [comment]
Well you can always just `//find` to only search the character that you're on.
If you don't want to hear about a certain character anymore, you can delete their folder in `windower\addons\findAll\data\`

**Comment by Chiaia** [comment]
You always uninstall/reinstall like you mentioned. Or you could do as Rub said.
