### ISSUE TITLE
Battle Mod blocking messages from the Windower itself

### ISSUE THREAD

**Issue by Licshee** [Windower/Lua#221]
When Battle Mod is on, the output of list (loaded plugins) command is filtered out.

**Comment by z16** [comment]
This has to do with the color `list` uses to display the plugins. Plugins not using the default color are still displayed (like FFOChat). Battlemod will have to be adjusted somehow to filter these.

**Comment by Byrth** [comment]
Battlemod will not and cannot be adjusted to fix this problem. Windower will have to choose a different color or allow me to change the message ID in packets passed through to the client. Until then, people will have to unload battlemod to view "list" and guildwork messages.

**Comment by Byrth** [comment]
Okay, this is fixed now from both ends.
