### ISSUE TITLE
Infobar 1.2.0.16 plugin no longer showing monster hp %

### ISSUE THREAD

**Issue by klikevil** [Windower/Lua#2210]
None of the monster.n lines appear to be working, on my end it is only showing notes.

monster.0=$target.instanceinfomultiple$$target.name$($target.hp.percent$%)  $target.aggressive(AGGRESSIVE  )$$target.linking(LINKING  )$Detects: $target.detects$  $prefix(Job: ,$target.job$,  )$Weak vs: $target.weaknesses$  Lv.$target.level$ (~$target.xp.avg$xp)
monster.1=$target.instanceinfomultiple$$target.name$($target.hp.percent$%)  Spawns: $target.spawns$ (Respawn: $target.respawn$)  Steal: $target.stolen$  Drops: $target.drops$
monster.2=$target.instanceinfomultiple$$target.name$($target.hp.percent$%)  Notes: $target.notes$

**
![image](https://user-images.githubusercontent.com/32278206/178139006-398184ea-3f7a-4f0a-bb53-fb8b4e550952.png)
**

**Comment by KenshiDRK** [comment]
The infobar plugin is deprecated, use the addon instead.

**Comment by wildsprite** [comment]
@KenshiDRK I'm using the addon myself and I'm not getting any info on any creatures. does it need a newer db file?

**Comment by KenshiDRK** [comment]
you need to configure the settings.xml file in the data folder of the addon folder. https://docs.windower.net/addons/infobar/

**Comment by wildsprite** [comment]
thank you, is there a way to make this show 2 lines for overflow rather than just 1? or is that a limitation?

**Comment by KenshiDRK** [comment]
you can make a line break with the variable ${new_line}

**Comment by wildsprite** [comment]
> you can make a line break with the variable ${new_line}

thank you very much

**Comment by klikevil** [comment]
> you need to configure the settings.xml file in the data folder of the addon folder. https://docs.windower.net/addons/infobar/

Do you have an example for a proper line that will show target remain hp %?

**Comment by KenshiDRK** [comment]
infobar can't show the hp %, you can use tparty for that.

**Comment by klikevil** [comment]
The plugin used to :-/ that's unfortunate, it looks like I'm going to 
have to load enemybar and get it stuck in the spot i want it.
