### ISSUE TITLE
Update Database to 2021 release?

### ISSUE THREAD

**Issue by randoomdude** [Windower/Lua#2215]
On your website https://iyouffxi.wordpress.com/2021/06/ supposedly the database has been updated to include Reseinjima and some other places but no longer works, will you update it in the github?

**Comment by RubenatorX** [comment]
Uh, do we have a way to get in contact with `Kevin (Kmicha)`? Cuz I think it might be kinda rude to swipe their work without their permission.

**Comment by Chiaia** [comment]
We don't take others work without them submitting it to us, unless it is fully worded anyone can use it. If you can get in contact with them we'd love to have newer info,
