### ISSUE TITLE
Binder: My Razer Blackwidow 2013 doesn't show up on Binder

### ISSUE THREAD

**Issue by bondxp** [Windower/Lua#226]
Hi,

I recently bought new keyboard Razer Blackwidow 2013, but Binder doesn't seem to recognize it like Old one (Razer Blackwidow 2012). Any work around here to solve this? or Any plan to update Binder to support this new keyboard?

Thanks,

**Comment by z16** [comment]
This is the Lua tracker, meant for addons (not plugins) and Lua-specific issues. Please repost this [here](https://github.com/Windower/Issues/issues).
