### ISSUE TITLE
Where are the lua functions defined?

### ISSUE THREAD

**Issue by gdborton** [Windower/Lua#2287]
I asked chatgpt to generate some code the follow the party leader, and it produced this:
```lua
function followLeader()
    local leader = getPartyLeader()
    if leader ~= nil then
        local myTarget = getTarget()
        if myTarget ~= leader then
            setTarget(leader)
            sendCommand('follow')
            setTarget(myTarget)
        end
    end
end

function getPartyLeader()
    local party = getPartyMembers()
    for _, member in ipairs(party) do
        if member.is_leader then
            return member
        end
    end
    return nil
end

function getTarget()
    local target = windower.ffxi.get_mob_by_target('t')
    return target
end

function setTarget(target)
    windower.ffxi.set_target(target.id)
end

function sendCommand(command)
    windower.send_command(command)
end

windower.register_event('prerender', followLeader)
```

As far as I know, `member.is_leader` doesn't exist (at least not as far as the docs show). Is there a place I can look this up in source? I tried various searches for `get_mob_by_target` which DOES exist, and could only find usages, not definitions.

**Comment by lili-ffxi** [comment]
The code generated by chatgpt barely qualifies as pseudocode - the logic is sound, if a bit unoptimal, for example you wouldn't want to run this in prerender at all ever, but the functions it spews out are often not real, like in this case. You would need to write most of these functions by yourself. Specifically, there's no `is_leader` field anywhere, there's an entry in the table returned by `windower.ffxi.get_party()` called `party1_leader` (or 2, or 3 for alliances) that contains the ID of the player who is the leader, but you'd have to compare the two fields manually, etc etc etc.

I recommend you forego chatgpt entirely and instead come to discord for help with development.

**Comment by gdborton** [comment]
I can hop in discord, and realize that chatgpt is wrong, but I'm still curious about the original question.

Where are these functions defined? Is there any chance at all that the docs are out of date?

**Comment by gdborton** [comment]
Got an answer in discord, these are in windower core which is closed source.

**Comment by RubenatorX** [comment]
For anyone that finds this later -- functions are documented here:
https://github.com/Windower/Lua/wiki/FFXI-Functions
