### ISSUE TITLE
[Addon][Gearswap] Faulty file_unload() function prevents unloading/changing profile.

### ISSUE THREAD

**Issue by lili-ffxi** [Windower/Lua#2306]
If the `file_unload()` function in any given profile is faulty in a way that the file can be loaded but the function will fail to run, gearswap isn't able to unload the profile at all - neither manually (`//gs reload`) nor at job change. 
The only solution is to unload gearswap entirely.

Example:
```lua
function file_unload()
    print(dummy.lol)
end
```

**Comment by Byrth** [comment]
So we need to wrap this in Lua's version of a try-catch block or something?

**Comment by lili-ffxi** [comment]
I honestly have no idea, the function is already pcalled but the failure still stops the rest of the script from continuing to load the new file. We had a very brief conversation with Arcon about it on discord, but it didn't lead to any conclusion.

It's also possible that it's not solvable and it just goes in the "known issue" bin for when somebody comes asking across the issues and asks for support.

**Comment by Byrth** [comment]
This looks like the problem to me: https://github.com/Windower/Lua/blob/ed0eb980b12a1af819b35585f4a8d0a4b42790aa/addons/GearSwap/flow.lua#L321

user_pcall rethrows the error instead of eating it.

**Comment by lili-ffxi** [comment]
Rright, I thought that was calling logger's error function but I see `error()` is in fact being re-un-defined earlier.
Would a simple `print()` be appropriate here in this case?

**Comment by Byrth** [comment]
I think I rely on that ending code execution and I'm not sure changing it at this point is worth the risk. I'll just add a bool that explicitly converts it to print.

**Comment by Byrth** [comment]
https://github.com/Windower/Lua/pull/2315

Closed by this!
