### ISSUE TITLE
Lua iconv support

### ISSUE THREAD

**Issue by BLM-jp** [Windower/Lua#232]
Would not any plans to support the iconv in LuaCore?
http://ittner.github.io/lua-iconv/

In a Japanese environment, input and output so SJIS, when referencing and output the contents of a resources(UTF-8), it is necessary to convert(SJIS->UTF-8 or UTF-8->SJIS).

**Comment by alphaONE2** [comment]
This isn't just a problem for Japanese, it affects every client language to some degree.

We've been talking a lot about character encodings recently. And I think the consensus has been that we should make Lua work entirely with UTF-8, and have LuaCore do the necessary conversion to Shift_JIS internally. The only thing stopping us is that there are a few addons that already expect text to be in Shift_JIS, so we need to proceed cautiously.

**Comment by BLM-jp** [comment]
You are thinking the automatic conversion in LuaCore? (in: EN | JP | FR | GE -> UTF-8, out: UTF-8 -> EN | JP | FR | GE)

Features for the conversion API, I was thinking that it is provided.
I think to do in the addons/script that want to convert.

**Comment by z16** [comment]
The game uses Shift_JIS (a variation) internally for all language clients, so it would be {in: UTF-8, out: Shift_JIS}. That way, all addon files would have to be in UTF-8, and would be handled that way internally, then output Shift_JIS to the chatlog. Personally I don't think it's too much to ask of developers to write their files in an international format, especially on an international game.

**Comment by Zireael** [comment]
The sooner done, the better, in my opinion. Few addons getting broken for few days is better than 20 addons getting broken in 2 months. It's not like the game will become unplayable if you miss out on few addons for a bit. Well, except [Send] users - they'd riot immediately (again...).

**Comment by z16** [comment]
We added manual conversion functions to LuaCore (`windower.to_shift_jis` and `windower.from_shift_jis`), but we will design the API better in v5. Until then, this will be it.
