### ISSUE TITLE
Send: send doesn't work after patch to hook 4.0.0.27

### ISSUE THREAD

**Issue by bondxp** [Windower/Lua#235]
Hi,

After windower new update send stop working. All command seem to can't send via multibox now.

PS. there is no error show up, send function just doesn't working.

**Comment by ghost** [comment]
Experiencing the same issue. Others reported partial functionality with XI-Util's send plugin, but it didn't work for me.

**Comment by Furyofthestormx** [comment]
Same issue here. If I roll back my hook send works again but because the Hook auto updates every launch it's a bit of a pain
