### ISSUE TITLE
Gearswap not swapping gears properly according to the code

### ISSUE THREAD

**Issue by Vhaldarius** [Windower/Lua#2406]
Hi there, i am new to using gearswap. I have trouble that gearswap doesn't swap my equipment entirely as I have set. Only head, body and hand that swapped according to the code, but the rest didn't swap at all. 

Here is the code in my gearswap for my THF, please help me to spot if the code has any typo or something. Any help would be greatly appreciated. Thank you!

function init_gear_sets()
	--============================================================
	--			Precast sets
	--============================================================
	sets.TreasureHunter = {}
	
	sets.precast.JA['Collaborator'] = {}
	sets.precast.JA['Accomplice'] = {}
	sets.precast.JA['Flee'] = {}
	sets.precast.JA['Hide'] = {}
	sets.precast.JA['Conspirator'] = {}
	sets.precast.JA['Steal'] = {}
	sets.precast.JA['Despoil'] = {}
	sets.precast.JA['Perfect Dodge'] = {}
	sets.precast.JA['Feint'] = {}
	sets.precast.JA["Assassin's Charge"] = {}

	sets.precast.JA['Sneak Attack'] = {}

	sets.precast.JA['Trick Attack'] = {}

	sets.precast.Waltz = {}
	sets.precast.Waltz['Healing Waltz'] = {}
	
	--============================================================
	
	sets.precast.FC = {}
	sets.precast.FC.Utsusemi = {}

	--============================================================
	
	--Snapshot
	sets.precast.ranged = {}

	sets.wsBase = {
		range="Raider's Bmrng.",
		head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
		body="Meg. Cuirie +1",
		hands="Meg. Gloves +1",
		legs={ name="Lustr. Subligar +1", augments={'Attack+20','STR+8','"Dbl.Atk."+3',}},
		feet={ name="Lustra. Leggings +1", augments={'HP+65','STR+15','DEX+15',}},
		neck="Caro Necklace",
		waist="Wanion Belt",
		left_ear="Mache Earring",
		right_ear="Telos Earring",
		left_ring="Rajas Ring",
		right_ring="Ramuh Ring +1",
		back="Tantalic Cape"
	}
	
	sets.wsBase.DEX = {}
	
	sets.wsBase.MediumAcc = {}
	sets.wsBase.HighAcc = {}

	sets.wsBase.Magic = {}
	
	--============================================================
	--			Midcast sets
	--============================================================
	
	sets.midcast.FastRecast = {}
	sets.midcast.Utsusemi = {}

	sets.midcast.ranged = {}
	sets.midcast.ranged.TH = sets.TreasureHunter
	
	--============================================================
	--			Other sets
	--============================================================
	
	sets.weapons.Other = {}
	sets.weapons.TH = {}
	sets.weapons.DD = {}
	sets.weapons.Accuracy = {}
	sets.weapons.THAcc = {}
	
	sets.resting = {}
	
	sets.idle = {
		range="Raider's Bmrng.",
		head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
		body="Meg. Cuirie +1",
		hands="Meg. Gloves +1",
		legs="Meg. Chausses +1",
		feet="Meg. Jam. +1",
		neck="Loricate Torque +1",
		waist="Flume Belt +1",
		left_ear="Eabani Earring",
		right_ear="Odnowa Earring +1",
		left_ring="Defending Ring",
		right_ring="Shneddick Ring",
		back="Solemnity Cape"
	}
	sets.idle.with_buff = {}
	sets.idle.with_buff['doom'] = {}
	sets.idle.with_buff['reive mark'] = {}
	
	sets.defense.Evasion = {}

	sets.defense.DT = combineSets(sets.defense.Evasion,{})
	
	sets.defense.PDT = combineSets(sets.defense.DT, {})

	sets.defense.MDT = combineSets(sets.defense.DT, {})
	
	sets.engaged = {
		range="Raider's Bmrng.",
		head={ name="Dampening Tam", augments={'DEX+10','Accuracy+15','Mag. Acc.+15','Quadruple Attack +3',}},
		body="Meg. Cuirie +1",
		hands="Meg. Gloves +1",
		legs={ name="Samnuha Tights", augments={'STR+5','DEX+6','"Dbl.Atk."+2',}},
		feet={ name="Herculean Boots", augments={'Accuracy+21 Attack+21','"Triple Atk."+4',}},
		neck="Lissome Necklace",
		waist="Sarissapho. Belt",
		left_ear="Telos Earring",
		right_ear="Digni. Earring",
		left_ring="Rajas Ring",
		right_ring="Cacoethic Ring",
		back="Canny Cape"
	}
	sets.engaged.with_buff = {}
	sets.engaged.with_buff['doom'] = {}
	sets.engaged.with_buff['reive mark'] = {}
	
	sets.engaged.MediumAcc = {}
	
	sets.engaged.HighAcc = {}
	
	sets.engaged.TH = {}
end

**Comment by Vhaldarius** [comment]
Or is it because I have some gears at wardrobe 5-6 and gearswap can't identify those wardrobe?

**Comment by Nifim** [comment]
you should come yo our discord for support regarding gearswap [#gearswap-support](https://discord.com/channels/338590234235371531/566275097753813013)
