### ISSUE TITLE
add interface functions get_weather_id(), get_storm_id(), get day_id()

### ISSUE THREAD

**Issue by ReaperX** [Windower/Lua#25]
get_weather_id()

returns the current weather ID, 

get_storm_id() 

returns the current (SCH) storm effect ID,

get_day_id()

returns the current day's ID.

**Comment by z16** [comment]
I'd like to expand that to get_environment(), which should return a table containing (at least) the following:

```
{
    weather: int
    day: int or string
    dayelement: int or string
}
```

Could include moon, moon%, season and similar things as well, although those can already be calculated, so wouldn't be a priority.

Storm ID you can already get, it's in the get_player()['buffs'] array.

**Comment by alphaONE2** [comment]
The day of the week and by extension the day element is trivially calculable from the current server time. We do have code to do this in the plugin API, but I think it's probably better if we expose a get_server_time() function and implement the rest of the time-related functions in Lua. Just my two cents.

**Comment by alphaONE2** [comment]
Oh and while I'm at it, the storm effect is available in the buff list, and yes that's how Spellcast implements it.

**Comment by z16** [comment]
<_< Not sure what I was on, but I knew that a well, I even made a function to calculate it.. but yeah, I guess having the server time for that would be nice. Then all these things could be calculated. Having weather reported would still be great though.

**Comment by aureus1** [comment]
Added get_ffxi_info() to handle weather/day lookups.  As mentioned, scholar weather can be accessed via the player buff list.
