### ISSUE TITLE
Plasmon does not download correctly from launcher and shortcut command is incorrect

### ISSUE THREAD

**Issue by quedari** [Windower/Lua#251]
After repeatedly trying to download plasmon using the launcher and it not downloading anything but the plasmon folder (empty except for the "data" folder which was also empty), I finally downloaded it manually. I then tried to execute commands with //delve test or //delve show, and it did nothing. So I tried //plasmon test and it worked perfectly. Just wanted to let you know. Hope this is in the right spot.

**Comment by alphaONE2** [comment]
For launcher bugs (such as addons not installing correctly) please submit your issue at the [Windower/Issues](https://github.com/Windower/Issues) tracker.

For plasmon, please submit any issues to the tracker listed in the Launcher ([giulianoriccio/Lua](https://github.com/giulianoriccio/Lua/issues)).

**Comment by quedari** [comment]
If there had been a bug tracker link for plasmon in the launcher I would have used it, but thank you for the link.

**Comment by alphaONE2** [comment]
No problem, I understand there have been some issues with that lately, that's why I provided the link.
