### ISSUE TITLE
StratHelper & Tabula Rasa

### ISSUE THREAD

**Issue by Sykel** [Windower/Lua#254]
StratHelper decrements the variable _SCH_STRATS_CURRENT even while Tabula Rasa is active.

This results in negative values over the duration of Tabula Rasa's buff as well as afterwards.

**Comment by Ihellmasker** [comment]
I never really considered that when I made it, just need to throw the value back to max and stop it decrementing.

**Comment by Ihellmasker** [comment]
Updated it, I think, can you test it and let me know.

**Comment by Sykel** [comment]
Hi, thanks for the the quick response.

I quickly tested it by jumping on SCH in Jeuno.

I tried using stratagems without Tabula Rasa and tried using it under normal circumstances, and I found a line error on line 62.
![ffxi_2013 05 17_20 34 57](https://f.cloud.github.com/assets/3309392/521112/86c86a40-bf6c-11e2-88eb-dd2c09181476.png)

I also tried it while using Tabula Rasa, and the same error occurred.
![ffxi_2013 05 17_20 33 05](https://f.cloud.github.com/assets/3309392/521114/9ef5fa06-bf6c-11e2-89a7-548ad68214d3.png)

I think it was a simple syntax error. I changed:

if get_player()['buffs']:contains(377) == false then

to:

if T(get_player()['buffs']):contains(377) == false then

and the problem seemed to be fixed, and the stratagem values seemed to persist correctly!
![ffxi_2013 05 17_20 56 26](https://f.cloud.github.com/assets/3309392/521119/1d355572-bf6f-11e2-8e98-1652cb50cbe8.png)

**Comment by Ihellmasker** [comment]
Cool, fixed that error then, so I'ma assume its all fine now.
