### ISSUE TITLE
Feature request: Provide a way to get a table of a player's key items

### ISSUE THREAD

**Issue by jerryhebert** [Windower/Lua#28]
It would be great to have this list since it would enable the creation of KI tracking add-ons!

thanks

**Comment by Byrth** [comment]
This is possible, but would require someone to create a key items resource either through .dat mining or an automated in game process. Then you'd want to take the bit field in the key item packets and transcribe it onto the key item IDs. Pain in the ass, but it's technically possible.

**Comment by Byrth** [comment]
Arcon created the get_key_items() function, so this now exists.
