### ISSUE TITLE
Slips.lua missing an item

### ISSUE THREAD

**Issue by Maurauc** [Windower/Lua#290]
Slip 03 in Slips.lua is missing Silver Fox Earring. I noticed it when using the porter addon. All items after Fourth Schuhs are offset by one. (My Rubeus Jacket showing as Rubeus Gloves, Griffinclaw instead of Rose Strap, etc)

**Comment by z16** [comment]
Fixed.

**Comment by giulianoriccio** [comment]
Thank you, I've fixed the bug.
Sorry for any inconvenience it may have caused
