### ISSUE TITLE
Autora freezes POL

### ISSUE THREAD

**Issue by Gotenn** [Windower/Lua#293]
I'm not sure if its not updating my ranged delay from the settings, but it seems as though its trying to send multiple /ra to the game per second causeing windower to freeze.

**Comment by alphaONE2** [comment]
The author of AutoRA has requested that bugs for this Addon be posted to [banggugyangu/Lua](https://github.com/banggugyangu/Lua/issues). And it appears that this bug has been reported as banggugyangu/Lua#2. I suggest posting any information you can to that issue.
