### ISSUE TITLE
AutoRA

### ISSUE THREAD

**Issue by MIGhunter** [Windower/Lua#298]
Not sure if this is where I should post this since not many look at the windower forums anymore.

I was using AutoRA and I get this error:

> Lua -- F:\Games\FFXI\Windower4\addons\autora\autara.lua:115: attempt to compare nil with number

It was working semi ok but now when I hit ctrl d, it freezes my game.

**Comment by alphaONE2** [comment]
There's a link to the correct bug tracker under each Addon in the launcher. (or at least most of them...)

For AutoRA please post any issues at [banggugyangu/Lua](https://github.com/banggugyangu/Lua/issues) so that the author will see them.
