### ISSUE TITLE
Unable to act on <st*> targets

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#319]
I cannot act on targets from `<st*>` actions, which is problematic when they are monsters.

For instance, if I someone uses `<stnpc>` provoke, I can probably obtain the target name that is being acted on. However, I cannot act on the target because my only tools are `<t>`, `<me>`, `<bt>`, etc..

**Comment by dustin-lennon** [comment]
I find this when it comes to me using my ranged attack macro and spellcast. Macro I use on my DNC is as follows
/equip range "Jinx Discus"
/ra `<stnpc>`
/p Incoming `<lastst> <call12>`
/equip range "Charis Feather"

When using that macro I don't even have the option of selecting the target and defaults to me as indicated by what is returned with `<lastst>`.
