### ISSUE TITLE
Custom Timestamp Formats not recognized properly

### ISSUE THREAD

**Issue by dustin-lennon** [Windower/Lua#326]
When having a custom timestamp such as ${m}${day}|${hour12}:${min}${ampm} it shows up in chat as 06${day}|${hour12}:${min}${ampm}. It can be noticed in the screen shot attached to this post.

![ffxi_2013 06 06_21 57 13](https://f.cloud.github.com/assets/92093/621928/5b04356c-cf1e-11e2-9b9e-04fd802bd54b.png)

**Comment by alphaONE2** [comment]
Please post this at [giulianoriccio/Lua](https://github.com/giulianoriccio/Lua/issues).
