### ISSUE TITLE
Automaton equipment interface

### ISSUE THREAD

**Issue by elijahatkinson** [Windower/Lua#353]
Would there be any chance you could expose the automation equipment interface to the LUA core so I can develop an addon similar to azuresets for pup? :)

**Comment by z16** [comment]
It will be added very shortly (probably today), and I think there's already an addon for it being done, it just needs the proper LuaCore functions.

If you wanna be closer to Lua addon development you should join our IRC channel on irc.ffochat.com (channel #lua for Lua development specifically). You can just download and use the FFOChat plugin for it if you don't have a proper IRC client.

**Comment by z16** [comment]
I forgot to say that this was added to the 4.1 branch (development preview), and an addon to swap attachment for PUP has already been made, although it's waiting to be published.
