### ISSUE TITLE
Possible infinite loop in Sets lib

### ISSUE THREAD

**Issue by giulianoriccio** [Windower/Lua#357]
@z16 

```
//eval requires 'sets' for item in S{'a'}:it() do end
```

This will instantly freeze the game. `:it()` is probably not interrupting the loop.
Interrupting the `for` loop will not freeze the game.

**Comment by z16** [comment]
That's correct, it's fixed in the new libs, for the new LuaCore, but I didn't push a fix for it to the current release yet, because nothing was using it at the time. I'll push a fix for it now.
