### ISSUE TITLE
AzureSets suggestion

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#363]
Add a configurable option show a Timers custom timer showing the cooldown before blue magic spells are available for use.

**Comment by alphaONE2** [comment]
Addon-specific issues should be reported to the author using the link in the Windower 4 launcher. Please repost this on [nitrous24/Lua](https://github.com/nitrous24/Lua/issues).

**Comment by nitrous24** [comment]
While yes, this should've been posted to my fork ask iryoku said, and though it's not configurable, it already does this.  send_command('timers c "Blue Magic Cooldown" 60 up') immeidately after equipping a set.

**Comment by ghost** [comment]
Thanks, I don't know why mine wasn't doing it. Probably something in my timers settings.

**Comment by nitrous24** [comment]
i suggest checking your timers settings to make sure the custom x/y are not outside your window frame >.>
