### ISSUE TITLE
Feature request: A table of loaded addons / plugins.

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#364]
It would be awesome if we could get a table listing what addons the user is running, being able to notify the user if they need to load an addon for certain functionality.

**Comment by alphaONE2** [comment]
We don't want to encourage Addon dependencies, common functionality should be considered for inclusion as a lib.

**Comment by ghost** [comment]
Sorry if this reopens the issue.

Particularly, I wanted to write a short addon that basically unloaded spellcast when I was logging out and share it with a few friends, and the community as a whole if it was a worthy addition. For my friends and I, we crash when we mule if we don't unload spellcast first. Unloading spellcast seems to fix it.

What I wanted to do was basically

plugin_load
  -- check if spellcast is running
  -- if spellcast is running, set a flag that allows the plugin to operate

event_logout
  -- if spellcast was running on intial load, unload it

event_login
  -- if spellcast was running on initial load, reload it

Just a little bit of backstory, but I can write a dirty version that just loads and unloads it. I'm sure that the bug will probably be nailed down in time, because you guys really are great, but crashing sucks ; ;.

Thanks

**Comment by nitrous24** [comment]
look into plugin_manager addon, it does that and more (sort of) you give it a list of addons/plugins to load  based on characters logged in. here's mine for example it basically unloads everything that's listed per character (and not in global) and loads them again (or different if you log in a differnet character) when you log back in.

``` xml
<settings>
    <global>
        <!-- This will be used for all the characters that you don't make a specific set of plugins/addons for -->

    </global>

    <Nitroustaru>
        <plugin>Bidder</plugin>
        <plugin>Boxhelper</plugin>
        <plugin>Cancel</plugin>
        <plugin>ChatLink</plugin>
        <plugin>Chatmon</plugin>
        <plugin>Distance</plugin>
        <plugin>ffochat</plugin>
        <plugin>Find</plugin>
        <plugin>GearCollector</plugin>
        <plugin>Guildwork</plugin>
        <plugin>Itemizer</plugin>
        <plugin>jazero</plugin>
        <plugin>LightLuggage</plugin>
        <plugin>Run</plugin>
        <plugin>Sandbox</plugin>
        <plugin>Silence</plugin>
        <plugin>Spellcast</plugin>
        <plugin>SSOrganizer</plugin>
        <plugin>Timestamp</plugin>
        <plugin>TParty</plugin>
        <plugin>Timers</plugin>

        <addon>autojoin</addon>
        <addon>azuresets</addon>
        <addon>battlemod</addon>
        <addon>cblock</addon>
        <addon>eval</addon>
        <addon>ffocolor</addon>
        <addon>findall</addon>
        <addon>highlight</addon>
        <addon>linker</addon>
        <addon>plasmon</addon>
        <addon>porter</addon>
        <addon>respond</addon>
        <addon>reive</addon>
        <addon>scoreboard</addon>
        <addon>send</addon>
        <addon>stna</addon>
    </Nitroustaru>
</settings>
```

**Comment by ghost** [comment]
Thanks, I'll use that.
