### ISSUE TITLE
Gametime Additional options

### ISSUE THREAD

**Issue by unununium** [Windower/Lua#367]
Hi I'm not sure if I'm posting this on the right place but I want to contribute the modified options I worked on the Gametime Addon.

1) Options for modifying  textbox font and size for day and game time

2) Extra mode for a compact mode where the days strings are displayed by using the ' ° '  symbol. 

Reasons I did this: I like my UI clean and symetrical. Not having an option for the font type and size didn't allow for maximum customization.

Also the game day name isn't really required. With a small glance at the color should be enough. 

Here's the source I modified with this options
http://pastebin.com/n8sssPjP

**Comment by z16** [comment]
If you want that code to go live, you need to fork the public Lua repository. To do that, go to this repository's [main page](https://github.com/Windower/Lua) and click on "Fork" in the top-right. Then check out those changes locally (for example using the [GitHub client for Windows](http://windows.github.com/)), change whatever you think is worth changing, then submit a pull request, so we can merge it into the main branch.

If you want to comment on an addon in particular or discuss any features, go to the addon creator's repository (in this case, [here](https://github.com/thatdudegrim/Lua/issues)). We are not in control of any addon code in particular, so we will not take care of merging that or uploading it for you, you'll either need to talk to the addon creator about it, or submit your own pull request (which you are welcome to do). I'm gonna close this now, as this isn't the right place for addon update discussions.
