### ISSUE TITLE
Using &gt; as a part of a value in a settings file may cause an unexpected token error on config.load

### ISSUE THREAD

**Issue by cairthenn** [Windower/Lua#369]
I'm pretty sure it only happens if &amp;gt; is the last non-space character within a field.

Something like,

<code>&lt;responses&gt;input /ma Paralyna &amp;lt;t&amp;gt;&lt;/responses&gt;</code>

would cause an error, but

<code>&lt;responses&gt;input /ma Paralyna &amp;lt;t&amp;gt; x&lt;/responses&gt;</code>

or

<code>&lt;responses&gt;input /ma Paralyna &amp;lt;t&amp;gt;, input /echo Hi!&lt;/responses&gt;</code>

would not.

**Comment by z16** [comment]
I forgot to say that I fixed that!
