### ISSUE TITLE
weird textbox issues in 4.1

### ISSUE THREAD

**Issue by nitrous24** [Windower/Lua#412]
this happens when i do tb_set_text with color stuff included
``'\cs(255,100,100)'..str..'\cr'''
The text in console is right, but it gets trimmed in the textboxes
![weirdness](https://dl.dropboxusercontent.com/u/184438010/screenshots/weirdness%20textbox.PNG)

**Comment by alphaONE2** [comment]
The text itself is fine, but it seems to be including the markup when measuring the extents.

**Comment by Alteubent** [comment]
This happened after I talked to Monissette in port jueno.
![ffxi_2013 12 15_04 16 30](https://f.cloud.github.com/assets/3992381/1813177/77e9d024-6eab-11e3-8810-04c6fe4cc6b6.jpg)

**Comment by z16** [comment]
This is unrelated to the issue described in here, it's Highlight's fault.
