### ISSUE TITLE
Autojoin

### ISSUE THREAD

**Issue by LoireMar** [Windower/Lua#450]
Currently not joining characters that are on the whitelist

**Comment by z16** [comment]
Are you on the 4.0 or 4.1 branch? If it was the 4.1 branch, this has been fixed.

Also, in future report addon issues to the respective addon devs, this tracker is for general Lua or LuaCore errors. Addon developers are generally not associated with Windower, so they might not even see their issues reported here. There should be a link to the author's bug tracker in the Windower Launcher for each addon in the `Addon` tab.

**Comment by LoireMar** [comment]
I am using the 4.1 version and to add as well using the bug tracker present
a 404 page not found on github

**Comment by z16** [comment]
Good catch, that was my mistake. I deleted my old repository and when I made a new one I forgot to add an issue tracker. It works again now, and AutoJoin has been fixed for both 4.0 and 4.1 now.
