### ISSUE TITLE
Config Library: xml_escape()

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#465]
Looks like the config library is missing a function:

417: attempt to call method xml_escape (a nil value)

**Comment by Byrth** [comment]
Just to update this, we realized that this was being caused by the different ways that Lists (continuous sequential numerically indexed tables) were being encoded in xml vs. noncontinuous tables.

**Comment by z16** [comment]
Changed to work normally with regular Lua tables. Only actual list objects (from the lists library) will now be saved in that format.
