### ISSUE TITLE
v4.1: event_mouse()

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#497]
event_mouse's "type" value appears to take the values 512 (movement), 513 (left click down), 514 (left click up), 516 (right click down, 517 (right click up), and 522 (scrolling in either direction. Somewhat randomly, it also can take the value 160 (leaving the window).

Would it be possible to reduce these to be, like, 0,1,2,3,4,5,6,7,8,9,10 or something? Why are they offset by 512 (except for 160, for some reason)?

**Comment by Byrth** [comment]
161 appears to be left-clicking down on a window border, but 514 still fires on the left up-click on a border. Correspondingly, 164 and 165 are right clicking down/up on a border. Scrolling on a border does not get a unique value.

The 514 thing on a border is certainly an error. The rest can be left as it is, but it's undocumented and unintuitive.

**Comment by Byrth** [comment]
These are fine (except for the left-click up-state on a border, which should be code 162). There should just be a link somewhere to: http://wiki.winehq.org/List_Of_Windows_Messages

**Comment by z16** [comment]
Fixed:
Mouse events will now have values between 0 (mouse move) and 14 (mouse horizontal wheel).

Also fixed the mouse wheel delta in the process.
