### ISSUE TITLE
v4.1 - Persistance issues in addon command or inject_incoming

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#499]
I was making an addon today: https://gist.github.com/Byrth/7250121

Entering:
//lua c chat_to_add This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20

Resulted in:
This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 2

So I started checking if I needed to null terminate the string, hence the string.byte checks in the while loop. When I made the last number "255", it came through fine. When I deleted the last number and left it terminated by a space, I still ended up getting a 2 at the end. I reloaded it, entered the same command (with no 20 at the end) and still got a 2 at the end of my output. Just to be clear:
- //lua c chat_to_add This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20
  Became:
- This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 2
- //lua c chat_to_add This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 255
  Became:
- This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 255

Then:
- //lua c chat_to_add This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 
  Became:
- This is a string of arbitrary length. How long can it go? 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 2

Reloaded, and I still got the same result for the final input. I assume that there is some problem with or without the final whitespace.

This problem is not necessarily in addon_command, but could also be in packets.inject_incoming. It seems to move in bytes of 4.

**Comment by z16** [comment]
Did a bunch of changes to that recently, is it still happening? Doesn't for me, but not sure if I'm reproducing it right.

**Comment by Byrth** [comment]
Yes, it does still occur as described.

**Comment by z16** [comment]
Fixed.
