### ISSUE TITLE
get_mob_by_target - ht and ft

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#505]
I do not believe that get_mob_by_target currently works with `<ft>` or `<ht>`.

**Comment by z16** [comment]
It should work with `<ht>`, although it will not always return the same mob as `<ht>` in the game, because I can't find out how the game determines it. So it's not reliable in situations with more than one CFH'd mob around, although it will always pick one of those mobs.

**Comment by Byrth** [comment]
Arcon fixed this a month ago.
