### ISSUE TITLE
Add treasure pool information

### ISSUE THREAD

**Issue by z16** [Windower/Lua#51]
A function to get the current treasure pool as a table would be practical for LL-y features, among other things. It could get added separately, or by amending the `get_items()` struct.

**Comment by ReaperX** [comment]
In addition to this, I would also like to have an event that is triggered when an item falls from the treasure pool into inventory. I'm thinking of an addon that moves currency and forgotten items to sack or satchel while farming Dynamis. That would be very useful when there are only few free inventory spots.

**Comment by z16** [comment]
I'll open this as an additional issue, treasure pool information has been added now.
