### ISSUE TITLE
battlemod, level -1 targets checking incorrectly

### ISSUE THREAD

**Issue by SnickySnacks** [Windower/Lua#580]
battlemod.lua
Gives an error 
"Uknown skill 4294967295"
and displays the results of the check like
"Wild Rabbit seems like level 4294967295"

There's a check in the code for the level value being 4294967296, but that's not what ffxi returns. I modified my local copy as follows (flipped the order of the skill name assignment and calculated the negative levels)

```
        if am.message_id > 169 and am.message_id <179 then
            if am.param_1 > 2147483647 then
                skill = 'like level -'..4294967296-am.param_1..' ('..ratings_arr[am.param_2-63]..')'
            else
                skill = 'like level '..am.param_1..' ('..ratings_arr[am.param_2-63]..')'
            end
        elseif fields.skill then 
            if res.skills[am.param_1] then
                skill = res.skills[am.param_1][language]:lower()
            else
                windower.add_to_chat(8, 'Unknown Skill '.. tostring(am.param_1))
            end
        end
```

I don't know enough about lua to know how to calculate the levels directly if there's an easier way. :/

**Comment by Byrth** [comment]
This is fixed now (by you!)
