### ISSUE TITLE
Chatporter

### ISSUE THREAD

**Issue by eotfofyl** [Windower/Lua#586]
1.35 just logs what i type, nothing from anyone else.

**Comment by Alteubent** [comment]
Chatporter was only showing the outline of the boxes for me no matter what settings I adjusted. A chatporter error I received recently.
![ffxi_2013 12 15_05 05 23](https://f.cloud.github.com/assets/3992381/1813202/cdc60498-6ead-11e3-9b98-248626e3e32e.jpg)

**Comment by Arti2406** [comment]
Since the January update also doesn't display chat from other people.

**Comment by Nifim** [comment]
could not replicate
