### ISSUE TITLE
WinControl fatal error when I tried to //reload spellcast

### ISSUE THREAD

**Issue by Alteubent** [Windower/Lua#587]
On side note Im not quite sure what the series of errors at the top of this are being generated from due to not being able to scroll up or export errors.

![ffxi_2013 12 26_23 28 32](https://f.cloud.github.com/assets/3992381/1813254/8ee54628-6eb0-11e3-90dd-d9e8effd831d.jpg)

**Comment by Byrth** [comment]
This looks like a memory corruption issue that was probably actually unrelated to WinControl.

Please feel free to reopen this issue if you replicate it.
