### ISSUE TITLE
POL (Luacore.dll) crashes when muling

### ISSUE THREAD

**Issue by Zireael** [Windower/Lua#606]
Hi, sorry, I don't run your debug dumper, so can't offer a dump for this, but my POL crashes when I do relogging into mule. Running a single instance of POL.
It doesn't happen all the time, maybe 1/10. I don't do anything else aside from log in->mule->mule->...->crash

Windows code for this says it's illegal memory read, I think c0000005

Podpis problemu:
  Nazwa zdarzenia problemu: APPCRASH
  Nazwa aplikacji:  pol.exe
  Wersja aplikacji: 1.18.13.0
  Sygnatura czasowa aplikacji:  4e3bcddc
  Nazwa modułu z błędem: luacore.DLL
  Wersja modułu z błędem:    1.4.0.2
  Sygnatura czasowa modułu z błędem: 52c3b945
  Kod wyjątku: c0000005
  Przesunięcie wyjątku:   000a1b01
  Wersja systemu operacyjnego:  6.1.7601.2.1.0.256.1

---

Lua addons I have enabled:
    <addon>vwhl</addon>
    <addon>reive</addon>
    <addon>send</addon>
    <addon>findAll</addon>
    <addon>autojoin</addon>
    <addon>autocontrol</addon>
    <addon>dynamishelper</addon>
    <addon>porter</addon>
    <plugin>Itemizer</plugin>
    <plugin>Sandbox</plugin>
    <plugin>FFXIDB</plugin>

**Comment by z16** [comment]
Nothing we can do without a crash dump or a sure way to reproduce it. Also, this belongs on the Windower bug tracker, but there are already various reports of this.
