### ISSUE TITLE
Game Crashing on character login.  Windower 4.0 w/ no plugins installed.

### ISSUE THREAD

**Issue by Pheelix** [Windower/Lua#62]
Friend can use the game fine using normal pol.  When he tries to use windower 4.0 from a fresh install and no plugins installed, he will crash once he logs his character in.

Can delete this issue, He just installed the update files from bg and didn't run the seekers install.  After he ran the seekers install and did a small update through pol it worked fine.

**Comment by Ihellmasker** [comment]
You've posted this is the wrong area. This is the Lua addon area not Windower issues. I have reposted this for you in the correct place [here](https://github.com/Windower/Issues/issues?page=1&state=open).
