### ISSUE TITLE
Enemy spells and ability names not colored

### ISSUE THREAD

**Issue by Zireael** [Windower/Lua#625]
Hi.
Battlemod doesn't seem to load/use
        <mobspellcol>167</mobspellcol>
        <mobwscol>167</mobwscol>
settings from colors.xml.
Both enemy spells and abilities are colored for me the same as my spells and abilities. In colors.xml I have both enemy spells and abilities set to be red (167).

**Comment by Nifim** [comment]
unable to replicate
