### ISSUE TITLE
GearSwap (Debug)

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#645]
i am currently getting the following text within game whenever I try to cast a spell.

GearSwap (Debug): Unable to create a packet for this command or action canceled (text of spell goes here eg.(/ma "haste" < stal>))
(< stal> doesnt have a space, it wont show stal here with the brackets attached for some reason.)
just thaught id mention this debug text just incase this is not supposed to be happening

**Comment by Byrth** [comment]
Yeah, this is supposed to happen. GearSwap can't make a packet for <st> commands because they can't be translated to a target ID. The debugmode message is a little spammy, but intended.
