### ISSUE TITLE
my haste macro

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#646]
my haste macro in game exactly:

/ma "Haste" < stal> (without the space for some reason it doesn't show on here without the space i.e. the  edit ^^)

haste is in blue using the games auto-translate. I occasionally get an odd issue where the spell would fire at who ever the original pointer is pointing at, eg myself without having yet hit enter to tell it to fire the spell at a designated target.

this issue persists until i reload gearswap. not my sripts, the actual addon, unsure if others have had a similar issue. it only happens to my haste macro for some reason, i have many spells that use < stal>. the macro is set at position alt 2 (I'm sure this has no relevance, i just want to make sure i give as much info as possible).
also this weird error occurs after loggin, and sometimes even after the game has been running for a while it suddenly starts happening.

**Comment by Byrth** [comment]
This is a shortcuts issue that I think I fixed a while ago. I agree that it was sporadic and difficult to track down and a huge pain in the ass, but I think it's fixed.

Please reopen it if you find it happening again.
