### ISSUE TITLE
autojoin not always auto-joining

### ISSUE THREAD

**Issue by Heretic667** [Windower/Lua#648]
"Once loaded, will automatically join party and alliance invites. If you're in a CS, it will wait until it's finished and then join (unless the invite time expires). It will also wait in similar situations, such as being dead and unable to act. It will not process the invite at all if the treasure pool is not empty. It will also wait until the treasure pool is cleared to join, although it can be forced by typing /join normally."

It has never actually done this wait-until-CS-is-finished type of thing for me.  At the very least it's awesome for accepting invites when the character is available to accept them.

For example, fishing, you cannot accept an invite while fishing.  Theoretically, this should /join when I'm done fishing?  It doesn't, I have to manually type /join when the character is available to accept the invite (I know, first world problems right!?).  It's definitely not a timeout issue when the invite just happened.

I don't believe this is limited to fishing.  It just happens commonly enough for me to see while I happen to be fishing.

If it's an easy fix, great!  If time/resources are low, don't sweat it.

**Comment by z16** [comment]
It should be simple to fix if it's broken, although I don't remember even having added it yet

But this is the general Lua tracker, for addon specific bugs please use the addon author's tracker ([link](https://github.com/z16/Lua/issues)).
