### ISSUE TITLE
Macro lag

### ISSUE THREAD

**Issue by Pheelix** [Windower/Lua#65]
Friend is having Macro lag in 4.0, He presses the macro and it takes 2-3sec for the commands to go through.  Not sure if this is a windower problem or ffxi but i figured id post it here.

**Comment by Ihellmasker** [comment]
You've posted this is the wrong area. This is the Lua addon area not Windower issues. I have reposted this for you in the correct place [here](https://github.com/Windower/Issues/issues?page=1&state=open).
