### ISSUE TITLE
todays update

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#654]
just to try help iron out todays broken stuff

error message im currently getting for GS is:
equip_processing.lua:214: attempt to index field '?' (a nil value)
im sure thers possibly more but this is the first error and i dont know how to fix it to look for more.
hope it helps

**Comment by kbeezie** [comment]
Over at the GearSwap help thread (where that support should usually go), he mentioned it probably won't be fixed until LUACore is fixed.

**Comment by Byrth** [comment]
This is fixed now.
