### ISSUE TITLE
Command to change mob name by ID

### ISSUE THREAD

**Issue by Markalike** [Windower/Lua#68]
This would be helpful as it would allow you to differentiate between mobs of same time and allow you to do stuff like:

[Goblin Butcher (S)]  = sleeping? or something similar

It would show you which debuffs mob has and whatnot!

Overall I think it would be a very unique feature to have if possible.

**Comment by Byrth** [comment]
This is a great idea, but I can't tell what debuff the monster has from a programming perspective until the "Action Packet" is exposed. For instance, if you're fighting two Goblin Butchers at the same time and someone sleeps one of them, Lua currently has no way to tell which of the two was slept.

**Comment by Markalike** [comment]
Its more so so you can change the name for you're own purposes, as in like I cast sleep on a mob, I can just use the target I have to change it. I did it before with my own FFace plugin and I thought it was a great help but I can see what you mean as well

**Comment by aureus1** [comment]
added set_mob_name
https://github.com/Windower/Lua/wiki/Interface-Functions-:-Output
