### ISSUE TITLE
Timers from C++ to Lua

### ISSUE THREAD

**Issue by Markalike** [Windower/Lua#69]
I am not so good with Lua but I am familiar with C++ and Python and what I had in the past for timers with Python was something like, OnTick() -> call to Python, this ran like every .01 seconds which allow me to make timers in Python without the use of addition threads cause you dont need to use a Sleep() function. I tried to look for something like this via google... but  I could not locate any thread safe timers. This would be most useful for rerunning things outside of events on a timing basis. I think this would definetly help for running addons that dont solely rely on events to do things, AKA Tparty in Lua, for every tick or however often you want, check each players TP and then update.

Thankyou for taking the time to read this and all the effort you are putting into it!

**Comment by Markalike** [comment]
Just to follow up, an easy but effective fix could be to make a new event like.. event_tick(int tick_count) and just have it fire every .1 seconds or something like that. It would be a simple but effective fix and would be very useful!

**Comment by z16** [comment]
While it's not a fix, this can currently be simulated by using the `send_command` function as follows:

``` lua
-- Addon test
function bla()
    -- Do stuff
    send_command('wait 0.1; lua i test bla')
end
```

**Comment by z16** [comment]
Added the `prerender` event for that:

``` lua
windower.register_event('prerender', function()
    print('Spamming the console!')
end)
```
