### ISSUE TITLE
Highlight has been generating a bunch of error messages on logoff

### ISSUE THREAD

**Issue by Linsaran** [Windower/Lua#750]
I get a bunch of message spam of the format

"Could not safely merge values for 'global/allydmg', string expected (default: ?), got number (0)"

The 'global/something' is different in every line, the ? after default is actually inside a box, and makes me think of a UTF character inserted into a program that doesn't support the character set. and the got number (0) can have a variety of different numbers in them for each line.  

I don't know enough about lua to know what's causing this, but it's a bit annoying to have pop up every time I switch mules. I like the functionality of highlight, so hopefully this is something that can be fixed.

**Comment by Byrth** [comment]
I believe this was solved months ago (and I could personally never replicate it), so I'm going to close the issue. Please reopen it and let us know if it was not.
