### ISSUE TITLE
GearSwap bug with some spells

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#757]
some spells/abilitys are not recognized by gearswap
i found this out by putting(below) in to my lua on precast/midcast/aftercast
print(spell.name)
print(spell.name)

these are the ones i have found so far
Healing Waltz
Curing Waltz

but whats funny is that Curing Waltz II and Curing Waltz III did work

**Comment by z16** [comment]
For future reference, these should go to the addon's own bug tracker (you can find it by clicking on `Report A Bug` for GearSwap in the Launcher). But in this case, this is actually a Lua issue, so it can remain here, GS just happens to be affected by it. We should fix it soon.

**Comment by smd111** [comment]
actualy its not its the function built in to gearswap that checks if you can use the spell
it needs a way to disable it

**Comment by z16** [comment]
I thought this was a resources issue?

**Comment by smd111** [comment]
ok i figured it out spells/ja's/ws's that you are not capable of using eather because of gear or jobs not being correct you need to use this function filtered_action(spell)

but this post was because gearswap couldn't tell all the spells/ja's/ws's that subjobs could use 

not sure if thats fixed or not(subjobs skills)
 i will test and let you know if i find anymore that dont work
