### ISSUE TITLE
Obiaway load error

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#760]
this is what it says in the windower command log

Failed to load obiaway. Lua error (1: .../Program Files/Windower//addons/obiaway/obiaway.lua:79: attempt to

yes that is ware it gets cut off

**Comment by nitrous24** [comment]
I believe this was an error because of the Thunder element. That has recently been changed to be lightning instead. I have fixed that please let me know if you still get the error

**Comment by smd111** [comment]
yes im still getting it

**Comment by nitrous24** [comment]
Have you updated since i said that? relaunched client i mean? Also, without
the end of the error it's hard to tell what exactly the error is. all line
70 is is a function call.

**Comment by smd111** [comment]
the best i can get is 
Failed to load obiaway. Lua error (1): .../Program Files/Windower//addons/obiaway/obiaway.lua:79: attempt to index global 'remove_unneeded_obis'

to get that i had to change the font in the console but i cant make it any smaller to bad there is no wordwrap

**Comment by nitrous24** [comment]
oooh ok
lemme try somethin

**Comment by nitrous24** [comment]
ok i assumed you were on live windower version rather than dev.. Try it again now

**Comment by smd111** [comment]
i am on the live version not the dev
but it worked

but now im getting
obiaway:lua error(runtime) - ..obiaway.lua:157 attempt to index field 'weathers' (a nil valu

**Comment by nitrous24** [comment]
good to know. it was trying to reference a function that hadn't been
defined yet lol.

**Comment by smd111** [comment]
i added some more info

**Comment by nitrous24** [comment]
? I thought i fixed it.. did i not? you said it worked?

**Comment by smd111** [comment]
it loaded then i just got another error when weather changed

**Comment by nitrous24** [comment]
What was that error?

**Comment by smd111** [comment]
obiaway:lua error(runtime) - ..obiaway.lua:157 attempt to index field 'weathers' (a nil valu

**Comment by nitrous24** [comment]
ok gimme a few to look into it. Sorry for all the issues, not my addon so it can take me a few min to figure this out lol

**Comment by smd111** [comment]
no problem im just trying to help with any errors i find

**Comment by nitrous24** [comment]
k try again just pushed another one

**Comment by smd111** [comment]
so far it works but i think the resorces need to be updated so the spells have the correct elements
i.e. thunder = lightning and any others that need it

**Comment by nitrous24** [comment]
They should all be working right already. Spell elements and day/weather have been changed to lightning rather than thunder for a while. This addon just slipped through it would seem.

**Comment by smd111** [comment]
i just ran //updateresources and here is an example
Thundaga II" german="Donnerga II" french="OmniFoudre II" japanese="サンダガII" type="BlackMagic" element="Thunder"  <-- still uses thunder

unless thay mad a fix for it in lua but i dont know

**Comment by nitrous24** [comment]
Oh well i'll ask about that. At least the addon works now. I'm going to close this issue.
