### ISSUE TITLE
GearSwap bug Unable to execute command

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#762]
i got this with my job as SAM99/DNC49 when i tried to use Healing Waltz with gearswap in debug mode

GearSwap (Debug Mode): Unable to execute command. You do not have access to that ability (Healing Waltz)
GearSwap (Debug Mode): Entering filtered_action

the strange part is that even as a subjob DNC can use the ability healing waltz as long as dnc's level is 35 or higher

**Comment by Byrth** [comment]
Does this issue still exist? I am unable to replicate it on the -dev version.

**Comment by smd111** [comment]
im waiting on a new controller so i can test right now i should be able to in the next few days
