### ISSUE TITLE
OhShi and VW messages

### ISSUE THREAD

**Issue by quedari** [Windower/Lua#765]
Voidwatch hints, light levels, and proc messages are getting stuck on screen. Sometimes it's just 2-3 and sometimes I have to unload it because i have about 20 covering up my screen. They usually stay until I reload Ohshi.

**Comment by nitrous24** [comment]
i added a clear function just for this. I have no clue what's causing it to stay. When this happens just type //ohshi clear and the textbox/tracking table will be cleared
