### ISSUE TITLE
Send dropping quotation marks when an apostrophe is present in item name

### ISSUE THREAD

**Issue by Ivaar** [Windower/Lua#766]
As the title says when trying /item "stalwart's tonic" <me> it comes out as /item stalwart's tonic <me>

**Comment by z16** [comment]
This is not a Send issue, it's a Windower "feature". Any quotes you enter through the chat log will be parsed out of it and the thing between the quotes parsed as one token. I'll see if I can implement a way to avoid that.

**Comment by Ivaar** [comment]
/item "dusty wing" <me> or anything else without ' in name seems to pass fine through with the quotes but thank you for looking into it

**Comment by z16** [comment]
The quotes always get removed, but it may still work that way. The game allows you to use single quotes instead of double quotes for spells, I assume it also works for items, so if there is only one single quote it will complain.

**Comment by Ivaar** [comment]
Alright I'll just tough it out till a workaround comes, thanks again for your responses.

**Comment by z16** [comment]
This has been added to the dev version of LuaCore and should be pushed live soon.

**Comment by nitrous24** [comment]
i actually had made send not require quotes around item text

**Comment by nitrous24** [comment]
local st,en,item,tar = string.find(msg,'/item ([%w%s]+) <(%w+)>')
    if item ~= nil then
        msg = '/item "'..item..'" <'..tar..'>'
    end

^ puts quotes around item text

**Comment by Ivaar** [comment]
@z16 Awesome dude.
@nitrous24 yeah i saw that and tried it but send will still drop the quotes or not add the quotes if an item has an apostrophe in the name

**Comment by nitrous24** [comment]
yea i didn't read that it was about specific items, my bad. Apostrophes aren't checked for
