### ISSUE TITLE
Feature Request: X Y Z and Angles of the camera

### ISSUE THREAD

**Issue by Markalike** [Windower/Lua#77]
I do not know if it is possible or not, but having access to these would allow interactive overlays with objects in game somewhat! Simple but idea would be "Area Tagging" or something like that... Say you go to area in FFXI, if you incorporate the C++ to Lua timers you could go to like.. area in Abyssea or New areas for example and see on the ground or the air W/E a text overlay that can get smallers or bigger depending on how close you are to it. With the X Y Z and angles of the camera this could make it so overlay goes and comes as u target the tagged area with you're point of view! 

This kinda idea would add a awesome aspect to FFXI!, could maybe do /tag <comment> or something like that and maybe have it upload those coordinates and you're message to server. I do not know how realistic this could be cause Lua can be decoded on the spot and people could probably mess with it. I am not a Lua expert but I am good with 3D coordinates and working with vectors! Please let me know you're input on this and if you think it could be abuse proof.

Only other option for something like this would be adding it into C++ and directly loading with windower and/or FFace to avoid abuse. Looking forward to you're feedback!

**Comment by alphaONE2** [comment]
Added get_camera()
