### ISSUE TITLE
Plasmon - stopped working and no way to make it work again

### ISSUE THREAD

**Issue by Sechs** [Windower/Lua#778]
![2a0aoav](https://cloud.githubusercontent.com/assets/4262767/2786573/2231c09e-cb79-11e3-9d87-86d1853d0bcb.png)

This is the behaviour I'm getting out of Plasmon for quite a while.
Resetting the addon (deleting and redownloading it with new settings.xml) doesn't seem to fix it.
Deleting and redownloading the addons/libs folder, as suggested by the addon original author, didn't fix it either.
When you load the addon some parts of it seem to be working when I test commands, others generate an error (398 if I recall?) saying there's something wrong with chat.lua.

**Comment by Byrth** [comment]
Try changing line 291 to: 
`windower.register_event('zone change', stop_tracking:cond(function(id) return (id == 271 or id == 264) and track end))`

I pushed that change to -dev, which should go live on Monday. The problem you were experiencing likely only affected Cirdas [U]?

**Comment by Sechs** [comment]
Pretty sure it was affecting the zones in Yorcia as well, been keeping the addon turned off lately so I'm not 100% sure.
The strange part is that other people seem (unless they're lying/misunderstanding what I ask) to be able to use Plasmon addon just fine, which led me to think it was somehow an issue local-side in my Windower folder, but as mentioned in the first post I think I pretty much tried everything I could as far as resetting stuff is concerned.

Of course, that is IF it's true that other people use it fine. If the addon is instead broken for everyone then it's a whole different story of course.

**Comment by Byrth** [comment]
Okay, try this then:
`windower.register_event('zone change', stop_tracking:cond(function(_,id) return (id == 271 or id == 264) and track end))`

**Comment by Sechs** [comment]
Modified that line in the Lua and will try it later when I enter Delve, will update here asap.
There also seems to be an error concerning the command //plasmon Help
Atm it doesn't work (used to work long ago), returns an error about line 398 concerning "attempt to index global 'chat' value (a nil value)"

**Comment by z16** [comment]
That's fixed on the dev client.

**Comment by Sechs** [comment]
Entered now on Cirdas_U with the line Byrth gave me, and it's working like a charm.
Makes me wonder how the hell could this work for other people if there was a broken line in there?
/shrugs

Should test Yorcia_U later.

**Comment by Byrth** [comment]
Okay, this is all fixed then. Going to close the issue.

-dev should be merged live today, which will fix your chat library issue.
