### ISSUE TITLE
Plasmon - Yorcia Weald [U]

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#780]
This zone apparently does not work with Plasmon at the moment.

**Comment by Sechs** [comment]
Doesn't load at all.
Plasmon was created before that zone was added and Zohno stopped updating the addon before.
I guess there is some check somewhere or some line to add to make so the addon works even in Yorcia_U zones.

**Comment by Byrth** [comment]
Believe it or not, this problem is due to the color of the Yorcia Weald [U] "You now permeate the mists surrounding the fracture" message. I basically just have to go record that message and it should work.

**Comment by Sechs** [comment]
Any news on the development of this thing?
Don't wanna sound demanding, just curious to see if it's been working on, it will in the future, or if I have to give up the idea :D

**Comment by joshk6656** [comment]
I made the changes on -dev, could you test? If you don't use dev you can manually download it @ 

https://github.com/Windower/Lua/blob/4.1-dev/addons/plasmon/plasmon.lua

**Comment by joshk6656** [comment]
I actually pushed this to live as well. Please close if its fixed.

**Comment by Sechs** [comment]
Not home atm, will do my best but T2 Delve shout runs aren't very common on my server, so I might have to wait for next LS event (sunday)

**Comment by Sechs** [comment]
Can confirm it works 100%! Thanks guys ;)

**Comment by Sechs** [comment]
Only strange thing I never noticed before, it said "37,5" on the "number of mobs killed" field.
Strange... what's a 0.5 monster lol?

**Comment by Byrth** [comment]
It's probably caused by killing a monster that give Plasm in an amount that's not divisible by 50 (like, 75 Plasm). Zohno uses this code: https://gist.github.com/Byrth/e91ae4c043a712eca541

So he's accommodating multiple monsters being killed at the same time (which lumps their message together) by assuming that anything that isn't a /500, /750, or /10000 kill is a multiple-monster kill. If there is something that he didn't account for (remember, he quit after Delve 1), then it'll end up throwing off the count.

That being said, if the issue is solved then I'm going to close this. Feel free to open another issue if you figure out how you're getting half a monster (75 Plasm per kill or something).
