### ISSUE TITLE
Lua Resources

### ISSUE THREAD

**Issue by Kinematics** [Windower/Lua#787]
There are now two directories containing lua resources: libs/res and libs/resources.  Reason for this duplication is unknown.

Further, there are differences in the resources provided within each directory.  Within abilities.lua, index values 381 to 400 are completely different between the two.  The /res/ version (which appears to be the one currently in use) does not include Chocobo Jig II and further, but instead includes Finishing Move 1-5, etc, which I would actually expect to be in the buffs.lua resource file.

**Comment by joshk6656** [comment]
I'm pretty sure the duplicate resources are due to the web site being down and not being able to pull resources from windower.net, so we added them to the github repo. 

That might have been a mistake when copying them back into libs.

**Comment by z16** [comment]
Yeah, I'll fix it in a second.

**Comment by z16** [comment]
Done.

**Comment by z16** [comment]
To further clarify: The `Windower/addon/libs/resources/` folder is a relic from our previous structure. It's no longer used and can be deleted, and as soon as our domain name is back up, `Windower/addons/libs/res/` can also be deleted, because then the resources will be in `Windower/res/`
