### ISSUE TITLE
Guarding vs Guard

### ISSUE THREAD

**Issue by mujihina** [Windower/Lua#805]
- Game uses 'Guarding'
- the table in windower.ffxi.get_player().skills uses 'guarding'
- res/skills uses 'Guard'.

**Comment by z16** [comment]
This will shortly be adjusted to [this](https://gist.github.com/IryokuChevalier/630cc45a0d4ebda0004a).

**Comment by mujihina** [comment]
does the file you list there  mean you are dropping the 'category' field? I'm actually using that in one of my addons.

**Comment by alphaONE2** [comment]
No, it's just the strings that are changing, or being added.

**Comment by z16** [comment]
For now just adjusted `windower.ffxi.get_player().skill`, we still need to see how to implement the skill changes so it doesn't mess up peoples' scripts.
