### ISSUE TITLE
Treasury bug

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#807]
when you die and go to your home point it randomly drops an item from your inventory

when autodrop is enabled

this is on the non dev version

**Comment by z16** [comment]
I pushed a fix that could cause it, but to verify: do you have any items in an inventory bag other than your main inventory that were on your pass list? Such as crystals maybe?

**Comment by smd111** [comment]
yes 

and the command to clear i.e.
//Treasury pass clear
does not work

**Comment by z16** [comment]
Ok, fixed that as well.
