### ISSUE TITLE
Treasury bug

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#813]
if Treasury auto loads it will not switch in the current <playername>  pass lot list when you log in

the only thig i can do to get it to load it is to use this command
lua reload Treasury after i log in my char

**Comment by z16** [comment]
This should be fixed on dev, I'll push it live after I've monitored the changes for a bit.

**Comment by smd111** [comment]
ok thx when it gets to nondev ill post if it works or not

**Comment by z16** [comment]
It's live now.
