### ISSUE TITLE
level up event

### ISSUE THREAD

**Issue by mujihina** [Windower/Lua#815]
Whenever you change jobs or subs, if the new job or new subjob is level 1, it triggers a 'level up' event followed by a 'job change' event. Switching to jobs or subjobs higher than level 1 only seems to trigger a 'job change' event.
  IMO, changing jobs or subs should not generate 'level up' events at all.

**Comment by mujihina** [comment]
btw....there's also a 'level up' event, shortly after a 'login' event (if your char is level 1).  
IMO, that should not happen either.

**Comment by z16** [comment]
Yes, because it sets the default level to `0`, so when you log in as level `1` it thinks you leveled up. I'll also fix that todya.

**Comment by mujihina** [comment]
This was only partially fixed. 
- If your main level is 1, and you change your sub (regardless of level) it still generates a 'level up'
- If your main level > 1, and you change to a lvl 1 sub, it no longer sends a 'level up'.

Untested (I don't have any jobs that close to verify)
- if I change from a level N job, to a level (N+1) job, will it generate a 'level up'?

**Comment by z16** [comment]
It should according to our current API. I'll see about making this more stable.

**Comment by mujihina** [comment]
It seems to work as intended now, btw.

**Comment by z16** [comment]
It shouldn't, nothing has changed. I'm pretty sure it's still broken, at least in some way.

**Comment by mujihina** [comment]
I spoke prematurely. What works as intended is that it no longer triggers an unnecessary 'level up' event....however, when you DO level up, it does NOT trigger the event.

**Comment by Nifim** [comment]
Fixed by this PR https://github.com/Windower/Plugins/pull/36
