### ISSUE TITLE
Timers Plugin

### ISSUE THREAD

**Issue by Greythorn** [Windower/Lua#824]
Just a heads up:

Timers plugin will not display the correct time remaining when using "extended [buff]" equipment from the mog wardrobe.

Example: 
Bard extended song duration equipment.  
Ballads last 3:06 when pulling from inventory and Timers plugin shows 3:06 mins time remaining.
Ballads last 3:06 when pulling from wardrobe and Timers plugin shows 2:00 mins time remaining.

**Comment by z16** [comment]
This should be fixed.

**Comment by z16** [comment]
Also, this is the Lua tracker, next time report non-Lua related issues [here](https://github.com/Windower/Issues/issues) please.
