### ISSUE TITLE
Autojoin colors.lua error message

### ISSUE THREAD

**Issue by Disserrna** [Windower/Lua#84]
Whenever I attempt to load autojoin I receive the following error:

Load error: Program files (x86)\Windower4\addons\autojoin\colors.lua:13: attempt to index a nil value

**Comment by z16** [comment]
That happens because either it parsed the data incorrectly, or if the file it's trying to parse doesn't exist. Since it parses correctly for me I have to ask: do you have ffxidata.json in your Windower/addons/libs/ folder?

https://github.com/Windower/Lua/archive/master.zip

If you click that, you will download the entire folder. Extract that somewhere (preferably not your Windower folder, unless you want every addon) then go to Lua-master/addons/libs/ and copy everything in there to Windower/addons/libs/ . Let me know if that helps.

**Comment by NathanZwache** [comment]
How the heck do you edit the settings file? Keep getting "Could not safely merge values: [1-10] nil" Getting very irritated.... ><

**Comment by z16** [comment]
Can you show me your settings file? That error appears when you put values in a setting that don't belong there, like strings where numbers are expected, or something like that.

**Comment by NathanZwache** [comment]
Well, I'm using the ingame commands //aj whitelist add name, so it should work...but it doesn't.
http://pastebin.com/TxKWq1tH

**Comment by z16** [comment]
That's working as intended. //aj save saves settings globally, for all characters, which is what it did there (as you can see, it moved the whitelist from <volgin> to <global>). If you don't want it to save globally, just don't do anything, it'll save settings on a per-character basis every time you modify it with an //aj command.

Or is it something else you wanted to do?

**Comment by NathanZwache** [comment]
I don't think you understand the problem.
It flat out does not work. If I save it globally or not, it does not work. I understand global and local settings. Again, either way, it throws "Could not safely merge values: [1-10] nil". If I unload it and reload it, it throws the exception. If I log out and log in, it throws the exception. If I load everything by hand every time I log in by typing out //aj whitelist add name for every member of my LS that I need invites from, it will work, but frankly I'd rather not use it at all if I have to go out of my way to type that out for every character every time I log in. 
![Untitled](https://f.cloud.github.com/assets/4168997/398125/5f11585e-a851-11e2-94d5-b4fe4fea82e8.png)

**Comment by NathanZwache** [comment]
After I unload/reload or restart POL, it always throws that. It does back to default.

**Comment by z16** [comment]
Hm, this shouldn't be happening. Can you confirm that you have the latest version of the addons/libs folder? Try deleting everything in that folder, then run the launcher, it should re-download up-to-date files for all of them. Alternatively, download them from GitHub (click "Code" above, then the cloud with the "ZIP" next to it, and extract the entire libs folder into your Windower/addon/libs folder). Let me know if the error still persists after that.

By the way, for the time being you can use the shorthand syntax: //aj w + foo bar baz < This will add "Foo", "Bar" and "Baz" to the whitelist. You can macro it as well (/con aj w + <list of names>).

**Comment by NathanZwache** [comment]
Downloaded from Lua_Master ZIP file from the Code tab like you said. Same problem. 
![img_20130418_145303](https://f.cloud.github.com/assets/4168997/398484/60e87b1e-a859-11e2-9986-499ebbac159b.png)

**Comment by z16** [comment]
Can you paste your entire settings XML [here](http://gist.github.com/)? At the point where it doesn't work to load it anymore, so I can try to reproduce the problem.

**Comment by NathanZwache** [comment]
https://gist.github.com/NathanZwache/5415482

**Comment by NathanZwache** [comment]
I gave you everything I did. Libs updated, autojoin redownloaded. There are comments at the bottom of whatever I did to get to the point of where I was at.

**Comment by z16** [comment]
Thanks, I can reproduce the error now. I'll have it fixed soon.

**Comment by z16** [comment]
Fixed it. You need to restart the launcher so it downloads the latest _config.lua_, then it should work. Sorry for this, I forgot to take obsolete code out when I restructured the file.
