### ISSUE TITLE
Need access to Pet information

### ISSUE THREAD

**Issue by Byrth** [Windower/Lua#85]
Unless I'm missing something, we currently have no way to access Pet information, but windower obviously knows how to access it because we have the PetTP plugin. Having a get_pet() function would be very useful.  

Thanks!

**Comment by alphaONE2** [comment]
this is slightly confusing because of the name of the field. what you're looking for is pet_index in the mob table. you should be able to use that as an argument to get_mob_by_target_id to get any player's pet.

**Comment by alphaONE2** [comment]
ok we're going to rename pet_index to pet_target_id for consistency.

**Comment by z16** [comment]
Just for future reference, both `pet_index` and `pet_target_id` are currently implemented, with `pet_target_id` being deprecated (same as all other `target_id` references).
