### ISSUE TITLE
GearSwap on JP Client

### ISSUE THREAD

**Issue by Sygloon** [Windower/Lua#855]
Hi there
The Japanese client, for items, magic, and abilities that does not include spaces, you do not need to be enclosed in double quotes (""). It does not process successfully because you are passing to the client remains utf8.
Configuration example of a macro
English client :/ ma "xxxxx" <me>
Japanese client :/ ma xxxxx <me>
must be passed to the client by encoding to Shift_JIS in xxxxx, there may be a need to determine the language of the client.

**Comment by Byrth** [comment]
Hello Sygloon!

I made changes to GearSwap on the -dev client last night to fix a bug and I think it will also fix this problem. Could you please try using this version of triggers.lua and let me know if it works?
https://www.dropbox.com/s/hjxpm8ocs58cul2/triggers.lua

If so, I can push it live in a few hours.
- Byrth

**Comment by Sygloon** [comment]
Hello Byrth

I was able to verify that it works well. I would like to thank the quick response.

In addition, it may be modified but, targ seems to have become nil at line 51 of targets.lua.

49 | local mob_array = windower.ffxi.get_mob_array ()
50 | 　for i, v in pairs (mob_array) do
51 | 　　if v.name: lower () == targ: lower () and not v.is_npc then
52 | 　　spelltarget = target_complete (v)
53 | 　　spelltarget.raw = targ
54 | 　　return targ, spelltarget
55 | 　end
56 | end

**Comment by Byrth** [comment]
Ah, yes. You need another version of targets.lua:
https://www.dropbox.com/s/0zwoeiy7aabo7ub/targets.lua

You may also want to download the triggers.lua file again. I changed it in the last 30 minutes.

I will push this live tonight.

**Comment by Byrth** [comment]
It is all live now, actually. If you re-run the launcher, it should download the right version for you.

**Comment by amatsuno** [comment]
Hello I'm japanese.
Thank you for support JP client.

but I found some problems. please check it.

1.SCH spells with 'Addendum: *' does not work.(For example Reraise III)
may be BLU has same problems.

this is because buffactive checked in English.

function filter_pretarget() in helper_functions.lua,
buffactive['Addendum: White']) and buffactive['Addendum: Black']) dose not work correctly in JP client.

when modifying to buffactive[res.buffs[401][language]] and 
buffactive[res.buffs[402][language]], they're working correcty.

2./ma "XXX" <st*> does not work.
this is because XXX encoded by UTF-8 in triggers.lua.

when modifying following code in triggers.lua, working correctly.

```
storedcommand = command..' "'..r_line[language]..'" '
```

to

```
if language == 'japanese' then
    storedcommand = command..' "'..windower.to_shift_jis(r_line[language])..'" '
else
    storedcommand = command..' "'..r_line[language]..'" '
end
```

sorry if funny english.

**Comment by joshk6656** [comment]
These other instances may have the same issue.

file - line number - string.
helper_functions.lua    -   5 matches in 826 lines.
helper_functions.lua    447         elseif player.main_job == 'SCH' and ((addendum_white[spell.id] and not buffactive['Addendum: White']) or
helper_functions.lua    448             (addendum_black[spell.id] and not buffactive['Addendum: Black'])) and not (spell_jobs[player.sub_job_id]
helper_functions.lua    458         elseif player.sub_job == 'SCH' and ((addendum_white[spell.id] and not buffactive['Addendum: White']) or
helper_functions.lua    459             (addendum_black[spell.id] and not buffactive['Addendum: Black'])) and not (spell_jobs[player.main_job_id]
helper_functions.lua    470             ((buffactive['Unbridled Learning'] or buffactive['Unbridled Wisdom']) and unbridled_learning_set[spell.english])) and not
refresh.lua -   12 matches in 582 lines.
refresh.lua 110         buffactive=buffactive,
refresh.lua 172 ---- Further converts player.buffs to buffactive.
refresh.lua 228     -- Assign player.inventory to be keyed to item.inventory[i][language] and to have a value of count, similar to buffactive
refresh.lua 379     if buffactive.voidstorm then
refresh.lua 382     elseif buffactive.aurorastorm then
refresh.lua 385     elseif buffactive.firestorm then
refresh.lua 388     elseif buffactive.sandstorm then
refresh.lua 391     elseif buffactive.rainstorm then
refresh.lua 394     elseif buffactive.windstorm then
refresh.lua 397     elseif buffactive.hailstorm then
refresh.lua 400     elseif buffactive.thunderstorm then
refresh.lua 497     table.reassign(buffactive,buffarr)
statics.lua -   1 match in 401 lines.
statics.lua 287 buffactive = make_user_table()

**Comment by Byrth** [comment]
Ah, thanks! I made buffactive include ID numbers recently, so I will switch it to using numbers instead of strings tonight.

**Comment by Byrth** [comment]
Okay, I pushed this live. I think it will work now.
https://github.com/Windower/Lua/pull/866

**Comment by Sygloon** [comment]
Hello Byrth

I found another problem.
There is a macro that does not work.

Macro :`/ magic パラナ <stal>` パラナ is Paralyna
It does not move
When you run the macro to ON debugmode, the following message appears.
GearSwap (Debug Mode): Unable to create a packet for this command or action canceled (. Magic Parana <slal>)

Phenomenon
1. Macro execution
Message display of 2. Above
3. Sub target cursor display
To select and execute 4. Target
The display will indicate ">> `/ magic" xxxxx <stal> "`
5. Chat window, magic is not cast
xxxx (because perhaps, magic name is left over UTF8) you are garbled

The workaround
`/ target <stal>`
`/ magic パラナ <lastst>`

**Comment by Sygloon** [comment]
sorry, 
It was a notation misleading. 

Macro definition
`/ magic パラナ <stal>`
Here, English name of パラナ is Paralyna

**Comment by Byrth** [comment]
Hmm.... on the NA client, you would use:
`/ma Paralyna <st>`

Does the JP client work without `<st>`?

Edit: Nevermind, I see `<stal>` when I edit your post
Edit2: SquareEnix' implementation of `<st>` commands is very confusing. This might take me an hour or two.

**Comment by Byrth** [comment]
Okay, now it should be fixed. This was also an issue for the NA version.

**Comment by Byrth** [comment]
The change fixed the problem as far as I can see, so I am going to close this issue.

If you find more problems in gearswap, please open issues here:
https://github.com/Byrth/Lua/issues?direction=desc&sort=created&state=open
