### ISSUE TITLE
Buff_change function

### ISSUE THREAD

**Issue by sebyg666** [Windower/Lua#898]
GEARSWAP

this seems to have broken, i even added print messages to see whever the function gets entred and it never enters it. or did the function change.
i see in the variables.xls that the funstion is written buff_change(name,gain),
i use motentons files and his has buff_change(buff,gain), im assuming that doesnt make a difference, i tried changing it and that doesnt help either

i did some more testing, went right into the gearswap.lua and added a print line for the events 
windower.register_event('gain buff',function(buff_id)
and its lose buff version also, and it seems to only parse it occasionally, its behaving really wierdly.
Im a bit lost

bit more info, im using buffs on bard, piannissimo and tenuto, casting marches and ballads with up to 3 songs, I cnt seem to work out a patern as to when it stops parssing the buffs.

**Comment by Byrth** [comment]
Rerun the launcher. Arcon reverted it hours ago.

**Comment by sebyg666** [comment]
thanks bud
