### ISSUE TITLE
BuffDuration: not running on Japanese client.

### ISSUE THREAD

**Issue by Zebrax** [Windower/Lua#92]
Thank you for great capability. I tried this on Japanese client. However it does not work propery. (Does not appeared timers by any enhancing magic.)

In the code, bad point in following function:
- event_gain_status

At line 128, creating the timer by name. I think 'name' is various name (i.e. English, Japanese, French and Germany) by client. On the English client, probably it can create a timer propery because name is written in English. (e.g. "Shell") On Japanese client, strings of the name is "シェル". Thus it cannot create a timer propery. 

Current: createTimer(tostring(name))
Correct: createTimer(tostring(buffname))
- event_lose_status

There is a wrong point like previous one. Following is an example of amendment.

> function event_lose_status(id,name)
>   for i in ipairs(lines) do
>       x = i
>       str = lines[x]
>       if str ~= nil then
>           str=tostring(str)
>           a,b,c,d = string.find(str,'&lt;b id="(%w+)" duration="(%w+)"')
>           if c ~= nil then
>               buffid = c
>               duration = d
>               buffn = tostring(str:split('&gt;',2)[2]:split('&lt;',2)[1])
>               if tonumber(buffid) == tonumber(id) then
>                   deleteTimer(1,buffn)
>                   send_ipc_message(buffn..' '..player['name']..' delete')
>                   break
>               end
>           end
>       end
>   end
> end

Could you consider to correct this localization issue?

At the end, this amendment was proposed by a user who loves Windower in Japan. I posted this on behalf of him. ">>36さん ありがとう"

**Comment by sebyg666** [comment]
The windower devs are working on a new release to timers that will buff timers as standard. As timers, im sure , conciders japanses, the buff timers will most probably work on the japanese client. Please allow a little while for them to release it. As soon as this update is released, i will be asking for buffduration to be deleted.

**Comment by Zebrax** [comment]
Thanks for your reply and interesting vision of Timers! Looking forward coming releases. =D

**Comment by Ihellmasker** [comment]
Yes, Timers, the Windower Plugin, supports multiple languages properly, or at least, it will in the next version :).
