### ISSUE TITLE
Addon to support WindowerHelper input from applications built for windower 3.4

### ISSUE THREAD

**Issue by Ivaar** [Windower/Lua#930]
Is this possible? Would anyone willing to undertake this?

**Comment by alphaONE2** [comment]
Support for the Windower 3.x version of WindowerHelper was added to Windower 4 shortly after release. Additionally, the version 4 DLL is binary compatible, so any application that is dynamically linked with WindowerHelper can just have the new DLL dropped in and it should work.

**Comment by Ivaar** [comment]
I'm sorry, where can i find the DLL?

**Comment by z16** [comment]
@Ivaar https://github.com/Windower/Helper

**Comment by Ivaar** [comment]
I'm getting alot of errors when I try to compile, not sure what i am doing wrong. if anyone can help me it would be great.

**Comment by Ivaar** [comment]
Sorry i was confused, on Ashita you can use a windowerhelper plugin to allow a certain fface program to process and execute // commands that used to work on windower 3.4. While I don't know what changed between windower 3.4 and windower 4 that disallows this programs functionality, which remains working on ashita thru the aforementioned plugin, i would love to see some kind of workaround if possible. Thank you for your time and efforts to the windower community.

**Comment by alphaONE2** [comment]
Sorry for the confusion, turns out there is a problem on our end. This is still the wrong issue tracker for this though. I've opened Windower/Issues#548 to track this.
