### ISSUE TITLE
itemizer

### ISSUE THREAD

**Issue by theblackdeath** [Windower/Lua#935]
when i load itemizer it locks me from selecting utsusemi ni and ich from the list of spells i can cast. also if i make a macro amd use that it spams utsusemi non stop till i shut itemizer off

**Comment by Antinym** [comment]
I was not able to replicate your problem.  If you haven't done so already disable all addons/plugins from the launcher.  Then load itemizer after you login and try to cast utsusemi.  If that works try editing your ../itemizer/data/settings.xml and set this: `<AutoNinjaTools>false</AutoNinjaTools>`.  Reload the game with all your usual plugins/addons and see if the problem still occurs.

**Comment by theblackdeath** [comment]
the <AutoNinjaTools>false</AutoNinjaTools> worked. ill be sure to tell my
friends that are having the problem to how to fix it

**Comment by z16** [comment]
That's not technically a fix. It just disables one of its functions. It _should_ still work even with that to true, but I cannot replicate your issue.

**Comment by theblackdeath** [comment]
if you would like to teamviewer in i can show you

**Comment by Byrth** [comment]
This was actually a GearSwap or Shortcuts issue interacting with Itemizer. Though I think this particular issue has already been solved, I've opened an issue for myself here:
https://github.com/Byrth/Lua/issues/346
