### ISSUE TITLE
Probable memory corruption within Lua interpreter

### ISSUE THREAD

**Issue by jerryhebert** [Windower/Lua#94]
I discovered a bug that isn't possible in bare Lua while calling Lua code within the event model. Rather than trying to describe it in English, I'll show examples of code that works and code that doesn't.

In all cases below, when I say "breaks" or "doesn't work" below, I mean I get this error:
`...\tablebug.lua:28: bad argument #1 to 'write' (string expected, got nil)`

This breaks. It just writes out t[6] whenever we get an action. This will still break if the write() is called from event_status_change(), event_incoming_text(), event_target_change() and presumably most others.

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd',
    [5] = 'e',
    [6] = 'f'
}

function event_action ()
    write(t[6])
end
```

It still breaks if I remove one element:

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd',
    [5] = 'e'
}

function event_action ()
    write(t[5])
end
```

If I remove one more element, it's fine. o.o

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd'
}

function event_action ()
    write(t[4])
end
```

Removing 'local' on the declaration doesn't fix it, but moving it into the event handler does. This works, regardless of 'local' or not on the internal and external declarations. o.o

```
function event_target_change ()
    local t = {
        [1] = 'a',
        [2] = 'b',
        [3] = 'c',
        [4] = 'd',
        [5] = 'e'
    }
    write(t[5])
end
```

This works. It's fine if called from event_load()

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd',
    [5] = 'e',
    [6] = 'f'
}

function event_load ()
    write(t[6])
end
```

It's also fine if event_load() calls another function:

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd',
    [5] = 'e',
    [6] = 'f'
}

function foo()
    write(t[6])
end

function event_load ()
    foo()
end
```

This version works. So some time after event_load() it's still okay.

```
local t = {
    [1] = 'a',
    [2] = 'b',
    [3] = 'c',
    [4] = 'd',
    [5] = 'e',
    [6] = 'f'
}

function foo()
    write(t[6])
end

function event_load ()
    send_command('wait 3; lua i tablebug foo')
end
```

Anyway, hopefully that spells it out. Something is amiss. I wonder if it's possible to just try a different Lua interpreter as a quick smoke screen to see if it's related to the particular one that we're using?

**Comment by jerryhebert** [comment]
I forgot to mention that this error isn't present in my stand-alone Lua console or Arcon's.

**Comment by jerryhebert** [comment]
Byrth ran into a strange bug earlier today. I spent a while trying to narrow it down and it turns out that it's this same problem again. Here is the repro I came up with, which is the result of deleting lots of stuff from battlemod:

```
function event_load()
    items = {}
    items[65535] = {id = ''}
    items[29324] = {id = ''}
    items[16924] = {enl = 'hocho'}

    write(items[16924]['enl'])
end


function event_target_change(...)
    -- This produces the nil element error
    write(items[16924]['enl'])
end
```

It's pretty much the same problem but there is no work-around this time. I tried with event_action() and event_target_change().

**Comment by z16** [comment]
Feels good to close this with a 'fixed' :)
