### ISSUE TITLE
Shortcuts Addon Bugs

### ISSUE THREAD

**Issue by Crevox** [Windower/Lua#949]
1) Whenever I have the "shortcuts" addon enabled, stuff appears in the console whenever I cast _some_ spells:

![image](https://cloud.githubusercontent.com/assets/6427024/3488656/dd23da32-04f8-11e4-8e3f-c27de9041644.png)
![image](https://cloud.githubusercontent.com/assets/6427024/3488657/e91413a2-04f8-11e4-8435-7c8d8763a79f.png)

It pops up every cast, even if the console is hidden. I have to use console_displayactivity 0 to make it stop. Unloading shortcuts also fixes it.

2) Error upon using Mending Halation and Radial Arcana.

![image](https://cloud.githubusercontent.com/assets/6427024/3534696/50d44292-07f0-11e4-9b58-8803e476e89e.png)

**Comment by Crevox** [comment]
Updated with a new bug.

**Comment by Byrth** [comment]
These should be fixed now. Closing the issue. Please re-open it if they reoccur.
