### ISSUE TITLE
gearswap request

### ISSUE THREAD

**Issue by smd111** [Windower/Lua#953]
is there any chance that using an item can be exposed in gearswap??

i.e for /item "Toolbag (Uchi)" <me>
spell.prefix = /item
spell.name = "Toolbag (Uchi)"
spell.target.raw = "<me>"

or something like that

**Comment by Byrth** [comment]
If you use an item using the /item command, that should all be exposed already.

**Comment by smd111** [comment]
ok ill check again

**Comment by smd111** [comment]
sorry it took so long for me to get back to you but no mater what i try i dont get any thing on aftercast when i use an item
/item "Toolbag (Uchi)" <me> --not from menu but by typing it in to chat
and when i check with this
add_to_chat(123,"Spell Table="..table.concat(spell, "/")) --i put this in filtered_action,precast,aftercast
it lists out all the spell info but does not show any thing for item --i dont even get an error which would normally happen

**Comment by smd111** [comment]
i went out side of gearswap do do this
with this code

```
require 'actions'
function event_action(act)
    action = Action(act)
    if action:get_category_string() == 'item_finish' then
        --this is ware my checks go
    end
end
windower.raw_register_event('action', event_action)
```

the cool part is this also work when using items from the menu

**Comment by Byrth** [comment]
Yeah, it should. I used to include menu items in my processing, but now I don't.

I also confirmed that the /item flow is broken and I'm not sure why. I'll look in to it later. I opened this issue, so I'll close this one:
https://github.com/Byrth/Lua/issues/277
