### ISSUE TITLE
Timers: Suggestions

### ISSUE THREAD

**Issue by ghost** [Windower/Lua#971]
Was wondering if you can add: 
Natures Meditation as attack buff and change the icon from question mark to the fire/red BLU magic icon?
Erratic Flutter new haste buff 5 min duration, currently doesn't show under buffs. Icon is Wind/Green
Thrashing Assault if you will change icon to physical BLU spell

**Comment by z16** [comment]
Can you check if the icons are still messed up?

We have no control over those, we use in-game icons for them, so I cannot change it. The reason it may not have been working right before was due to resources being out of date, so this may be fixed now.

How long does _Nature's Meditation_ last?

**Comment by ghost** [comment]
Nature's Meditation is 60 seconds.
Will test the icons once new dev version is up.

**Comment by ghost** [comment]
New suggestion:
Ability to hide icons
Ability to lengthen bars to accommodate longer ability names ex: Formless Strikes [Self]

**Comment by z16** [comment]
Implemented.
