### ISSUE TITLE
GearSwap: Error when equipping augmented gear

### ISSUE THREAD

**Issue by Crevox** [Windower/Lua#975]
In the case of you having an inventory of multiple augmented items of a certain type, and the same item  without any augments whatsoever of the same time, you get a runtime error upon trying to equip a set containing the augmented item.

As an example of the specific scenario that triggered this, I have three Hagondes Hats. One has pet magical accuracy, another has magical accuracy, and the other has no augments at all. If I try to script to equip the hat with pet magical accuracy, the script loads just fine with the definition of the item, but upon trying to equip the set that contains the item, it errors. If I put the Hagondes Hat with no augments into my Mog Case, the error is gone.

![image](https://cloud.githubusercontent.com/assets/6427024/3637593/d2e4a508-1013-11e4-86e0-839a957326c6.png)

**Comment by Byrth** [comment]
Thanks, I've fixed this. I'll push it to -dev and Live later tonight.
