### ISSUE TITLE
Timers: It's like extending downward the longer it's open

### ISSUE THREAD

**Issue by Crevox** [Windower/Lua#982]
The longer its open without a reload, it just goes further and further down. It just started doing this like a couple days ago.

Also dunno what's up with that Shining Ruby in the middle, that's never been there before, but I'll ignore that.

![image](https://cloud.githubusercontent.com/assets/6427024/3660426/8cdc2af4-11b7-11e4-9d7e-dbfe3abed90e.png)

**Comment by z16** [comment]
This is known and reported, we're working on it. 

Also this is the Lua tracker which is specifically for addon and Lua API issues, please report Windower issues on the regular issue tracker.
