### ISSUE TITLE
[Battlemod] Zantetsuken

### ISSUE THREAD

**Issue by Crevox** [Windower/Lua#988]
![image](https://cloud.githubusercontent.com/assets/6427024/3755023/d7bf7f7a-1820-11e4-9e5f-b53349df6383.png)

**Comment by SnickySnacks** [comment]
A missing status effect. 
I fix these as they get pointed out. 

I'll fix it up later tonight.

**Comment by SnickySnacks** [comment]
I put in a fix for this on the dev branch.
I'll test it a bit more and push it to live tomorrow after I get a little more time to test it.

**Comment by Byrth** [comment]
This has doubtlessly been pushed live already. I'm going to close the issue.
