### ISSUE TITLE
[Shortcuts] Elemental Magic pet bug

### ISSUE THREAD

**Issue by Crevox** [Windower/Lua#989]
Trying to shortcut elemental magic with an avatar out causes it to try to command the avatar to use that magic. If Blood Pact: Rage is on cooldown, it just displays recast timer in chat, and you cannot cast the magic.

Example: I have Leviathan out. I type the following:

/ma Water II

And Leviathan casts Water II. I want to cast Water II, not him.

**Comment by Byrth** [comment]
I'm going to reopen this on my tracker so I see it this weekend when I go through and smush bugs.
